/* Generated by Nim Compiler v0.18.0 */
/*   (c) 2018 Andreas Rumpf */
/* The generated code is subject to the original license. */
/* Compiled for: MacOSX, amd64, clang */
/* Command for C compiler:
   clang -c  -w  -I/Users/lowks/.asdf/installs/nim/v0.18.0/lib -o /Users/lowks/exercism/nim/word-count/nimcache/stdlib_critbits.o /Users/lowks/exercism/nim/word-count/nimcache/stdlib_critbits.c */
#define NIM_NEW_MANGLING_RULES
#define NIM_INTBITS 64

#include "nimbase.h"
#include <string.h>
#undef LANGUAGE_C
#undef MIPSEB
#undef MIPSEL
#undef PPC
#undef R3000
#undef R4000
#undef i386
#undef linux
#undef mips
#undef near
#undef powerpc
#undef unix
typedef struct tyObject_CritBitTree_kyjBlOvrqb2saoDaZxR9cWA tyObject_CritBitTree_kyjBlOvrqb2saoDaZxR9cWA;
typedef struct NimStringDesc NimStringDesc;
typedef struct TGenericSeq TGenericSeq;
typedef struct tyObject_NodeObj_s6B00BU456H1of4V8TzqOw tyObject_NodeObj_s6B00BU456H1of4V8TzqOw;
typedef struct TNimType TNimType;
typedef struct TNimNode TNimNode;
typedef struct tyObject_Cell_1zcF9cV8XIAtbN8h5HRUB8g tyObject_Cell_1zcF9cV8XIAtbN8h5HRUB8g;
typedef struct tyObject_CellSeq_Axo1XVm9aaQueTOldv8le5w tyObject_CellSeq_Axo1XVm9aaQueTOldv8le5w;
typedef struct tyObject_GcHeap_1TRH1TZMaVZTnLNcIHuNFQ tyObject_GcHeap_1TRH1TZMaVZTnLNcIHuNFQ;
typedef struct tyObject_GcStack_7fytPA5bBsob6See21YMRA tyObject_GcStack_7fytPA5bBsob6See21YMRA;
typedef struct tyObject_MemRegion_x81NhDv59b8ercDZ9bi85jyg tyObject_MemRegion_x81NhDv59b8ercDZ9bi85jyg;
typedef struct tyObject_SmallChunk_tXn60W2f8h3jgAYdEmy5NQ tyObject_SmallChunk_tXn60W2f8h3jgAYdEmy5NQ;
typedef struct tyObject_BigChunk_Rv9c70Uhp2TytkX7eH78qEg tyObject_BigChunk_Rv9c70Uhp2TytkX7eH78qEg;
typedef struct tyObject_LLChunk_XsENErzHIZV9bhvyJx56wGw tyObject_LLChunk_XsENErzHIZV9bhvyJx56wGw;
typedef struct tyObject_IntSet_EZObFrE3NC9bIb3YMkY9crZA tyObject_IntSet_EZObFrE3NC9bIb3YMkY9crZA;
typedef struct tyObject_Trunk_W0r8S0Y3UGke6T9bIUWnnuw tyObject_Trunk_W0r8S0Y3UGke6T9bIUWnnuw;
typedef struct tyObject_AvlNode_IaqjtwKhxLEpvDS9bct9blEw tyObject_AvlNode_IaqjtwKhxLEpvDS9bct9blEw;
typedef struct tyObject_HeapLinks_PDV1HBZ8CQSQJC9aOBFNRSg tyObject_HeapLinks_PDV1HBZ8CQSQJC9aOBFNRSg;
typedef struct tyTuple_ujsjpB2O9cjj3uDHsXbnSzg tyTuple_ujsjpB2O9cjj3uDHsXbnSzg;
typedef struct tyObject_GcStat_0RwLoVBHZPfUAcLczmfQAg tyObject_GcStat_0RwLoVBHZPfUAcLczmfQAg;
typedef struct tyObject_CellSet_jG87P0AI9aZtss9ccTYBIISQ tyObject_CellSet_jG87P0AI9aZtss9ccTYBIISQ;
typedef struct tyObject_PageDesc_fublkgIY4LG3mT51LU2WHg tyObject_PageDesc_fublkgIY4LG3mT51LU2WHg;
typedef struct tyObject_CritBitTree_W9co9c9b9bieBHo7glffSqTaOw tyObject_CritBitTree_W9co9c9b9bieBHo7glffSqTaOw;
typedef struct tyObject_NodeObj_xBU1K9bOAI19c7jtJRn2DFJw tyObject_NodeObj_xBU1K9bOAI19c7jtJRn2DFJw;
typedef struct tySequence_riGsizgBbQK4AtYOoYFFuw tySequence_riGsizgBbQK4AtYOoYFFuw;
typedef struct tyObject_BaseChunk_Sdq7WpT6qAH858F5ZEdG3w tyObject_BaseChunk_Sdq7WpT6qAH858F5ZEdG3w;
typedef struct tyObject_FreeCell_u6M5LHprqzkn9axr04yg9bGQ tyObject_FreeCell_u6M5LHprqzkn9axr04yg9bGQ;
struct TGenericSeq {
NI len;
NI reserved;
};
struct NimStringDesc {
  TGenericSeq Sup;
NIM_CHAR data[SEQ_DECL_SIZE];
};
struct tyObject_CritBitTree_kyjBlOvrqb2saoDaZxR9cWA {
tyObject_NodeObj_s6B00BU456H1of4V8TzqOw* root;
NI count;
};
typedef tyObject_NodeObj_s6B00BU456H1of4V8TzqOw* tyArray_WPLPge0ABYq4JBOh9aIrU5A[2];
struct tyObject_NodeObj_s6B00BU456H1of4V8TzqOw {
NI byte;
NIM_CHAR otherbits;
NIM_BOOL isLeaf;
union{
tyArray_WPLPge0ABYq4JBOh9aIrU5A child;
struct {NimStringDesc* key;
} S2;
} isLeafU;
};
typedef NU8 tyEnum_TNimKind_jIBKr1ejBgsfM33Kxw4j7A;
typedef NU8 tySet_tyEnum_TNimTypeFlag_v8QUszD1sWlSIWZz7mC4bQ;
typedef N_NIMCALL_PTR(void, tyProc_ojoeKfW4VYIm36I9cpDTQIg) (void* p, NI op);
typedef N_NIMCALL_PTR(void*, tyProc_WSm2xU5ARYv9aAR4l0z9c9auQ) (void* p);
struct TNimType {
NI size;
tyEnum_TNimKind_jIBKr1ejBgsfM33Kxw4j7A kind;
tySet_tyEnum_TNimTypeFlag_v8QUszD1sWlSIWZz7mC4bQ flags;
TNimType* base;
TNimNode* node;
void* finalizer;
tyProc_ojoeKfW4VYIm36I9cpDTQIg marker;
tyProc_WSm2xU5ARYv9aAR4l0z9c9auQ deepcopy;
};
typedef NU8 tyEnum_TNimNodeKind_unfNsxrcATrufDZmpBq4HQ;
struct TNimNode {
tyEnum_TNimNodeKind_unfNsxrcATrufDZmpBq4HQ kind;
NI offset;
TNimType* typ;
NCSTRING name;
NI len;
TNimNode** sons;
};
struct tyObject_Cell_1zcF9cV8XIAtbN8h5HRUB8g {
NI refcount;
TNimType* typ;
};
struct tyObject_GcStack_7fytPA5bBsob6See21YMRA {
void* bottom;
};
struct tyObject_CellSeq_Axo1XVm9aaQueTOldv8le5w {
NI len;
NI cap;
tyObject_Cell_1zcF9cV8XIAtbN8h5HRUB8g** d;
};
typedef tyObject_SmallChunk_tXn60W2f8h3jgAYdEmy5NQ* tyArray_SiRwrEKZdLgxqz9a9aoVBglg[512];
typedef NU32 tyArray_BHbOSqU1t9b3Gt7K2c6fQig[24];
typedef tyObject_BigChunk_Rv9c70Uhp2TytkX7eH78qEg* tyArray_N1u1nqOgmuJN9cSZrnMHgOQ[32];
typedef tyArray_N1u1nqOgmuJN9cSZrnMHgOQ tyArray_B6durA4ZCi1xjJvRtyYxMg[24];
typedef tyObject_Trunk_W0r8S0Y3UGke6T9bIUWnnuw* tyArray_lh2A89ahMmYg9bCmpVaplLbA[256];
struct tyObject_IntSet_EZObFrE3NC9bIb3YMkY9crZA {
tyArray_lh2A89ahMmYg9bCmpVaplLbA data;
};
typedef tyObject_AvlNode_IaqjtwKhxLEpvDS9bct9blEw* tyArray_0aOLqZchNi8nWtMTi8ND8w[2];
struct tyObject_AvlNode_IaqjtwKhxLEpvDS9bct9blEw {
tyArray_0aOLqZchNi8nWtMTi8ND8w link;
NI key;
NI upperBound;
NI level;
};
struct tyTuple_ujsjpB2O9cjj3uDHsXbnSzg {
tyObject_BigChunk_Rv9c70Uhp2TytkX7eH78qEg* Field0;
NI Field1;
};
typedef tyTuple_ujsjpB2O9cjj3uDHsXbnSzg tyArray_LzOv2eCDGiceMKQstCLmhw[30];
struct tyObject_HeapLinks_PDV1HBZ8CQSQJC9aOBFNRSg {
NI len;
tyArray_LzOv2eCDGiceMKQstCLmhw chunks;
tyObject_HeapLinks_PDV1HBZ8CQSQJC9aOBFNRSg* next;
};
struct tyObject_MemRegion_x81NhDv59b8ercDZ9bi85jyg {
NI minLargeObj;
NI maxLargeObj;
tyArray_SiRwrEKZdLgxqz9a9aoVBglg freeSmallChunks;
NU32 flBitmap;
tyArray_BHbOSqU1t9b3Gt7K2c6fQig slBitmap;
tyArray_B6durA4ZCi1xjJvRtyYxMg matrix;
tyObject_LLChunk_XsENErzHIZV9bhvyJx56wGw* llmem;
NI currMem;
NI maxMem;
NI freeMem;
NI occ;
NI lastSize;
tyObject_IntSet_EZObFrE3NC9bIb3YMkY9crZA chunkStarts;
tyObject_AvlNode_IaqjtwKhxLEpvDS9bct9blEw* root;
tyObject_AvlNode_IaqjtwKhxLEpvDS9bct9blEw* deleted;
tyObject_AvlNode_IaqjtwKhxLEpvDS9bct9blEw* last;
tyObject_AvlNode_IaqjtwKhxLEpvDS9bct9blEw* freeAvlNodes;
NIM_BOOL locked;
NIM_BOOL blockChunkSizeIncrease;
NI nextChunkSize;
tyObject_AvlNode_IaqjtwKhxLEpvDS9bct9blEw bottomData;
tyObject_HeapLinks_PDV1HBZ8CQSQJC9aOBFNRSg heapLinks;
};
struct tyObject_GcStat_0RwLoVBHZPfUAcLczmfQAg {
NI stackScans;
NI cycleCollections;
NI maxThreshold;
NI maxStackSize;
NI maxStackCells;
NI cycleTableSize;
NI64 maxPause;
};
struct tyObject_CellSet_jG87P0AI9aZtss9ccTYBIISQ {
NI counter;
NI max;
tyObject_PageDesc_fublkgIY4LG3mT51LU2WHg* head;
tyObject_PageDesc_fublkgIY4LG3mT51LU2WHg** data;
};
struct tyObject_GcHeap_1TRH1TZMaVZTnLNcIHuNFQ {
tyObject_GcStack_7fytPA5bBsob6See21YMRA stack;
NI cycleThreshold;
tyObject_CellSeq_Axo1XVm9aaQueTOldv8le5w zct;
tyObject_CellSeq_Axo1XVm9aaQueTOldv8le5w decStack;
tyObject_CellSeq_Axo1XVm9aaQueTOldv8le5w tempStack;
NI recGcLock;
tyObject_MemRegion_x81NhDv59b8ercDZ9bi85jyg region;
tyObject_GcStat_0RwLoVBHZPfUAcLczmfQAg stat;
tyObject_CellSet_jG87P0AI9aZtss9ccTYBIISQ marked;
tyObject_CellSeq_Axo1XVm9aaQueTOldv8le5w additionalRoots;
NI gcThreadId;
};
struct tyObject_CritBitTree_W9co9c9b9bieBHo7glffSqTaOw {
tyObject_NodeObj_xBU1K9bOAI19c7jtJRn2DFJw* root;
NI count;
};
typedef tyObject_NodeObj_xBU1K9bOAI19c7jtJRn2DFJw* tyArray_GRcX7rp8rN75VPNIuX8x7g[2];
struct tyObject_NodeObj_xBU1K9bOAI19c7jtJRn2DFJw {
NI byte;
NIM_CHAR otherbits;
NIM_BOOL isLeaf;
union{
tyArray_GRcX7rp8rN75VPNIuX8x7g child;
struct {NimStringDesc* key;
NI val;
} S2;
} isLeafU;
};
typedef NU8 tyEnum_TNimTypeFlag_v8QUszD1sWlSIWZz7mC4bQ;
typedef NU8 tyEnum_WalkOp_Wfy7gT5VQ8B3aJBxqU8D9cQ;
struct tyObject_BaseChunk_Sdq7WpT6qAH858F5ZEdG3w {
NI prevSize;
NI size;
};
struct tyObject_SmallChunk_tXn60W2f8h3jgAYdEmy5NQ {
  tyObject_BaseChunk_Sdq7WpT6qAH858F5ZEdG3w Sup;
tyObject_SmallChunk_tXn60W2f8h3jgAYdEmy5NQ* next;
tyObject_SmallChunk_tXn60W2f8h3jgAYdEmy5NQ* prev;
tyObject_FreeCell_u6M5LHprqzkn9axr04yg9bGQ* freeList;
NI free;
NI acc;
NF data;
};
struct tyObject_BigChunk_Rv9c70Uhp2TytkX7eH78qEg {
  tyObject_BaseChunk_Sdq7WpT6qAH858F5ZEdG3w Sup;
tyObject_BigChunk_Rv9c70Uhp2TytkX7eH78qEg* next;
tyObject_BigChunk_Rv9c70Uhp2TytkX7eH78qEg* prev;
NF data;
};
struct tyObject_LLChunk_XsENErzHIZV9bhvyJx56wGw {
NI size;
NI acc;
tyObject_LLChunk_XsENErzHIZV9bhvyJx56wGw* next;
};
typedef NI tyArray_9a8QARi5WsUggNU9bom7kzTQ[8];
struct tyObject_Trunk_W0r8S0Y3UGke6T9bIUWnnuw {
tyObject_Trunk_W0r8S0Y3UGke6T9bIUWnnuw* next;
NI key;
tyArray_9a8QARi5WsUggNU9bom7kzTQ bits;
};
struct tyObject_PageDesc_fublkgIY4LG3mT51LU2WHg {
tyObject_PageDesc_fublkgIY4LG3mT51LU2WHg* next;
NI key;
tyArray_9a8QARi5WsUggNU9bom7kzTQ bits;
};
struct tyObject_FreeCell_u6M5LHprqzkn9axr04yg9bGQ {
tyObject_FreeCell_u6M5LHprqzkn9axr04yg9bGQ* next;
NI zeroField;
};
struct tySequence_riGsizgBbQK4AtYOoYFFuw {
  TGenericSeq Sup;
  tyObject_NodeObj_xBU1K9bOAI19c7jtJRn2DFJw* data[SEQ_DECL_SIZE];
};
N_LIB_PRIVATE N_NIMCALL(NIM_BOOL, containsOrIncl_6jTqr539bj9a9bXz9cQHn5OV9cg)(tyObject_CritBitTree_kyjBlOvrqb2saoDaZxR9cWA* c, NimStringDesc* key);
N_LIB_PRIVATE N_NIMCALL(tyObject_NodeObj_s6B00BU456H1of4V8TzqOw*, rawInsert_TO4O1pgmb8x1EXOER8mT5g)(tyObject_CritBitTree_kyjBlOvrqb2saoDaZxR9cWA* c, NimStringDesc* key);
N_NIMCALL(void, nimGCvisit)(void* d, NI op);
static N_NIMCALL(void, Marker_tyRef_1CYpj5Dhx2VK3Ym59czDTcQ)(void* p, NI op);
N_NIMCALL(void*, newObj)(TNimType* typ, NI size);
N_NIMCALL(void, unsureAsgnRef)(void** dest, void* src);
N_NIMCALL(void, FieldDiscriminantCheck)(NI oldDiscVal, NI newDiscVal, TNimNode** a, NI L);
N_NOINLINE(void, raiseFieldError)(NimStringDesc* f);
N_NIMCALL(NimStringDesc*, copyStringRC1)(NimStringDesc* src);
static N_INLINE(void, nimGCunrefNoCycle)(void* p);
static N_INLINE(tyObject_Cell_1zcF9cV8XIAtbN8h5HRUB8g*, usrToCell_yB9aH5WIlwd0xkYrcdPeXrQsystem)(void* usr);
static N_INLINE(void, nimFrame)(TFrame* s);
N_LIB_PRIVATE N_NOINLINE(void, stackOverflow_II46IjNZztN9bmbxUD8dt8g)(void);
static N_INLINE(void, popFrame)(void);
static N_INLINE(void, rtlAddZCT_MV4BBk6J1qu70IbBxwEn4w_2system)(tyObject_Cell_1zcF9cV8XIAtbN8h5HRUB8g* c);
N_LIB_PRIVATE N_NOINLINE(void, addZCT_fCDI7oO1NNVXXURtxSzsRw)(tyObject_CellSeq_Axo1XVm9aaQueTOldv8le5w* s, tyObject_Cell_1zcF9cV8XIAtbN8h5HRUB8g* c);
N_NOINLINE(void, raiseIndexError)(void);
static N_INLINE(NI, addInt)(NI a, NI b);
N_NOINLINE(void, raiseOverflow)(void);
static N_INLINE(NI, subInt)(NI a, NI b);
static N_INLINE(NI, chckRange)(NI i, NI a, NI b);
N_NOINLINE(void, raiseRangeError)(NI64 val);
static N_INLINE(void, asgnRefNoCycle)(void** dest, void* src);
N_LIB_PRIVATE N_NIMCALL(void, inc_8YmcVDWhRuEPpJvI5tDYBQ)(tyObject_CritBitTree_W9co9c9b9bieBHo7glffSqTaOw* c, NimStringDesc* key);
N_LIB_PRIVATE N_NIMCALL(tyObject_NodeObj_xBU1K9bOAI19c7jtJRn2DFJw*, rawInsert_It5l6XNiy8yPa2z0rsJ69cw)(tyObject_CritBitTree_W9co9c9b9bieBHo7glffSqTaOw* c, NimStringDesc* key);
static N_NIMCALL(void, Marker_tyRef_2iDqjPqOFZmNCE6zfQbG4g)(void* p, NI op);
N_LIB_PRIVATE N_NIMCALL(void, incl_imDOJIOfVlx8JBSwN1tyQg)(tyObject_CritBitTree_kyjBlOvrqb2saoDaZxR9cWA* c, NimStringDesc* key);
static N_INLINE(NIM_BOOL, eqStrings)(NimStringDesc* a, NimStringDesc* b);
static N_INLINE(NIM_BOOL, equalMem_fmeFeLBvgmAHG9bC8ETS9bYQsystem)(void* a, void* b, NI size);
N_LIB_PRIVATE N_NIMCALL(NI, len_tr1EAKWlDHjUSryZUXVzyg)(tyObject_CritBitTree_W9co9c9b9bieBHo7glffSqTaOw c);
N_NIMCALL(NimStringDesc*, copyString)(NimStringDesc* src);
N_NIMCALL(NimStringDesc*, rawNewString)(NI space);
N_NIMCALL(NimStringDesc*, rawNewString)(NI cap);
N_NIMCALL(NI, mulInt)(NI a, NI b);
static N_INLINE(void, appendString)(NimStringDesc* dest, NimStringDesc* src);
static N_INLINE(void, copyMem_E1xtACub5WcDa3vbrIXbwgsystem)(void* dest, void* source, NI size);
N_NIMCALL(NimStringDesc*, resizeString)(NimStringDesc* dest, NI addlen);
N_NIMCALL(void*, newSeq)(TNimType* typ, NI len);
static N_INLINE(tyObject_NodeObj_xBU1K9bOAI19c7jtJRn2DFJw*, pop_Yw8TX1ShKvAyRG7AcrRflAword_count_test)(tySequence_riGsizgBbQK4AtYOoYFFuw** s);
static N_INLINE(TGenericSeq*, setLengthSeq)(TGenericSeq* seq, NI elemSize, NI newLen);
static N_INLINE(NI, resize_bzF9a0JivP3Z4njqaxuLc5wsystem)(NI old);
N_LIB_PRIVATE N_NIMCALL(void*, growObj_AVYny8c0GTk28gxjmat1MA)(void* old, NI newsize);
N_NIMCALL(TNimType*, extGetCellType)(void* c);
N_LIB_PRIVATE N_NIMCALL(void, forAllChildrenAux_YOI1Uo54H9aas13WthjhsfA)(void* dest, TNimType* mt, tyEnum_WalkOp_Wfy7gT5VQ8B3aJBxqU8D9cQ op);
static N_INLINE(void, zeroMem_t0o5XqKanO5QJfXMGEzp2Asystem)(void* p, NI size);
N_NIMCALL(TGenericSeq*, incrSeqV2)(TGenericSeq* seq, NI elemSize);
N_LIB_PRIVATE N_NIMCALL(void, failedAssertImpl_aDmpBTs9cPuXp0Mp9cfiNeyA)(NimStringDesc* msg);
N_LIB_PRIVATE N_NIMCALL(void, addQuoted_nyaZAljVI03SH2d9cnD0WMw)(NimStringDesc** s, NI x);
TNimType NTI_s6B00BU456H1of4V8TzqOw_;
extern TNimType NTI_rR5Bzr1D5krxoo1NcNyeMA_;
extern TNimType NTI_nmiMWKVIe46vacnhAFrQvw_;
extern TNimType NTI_VaVACK0bpYmqIQ0mKcHfQQ_;
TNimType NTI_WPLPge0ABYq4JBOh9aIrU5A_;
extern TNimType NTI_77mFvmsOLKik79ci2hXkHEg_;
TNimType NTI_1CYpj5Dhx2VK3Ym59czDTcQ_;
extern TNimNode* NimDT__s6B00BU456H1of4V8TzqOw_isLeaf[3];
extern TFrame* framePtr_HRfVMH3jYeBJz6Q6X9b6Ptw;
extern tyObject_GcHeap_1TRH1TZMaVZTnLNcIHuNFQ gch_IcYaEuuWivYAS86vFMTS3Q;
TNimType NTI_xBU1K9bOAI19c7jtJRn2DFJw_;
TNimType NTI_GRcX7rp8rN75VPNIuX8x7g_;
TNimType NTI_2iDqjPqOFZmNCE6zfQbG4g_;
extern TNimNode* NimDT__xBU1K9bOAI19c7jtJRn2DFJw_isLeaf[3];
TNimType NTI_W9co9c9b9bieBHo7glffSqTaOw_;
extern TNimType NTI_riGsizgBbQK4AtYOoYFFuw_;
TNimNode* NimDT__s6B00BU456H1of4V8TzqOw_isLeaf[3];
STRING_LITERAL(TM_PZbQ6FnMafyICMjEl6Mgfg_4, "key", 3);
STRING_LITERAL(TM_PZbQ6FnMafyICMjEl6Mgfg_6, "child", 5);
TNimNode* NimDT__xBU1K9bOAI19c7jtJRn2DFJw_isLeaf[3];
STRING_LITERAL(TM_PZbQ6FnMafyICMjEl6Mgfg_24, "val", 3);
STRING_LITERAL(TM_PZbQ6FnMafyICMjEl6Mgfg_28, "{:}", 3);
STRING_LITERAL(TM_PZbQ6FnMafyICMjEl6Mgfg_30, "{", 1);
STRING_LITERAL(TM_PZbQ6FnMafyICMjEl6Mgfg_32, "\012not (it == nil) ", 17);
STRING_LITERAL(TM_PZbQ6FnMafyICMjEl6Mgfg_33, ", ", 2);
STRING_LITERAL(TM_PZbQ6FnMafyICMjEl6Mgfg_34, ": ", 2);
STRING_LITERAL(TM_PZbQ6FnMafyICMjEl6Mgfg_35, "}", 1);
static N_NIMCALL(void, Marker_tyRef_1CYpj5Dhx2VK3Ym59czDTcQ)(void* p, NI op) {
	tyObject_NodeObj_s6B00BU456H1of4V8TzqOw* a;
	NI T1_;
	a = (tyObject_NodeObj_s6B00BU456H1of4V8TzqOw*)p;
	switch ((*a).isLeaf) {
	case NIM_FALSE:
	T1_ = (NI)0;
	for (T1_ = 0; T1_ < 2; T1_++) {
	nimGCvisit((void*)(*a).isLeafU.child[T1_], op);
	}
	break;
	case NIM_TRUE:
	nimGCvisit((void*)(*a).isLeafU.S2.key, op);
	break;
	} 
}

static N_INLINE(void, nimFrame)(TFrame* s) {
	NI T1_;
	T1_ = (NI)0;
	{
		if (!(framePtr_HRfVMH3jYeBJz6Q6X9b6Ptw == NIM_NIL)) goto LA4_;
		T1_ = ((NI) 0);
	}
	goto LA2_;
	LA4_: ;
	{
		T1_ = ((NI) ((NI16)((*framePtr_HRfVMH3jYeBJz6Q6X9b6Ptw).calldepth + ((NI16) 1))));
	}
	LA2_: ;
	(*s).calldepth = ((NI16) (T1_));
	(*s).prev = framePtr_HRfVMH3jYeBJz6Q6X9b6Ptw;
	framePtr_HRfVMH3jYeBJz6Q6X9b6Ptw = s;
	{
		if (!((*s).calldepth == ((NI16) 2000))) goto LA9_;
		stackOverflow_II46IjNZztN9bmbxUD8dt8g();
	}
	LA9_: ;
}

static N_INLINE(void, popFrame)(void) {
	framePtr_HRfVMH3jYeBJz6Q6X9b6Ptw = (*framePtr_HRfVMH3jYeBJz6Q6X9b6Ptw).prev;
}

static N_INLINE(tyObject_Cell_1zcF9cV8XIAtbN8h5HRUB8g*, usrToCell_yB9aH5WIlwd0xkYrcdPeXrQsystem)(void* usr) {
	tyObject_Cell_1zcF9cV8XIAtbN8h5HRUB8g* result;
	nimfr_("usrToCell", "gc.nim");
	result = (tyObject_Cell_1zcF9cV8XIAtbN8h5HRUB8g*)0;
	nimln_(132, "gc.nim");
	result = ((tyObject_Cell_1zcF9cV8XIAtbN8h5HRUB8g*) ((NI)((NU64)(((NI) (ptrdiff_t) (usr))) - (NU64)(((NI)sizeof(tyObject_Cell_1zcF9cV8XIAtbN8h5HRUB8g))))));
	popFrame();
	return result;
}

static N_INLINE(void, rtlAddZCT_MV4BBk6J1qu70IbBxwEn4w_2system)(tyObject_Cell_1zcF9cV8XIAtbN8h5HRUB8g* c) {
	nimfr_("rtlAddZCT", "gc.nim");
	nimln_(211, "gc.nim");
	addZCT_fCDI7oO1NNVXXURtxSzsRw((&gch_IcYaEuuWivYAS86vFMTS3Q.zct), c);
	popFrame();
}

static N_INLINE(void, nimGCunrefNoCycle)(void* p) {
	tyObject_Cell_1zcF9cV8XIAtbN8h5HRUB8g* c;
	nimfr_("nimGCunrefNoCycle", "gc.nim");
	nimln_(250, "gc.nim");
	c = usrToCell_yB9aH5WIlwd0xkYrcdPeXrQsystem(p);
	nimln_(252, "gc.nim");
	{
		(*c).refcount -= ((NI) 8);
		if (!((NU64)((*c).refcount) < (NU64)(((NI) 8)))) goto LA3_;
		nimln_(253, "gc.nim");
		rtlAddZCT_MV4BBk6J1qu70IbBxwEn4w_2system(c);
	}
	LA3_: ;
	popFrame();
}

static N_INLINE(NI, addInt)(NI a, NI b) {
	NI result;
{	result = (NI)0;
	result = (NI)((NU64)(a) + (NU64)(b));
	{
		NIM_BOOL T3_;
		T3_ = (NIM_BOOL)0;
		T3_ = (((NI) 0) <= (NI)(result ^ a));
		if (T3_) goto LA4_;
		T3_ = (((NI) 0) <= (NI)(result ^ b));
		LA4_: ;
		if (!T3_) goto LA5_;
		goto BeforeRet_;
	}
	LA5_: ;
	raiseOverflow();
	}BeforeRet_: ;
	return result;
}

static N_INLINE(NI, subInt)(NI a, NI b) {
	NI result;
{	result = (NI)0;
	result = (NI)((NU64)(a) - (NU64)(b));
	{
		NIM_BOOL T3_;
		T3_ = (NIM_BOOL)0;
		T3_ = (((NI) 0) <= (NI)(result ^ a));
		if (T3_) goto LA4_;
		T3_ = (((NI) 0) <= (NI)(result ^ (NI)((NU64) ~(b))));
		LA4_: ;
		if (!T3_) goto LA5_;
		goto BeforeRet_;
	}
	LA5_: ;
	raiseOverflow();
	}BeforeRet_: ;
	return result;
}

static N_INLINE(NI, chckRange)(NI i, NI a, NI b) {
	NI result;
{	result = (NI)0;
	{
		NIM_BOOL T3_;
		T3_ = (NIM_BOOL)0;
		T3_ = (a <= i);
		if (!(T3_)) goto LA4_;
		T3_ = (i <= b);
		LA4_: ;
		if (!T3_) goto LA5_;
		result = i;
		goto BeforeRet_;
	}
	goto LA1_;
	LA5_: ;
	{
		raiseRangeError(((NI64) (i)));
	}
	LA1_: ;
	}BeforeRet_: ;
	return result;
}

static N_INLINE(void, asgnRefNoCycle)(void** dest, void* src) {
	nimfr_("asgnRefNoCycle", "gc.nim");
	nimln_(271, "gc.nim");
	{
		tyObject_Cell_1zcF9cV8XIAtbN8h5HRUB8g* c;
		nimln_(398, "system.nim");
		nimln_(271, "gc.nim");
		if (!!((src == NIM_NIL))) goto LA3_;
		nimln_(272, "gc.nim");
		c = usrToCell_yB9aH5WIlwd0xkYrcdPeXrQsystem(src);
		nimln_(273, "gc.nim");
		(*c).refcount += ((NI) 8);
	}
	LA3_: ;
	nimln_(274, "gc.nim");
	{
		tyObject_Cell_1zcF9cV8XIAtbN8h5HRUB8g* c_2;
		nimln_(398, "system.nim");
		nimln_(274, "gc.nim");
		if (!!(((*dest) == NIM_NIL))) goto LA7_;
		nimln_(275, "gc.nim");
		c_2 = usrToCell_yB9aH5WIlwd0xkYrcdPeXrQsystem((*dest));
		nimln_(276, "gc.nim");
		{
			(*c_2).refcount -= ((NI) 8);
			if (!((NU64)((*c_2).refcount) < (NU64)(((NI) 8)))) goto LA11_;
			nimln_(277, "gc.nim");
			rtlAddZCT_MV4BBk6J1qu70IbBxwEn4w_2system(c_2);
		}
		LA11_: ;
	}
	LA7_: ;
	nimln_(278, "gc.nim");
	(*dest) = src;
	popFrame();
}

N_LIB_PRIVATE N_NIMCALL(tyObject_NodeObj_s6B00BU456H1of4V8TzqOw*, rawInsert_TO4O1pgmb8x1EXOER8mT5g)(tyObject_CritBitTree_kyjBlOvrqb2saoDaZxR9cWA* c, NimStringDesc* key) {
	tyObject_NodeObj_s6B00BU456H1of4V8TzqOw* result;
	NI TM_PZbQ6FnMafyICMjEl6Mgfg_13;
	nimfr_("rawInsert", "critbits.nim");
{	result = (tyObject_NodeObj_s6B00BU456H1of4V8TzqOw*)0;
	nimln_(61, "critbits.nim");
	{
		NIM_BOOL T5_;
		NimStringDesc* T6_;
		if (!((*c).root == NIM_NIL)) goto LA3_;
		nimln_(62, "critbits.nim");
		unsureAsgnRef((void**) (&(*c).root), (tyObject_NodeObj_s6B00BU456H1of4V8TzqOw*) newObj((&NTI_1CYpj5Dhx2VK3Ym59czDTcQ_), sizeof(tyObject_NodeObj_s6B00BU456H1of4V8TzqOw)));
		nimln_(63, "critbits.nim");
		T5_ = (NIM_BOOL)0;
		T5_ = NIM_TRUE;
		FieldDiscriminantCheck((NI)(NU)((*(*c).root).isLeaf), (NI)(NU)(T5_), NimDT__s6B00BU456H1of4V8TzqOw_isLeaf, 3);
		(*(*c).root).isLeaf = T5_;
		if (!(((2 &(1U<<((NU)((*(*c).root).isLeaf)&7U)))!=0))) raiseFieldError(((NimStringDesc*) &TM_PZbQ6FnMafyICMjEl6Mgfg_4));
		nimln_(64, "critbits.nim");
		T6_ = (NimStringDesc*)0;
		T6_ = (*(*c).root).isLeafU.S2.key; (*(*c).root).isLeafU.S2.key = copyStringRC1(key);
		if (T6_) nimGCunrefNoCycle(T6_);
		nimln_(65, "critbits.nim");
		result = (*c).root;
	}
	goto LA1_;
	LA3_: ;
	{
		tyObject_NodeObj_s6B00BU456H1of4V8TzqOw* it;
		NI newOtherBits;
		NI newByte;
		NIM_CHAR ch_2;
		NI dir_2;
		NI TM_PZbQ6FnMafyICMjEl6Mgfg_10;
		tyObject_NodeObj_s6B00BU456H1of4V8TzqOw* inner;
		NIM_BOOL T29_;
		NimStringDesc* T30_;
		NI TM_PZbQ6FnMafyICMjEl6Mgfg_11;
		tyObject_NodeObj_s6B00BU456H1of4V8TzqOw** wherep;
		nimln_(67, "critbits.nim");
		it = (*c).root;
		{
			nimln_(68, "critbits.nim");
			while (1) {
				NIM_CHAR ch;
				NI dir;
				NI TM_PZbQ6FnMafyICMjEl6Mgfg_5;
				if (!!((*it).isLeaf)) goto LA9;
				nimln_(69, "critbits.nim");
				{
					if (!((*it).byte < (key ? key->Sup.len : 0))) goto LA12_;
					if ((NU)((*it).byte) > (NU)(key->Sup.len)) raiseIndexError();
					ch = key->data[(*it).byte];
				}
				goto LA10_;
				LA12_: ;
				{
					ch = 0;
				}
				LA10_: ;
				nimln_(70, "critbits.nim");
				TM_PZbQ6FnMafyICMjEl6Mgfg_5 = addInt(((NI) 1), (NI)(((NU8)(ch)) | ((NU8)((*it).otherbits))));
				dir = (NI)((NU64)((NI)(TM_PZbQ6FnMafyICMjEl6Mgfg_5)) >> (NU64)(((NI) 8)));
				nimln_(71, "critbits.nim");
				if (!(((1 &(1U<<((NU)((*it).isLeaf)&7U)))!=0))) raiseFieldError(((NimStringDesc*) &TM_PZbQ6FnMafyICMjEl6Mgfg_6));
				if ((NU)(dir) > (NU)(1)) raiseIndexError();
				it = (*it).isLeafU.child[(dir)- 0];
			} LA9: ;
		}
		nimln_(73, "critbits.nim");
		newOtherBits = ((NI) 0);
		nimln_(74, "critbits.nim");
		newByte = ((NI) 0);
		{
			{
				nimln_(76, "critbits.nim");
				while (1) {
					NI TM_PZbQ6FnMafyICMjEl6Mgfg_7;
					if (!(newByte < (key ? key->Sup.len : 0))) goto LA17;
					nimln_(77, "critbits.nim");
					{
						nimln_(398, "system.nim");
						nimln_(77, "critbits.nim");
						if (!(((2 &(1U<<((NU)((*it).isLeaf)&7U)))!=0))) raiseFieldError(((NimStringDesc*) &TM_PZbQ6FnMafyICMjEl6Mgfg_4));
						if ((NU)(newByte) > (NU)((*it).isLeafU.S2.key->Sup.len)) raiseIndexError();
						if ((NU)(newByte) > (NU)(key->Sup.len)) raiseIndexError();
						if (!!(((NU8)((*it).isLeafU.S2.key->data[newByte]) == (NU8)(key->data[newByte])))) goto LA20_;
						nimln_(78, "critbits.nim");
						if (!(((2 &(1U<<((NU)((*it).isLeaf)&7U)))!=0))) raiseFieldError(((NimStringDesc*) &TM_PZbQ6FnMafyICMjEl6Mgfg_4));
						if ((NU)(newByte) > (NU)((*it).isLeafU.S2.key->Sup.len)) raiseIndexError();
						if ((NU)(newByte) > (NU)(key->Sup.len)) raiseIndexError();
						newOtherBits = (NI)(((NU8)((*it).isLeafU.S2.key->data[newByte])) ^ ((NU8)(key->data[newByte])));
						nimln_(79, "critbits.nim");
						goto LA15;
					}
					LA20_: ;
					nimln_(80, "critbits.nim");
					TM_PZbQ6FnMafyICMjEl6Mgfg_7 = addInt(newByte, ((NI) 1));
					newByte = (NI)(TM_PZbQ6FnMafyICMjEl6Mgfg_7);
				} LA17: ;
			}
			nimln_(81, "critbits.nim");
			{
				nimln_(398, "system.nim");
				nimln_(81, "critbits.nim");
				if (!(((2 &(1U<<((NU)((*it).isLeaf)&7U)))!=0))) raiseFieldError(((NimStringDesc*) &TM_PZbQ6FnMafyICMjEl6Mgfg_4));
				if ((NU)(newByte) > (NU)((*it).isLeafU.S2.key->Sup.len)) raiseIndexError();
				if (!!(((NU8)((*it).isLeafU.S2.key->data[newByte]) == (NU8)(0)))) goto LA24_;
				nimln_(82, "critbits.nim");
				if (!(((2 &(1U<<((NU)((*it).isLeaf)&7U)))!=0))) raiseFieldError(((NimStringDesc*) &TM_PZbQ6FnMafyICMjEl6Mgfg_4));
				if ((NU)(newByte) > (NU)((*it).isLeafU.S2.key->Sup.len)) raiseIndexError();
				newOtherBits = ((NU8)((*it).isLeafU.S2.key->data[newByte]));
			}
			goto LA22_;
			LA24_: ;
			{
				nimln_(84, "critbits.nim");
				result = it;
				goto BeforeRet_;
			}
			LA22_: ;
		} LA15: ;
		{
			nimln_(85, "critbits.nim");
			while (1) {
				NI TM_PZbQ6FnMafyICMjEl6Mgfg_8;
				NI TM_PZbQ6FnMafyICMjEl6Mgfg_9;
				nimln_(398, "system.nim");
				nimln_(85, "critbits.nim");
				TM_PZbQ6FnMafyICMjEl6Mgfg_8 = subInt(newOtherBits, ((NI) 1));
				if (!!(((NI)(newOtherBits & (NI)(TM_PZbQ6FnMafyICMjEl6Mgfg_8)) == ((NI) 0)))) goto LA28;
				nimln_(86, "critbits.nim");
				TM_PZbQ6FnMafyICMjEl6Mgfg_9 = subInt(newOtherBits, ((NI) 1));
				newOtherBits = (NI)(newOtherBits & (NI)(TM_PZbQ6FnMafyICMjEl6Mgfg_9));
			} LA28: ;
		}
		nimln_(87, "critbits.nim");
		newOtherBits = (NI)(newOtherBits ^ ((NI) 255));
		nimln_(88, "critbits.nim");
		if (!(((2 &(1U<<((NU)((*it).isLeaf)&7U)))!=0))) raiseFieldError(((NimStringDesc*) &TM_PZbQ6FnMafyICMjEl6Mgfg_4));
		if ((NU)(newByte) > (NU)((*it).isLeafU.S2.key->Sup.len)) raiseIndexError();
		ch_2 = (*it).isLeafU.S2.key->data[newByte];
		nimln_(89, "critbits.nim");
		TM_PZbQ6FnMafyICMjEl6Mgfg_10 = addInt(((NI) 1), (NI)(((NU8)(ch_2)) | newOtherBits));
		dir_2 = (NI)((NU64)((NI)(TM_PZbQ6FnMafyICMjEl6Mgfg_10)) >> (NU64)(((NI) 8)));
		inner = (tyObject_NodeObj_s6B00BU456H1of4V8TzqOw*)0;
		nimln_(92, "critbits.nim");
		inner = (tyObject_NodeObj_s6B00BU456H1of4V8TzqOw*) newObj((&NTI_1CYpj5Dhx2VK3Ym59czDTcQ_), sizeof(tyObject_NodeObj_s6B00BU456H1of4V8TzqOw));
		nimln_(93, "critbits.nim");
		result = (tyObject_NodeObj_s6B00BU456H1of4V8TzqOw*) newObj((&NTI_1CYpj5Dhx2VK3Ym59czDTcQ_), sizeof(tyObject_NodeObj_s6B00BU456H1of4V8TzqOw));
		nimln_(94, "critbits.nim");
		T29_ = (NIM_BOOL)0;
		T29_ = NIM_TRUE;
		FieldDiscriminantCheck((NI)(NU)((*result).isLeaf), (NI)(NU)(T29_), NimDT__s6B00BU456H1of4V8TzqOw_isLeaf, 3);
		(*result).isLeaf = T29_;
		if (!(((2 &(1U<<((NU)((*result).isLeaf)&7U)))!=0))) raiseFieldError(((NimStringDesc*) &TM_PZbQ6FnMafyICMjEl6Mgfg_4));
		nimln_(95, "critbits.nim");
		T30_ = (NimStringDesc*)0;
		T30_ = (*result).isLeafU.S2.key; (*result).isLeafU.S2.key = copyStringRC1(key);
		if (T30_) nimGCunrefNoCycle(T30_);
		nimln_(96, "critbits.nim");
		(*inner).otherbits = ((NIM_CHAR) (((NI)chckRange(newOtherBits, ((NI) 0), ((NI) 255)))));
		nimln_(97, "critbits.nim");
		(*inner).byte = newByte;
		if (!(((1 &(1U<<((NU)((*inner).isLeaf)&7U)))!=0))) raiseFieldError(((NimStringDesc*) &TM_PZbQ6FnMafyICMjEl6Mgfg_6));
		nimln_(98, "critbits.nim");
		TM_PZbQ6FnMafyICMjEl6Mgfg_11 = subInt(((NI) 1), dir_2);
		if ((NU)((NI)(TM_PZbQ6FnMafyICMjEl6Mgfg_11)) > (NU)(1)) raiseIndexError();
		asgnRefNoCycle((void**) (&(*inner).isLeafU.child[((NI)(TM_PZbQ6FnMafyICMjEl6Mgfg_11))- 0]), result);
		nimln_(100, "critbits.nim");
		wherep = &(*c).root;
		{
			nimln_(101, "critbits.nim");
			while (1) {
				tyObject_NodeObj_s6B00BU456H1of4V8TzqOw* p;
				NIM_CHAR ch_3;
				NI dir_3;
				NI TM_PZbQ6FnMafyICMjEl6Mgfg_12;
				nimln_(102, "critbits.nim");
				p = (*wherep);
				nimln_(103, "critbits.nim");
				{
					if (!(*p).isLeaf) goto LA35_;
					goto LA31;
				}
				LA35_: ;
				nimln_(104, "critbits.nim");
				{
					if (!(newByte < (*p).byte)) goto LA39_;
					goto LA31;
				}
				LA39_: ;
				nimln_(105, "critbits.nim");
				{
					NIM_BOOL T43_;
					T43_ = (NIM_BOOL)0;
					T43_ = ((*p).byte == newByte);
					if (!(T43_)) goto LA44_;
					T43_ = (newOtherBits < ((NU8)((*p).otherbits)));
					LA44_: ;
					if (!T43_) goto LA45_;
					goto LA31;
				}
				LA45_: ;
				nimln_(106, "critbits.nim");
				{
					if (!((*p).byte < (key ? key->Sup.len : 0))) goto LA49_;
					if ((NU)((*p).byte) > (NU)(key->Sup.len)) raiseIndexError();
					ch_3 = key->data[(*p).byte];
				}
				goto LA47_;
				LA49_: ;
				{
					ch_3 = 0;
				}
				LA47_: ;
				nimln_(107, "critbits.nim");
				TM_PZbQ6FnMafyICMjEl6Mgfg_12 = addInt(((NI) 1), (NI)(((NU8)(ch_3)) | ((NU8)((*p).otherbits))));
				dir_3 = (NI)((NU64)((NI)(TM_PZbQ6FnMafyICMjEl6Mgfg_12)) >> (NU64)(((NI) 8)));
				nimln_(108, "critbits.nim");
				if (!(((1 &(1U<<((NU)((*p).isLeaf)&7U)))!=0))) raiseFieldError(((NimStringDesc*) &TM_PZbQ6FnMafyICMjEl6Mgfg_6));
				if ((NU)(dir_3) > (NU)(1)) raiseIndexError();
				wherep = &(*p).isLeafU.child[(dir_3)- 0];
			}
		} LA31: ;
		if (!(((1 &(1U<<((NU)((*inner).isLeaf)&7U)))!=0))) raiseFieldError(((NimStringDesc*) &TM_PZbQ6FnMafyICMjEl6Mgfg_6));
		if ((NU)(dir_2) > (NU)(1)) raiseIndexError();
		nimln_(109, "critbits.nim");
		asgnRefNoCycle((void**) (&(*inner).isLeafU.child[(dir_2)- 0]), (*wherep));
		nimln_(110, "critbits.nim");
		unsureAsgnRef((void**) (&(*wherep)), inner);
	}
	LA1_: ;
	nimln_(111, "critbits.nim");
	TM_PZbQ6FnMafyICMjEl6Mgfg_13 = addInt((*c).count, ((NI) 1));
	(*c).count = (NI)(TM_PZbQ6FnMafyICMjEl6Mgfg_13);
	}BeforeRet_: ;
	popFrame();
	return result;
}

N_LIB_PRIVATE N_NIMCALL(NIM_BOOL, containsOrIncl_6jTqr539bj9a9bXz9cQHn5OV9cg)(tyObject_CritBitTree_kyjBlOvrqb2saoDaZxR9cWA* c, NimStringDesc* key) {
	NIM_BOOL result;
	NI oldCount;
	tyObject_NodeObj_s6B00BU456H1of4V8TzqOw* n;
	nimfr_("containsOrIncl", "critbits.nim");
	result = (NIM_BOOL)0;
	nimln_(161, "critbits.nim");
	oldCount = (*c).count;
	nimln_(162, "critbits.nim");
	n = rawInsert_TO4O1pgmb8x1EXOER8mT5g(c, key);
	nimln_(163, "critbits.nim");
	result = ((*c).count == oldCount);
	popFrame();
	return result;
}
static N_NIMCALL(void, Marker_tyRef_2iDqjPqOFZmNCE6zfQbG4g)(void* p, NI op) {
	tyObject_NodeObj_xBU1K9bOAI19c7jtJRn2DFJw* a;
	NI T1_;
	a = (tyObject_NodeObj_xBU1K9bOAI19c7jtJRn2DFJw*)p;
	switch ((*a).isLeaf) {
	case NIM_FALSE:
	T1_ = (NI)0;
	for (T1_ = 0; T1_ < 2; T1_++) {
	nimGCvisit((void*)(*a).isLeafU.child[T1_], op);
	}
	break;
	case NIM_TRUE:
	nimGCvisit((void*)(*a).isLeafU.S2.key, op);
	break;
	} 
}

N_LIB_PRIVATE N_NIMCALL(tyObject_NodeObj_xBU1K9bOAI19c7jtJRn2DFJw*, rawInsert_It5l6XNiy8yPa2z0rsJ69cw)(tyObject_CritBitTree_W9co9c9b9bieBHo7glffSqTaOw* c, NimStringDesc* key) {
	tyObject_NodeObj_xBU1K9bOAI19c7jtJRn2DFJw* result;
	NI TM_PZbQ6FnMafyICMjEl6Mgfg_23;
	nimfr_("rawInsert", "critbits.nim");
{	result = (tyObject_NodeObj_xBU1K9bOAI19c7jtJRn2DFJw*)0;
	nimln_(61, "critbits.nim");
	{
		NIM_BOOL T5_;
		NimStringDesc* T6_;
		if (!((*c).root == NIM_NIL)) goto LA3_;
		nimln_(62, "critbits.nim");
		unsureAsgnRef((void**) (&(*c).root), (tyObject_NodeObj_xBU1K9bOAI19c7jtJRn2DFJw*) newObj((&NTI_2iDqjPqOFZmNCE6zfQbG4g_), sizeof(tyObject_NodeObj_xBU1K9bOAI19c7jtJRn2DFJw)));
		nimln_(63, "critbits.nim");
		T5_ = (NIM_BOOL)0;
		T5_ = NIM_TRUE;
		FieldDiscriminantCheck((NI)(NU)((*(*c).root).isLeaf), (NI)(NU)(T5_), NimDT__xBU1K9bOAI19c7jtJRn2DFJw_isLeaf, 3);
		(*(*c).root).isLeaf = T5_;
		if (!(((2 &(1U<<((NU)((*(*c).root).isLeaf)&7U)))!=0))) raiseFieldError(((NimStringDesc*) &TM_PZbQ6FnMafyICMjEl6Mgfg_4));
		nimln_(64, "critbits.nim");
		T6_ = (NimStringDesc*)0;
		T6_ = (*(*c).root).isLeafU.S2.key; (*(*c).root).isLeafU.S2.key = copyStringRC1(key);
		if (T6_) nimGCunrefNoCycle(T6_);
		nimln_(65, "critbits.nim");
		result = (*c).root;
	}
	goto LA1_;
	LA3_: ;
	{
		tyObject_NodeObj_xBU1K9bOAI19c7jtJRn2DFJw* it;
		NI newOtherBits;
		NI newByte;
		NIM_CHAR ch_2;
		NI dir_2;
		NI TM_PZbQ6FnMafyICMjEl6Mgfg_20;
		tyObject_NodeObj_xBU1K9bOAI19c7jtJRn2DFJw* inner;
		NIM_BOOL T29_;
		NimStringDesc* T30_;
		NI TM_PZbQ6FnMafyICMjEl6Mgfg_21;
		tyObject_NodeObj_xBU1K9bOAI19c7jtJRn2DFJw** wherep;
		nimln_(67, "critbits.nim");
		it = (*c).root;
		{
			nimln_(68, "critbits.nim");
			while (1) {
				NIM_CHAR ch;
				NI dir;
				NI TM_PZbQ6FnMafyICMjEl6Mgfg_16;
				if (!!((*it).isLeaf)) goto LA9;
				nimln_(69, "critbits.nim");
				{
					if (!((*it).byte < (key ? key->Sup.len : 0))) goto LA12_;
					if ((NU)((*it).byte) > (NU)(key->Sup.len)) raiseIndexError();
					ch = key->data[(*it).byte];
				}
				goto LA10_;
				LA12_: ;
				{
					ch = 0;
				}
				LA10_: ;
				nimln_(70, "critbits.nim");
				TM_PZbQ6FnMafyICMjEl6Mgfg_16 = addInt(((NI) 1), (NI)(((NU8)(ch)) | ((NU8)((*it).otherbits))));
				dir = (NI)((NU64)((NI)(TM_PZbQ6FnMafyICMjEl6Mgfg_16)) >> (NU64)(((NI) 8)));
				nimln_(71, "critbits.nim");
				if (!(((1 &(1U<<((NU)((*it).isLeaf)&7U)))!=0))) raiseFieldError(((NimStringDesc*) &TM_PZbQ6FnMafyICMjEl6Mgfg_6));
				if ((NU)(dir) > (NU)(1)) raiseIndexError();
				it = (*it).isLeafU.child[(dir)- 0];
			} LA9: ;
		}
		nimln_(73, "critbits.nim");
		newOtherBits = ((NI) 0);
		nimln_(74, "critbits.nim");
		newByte = ((NI) 0);
		{
			{
				nimln_(76, "critbits.nim");
				while (1) {
					NI TM_PZbQ6FnMafyICMjEl6Mgfg_17;
					if (!(newByte < (key ? key->Sup.len : 0))) goto LA17;
					nimln_(77, "critbits.nim");
					{
						nimln_(398, "system.nim");
						nimln_(77, "critbits.nim");
						if (!(((2 &(1U<<((NU)((*it).isLeaf)&7U)))!=0))) raiseFieldError(((NimStringDesc*) &TM_PZbQ6FnMafyICMjEl6Mgfg_4));
						if ((NU)(newByte) > (NU)((*it).isLeafU.S2.key->Sup.len)) raiseIndexError();
						if ((NU)(newByte) > (NU)(key->Sup.len)) raiseIndexError();
						if (!!(((NU8)((*it).isLeafU.S2.key->data[newByte]) == (NU8)(key->data[newByte])))) goto LA20_;
						nimln_(78, "critbits.nim");
						if (!(((2 &(1U<<((NU)((*it).isLeaf)&7U)))!=0))) raiseFieldError(((NimStringDesc*) &TM_PZbQ6FnMafyICMjEl6Mgfg_4));
						if ((NU)(newByte) > (NU)((*it).isLeafU.S2.key->Sup.len)) raiseIndexError();
						if ((NU)(newByte) > (NU)(key->Sup.len)) raiseIndexError();
						newOtherBits = (NI)(((NU8)((*it).isLeafU.S2.key->data[newByte])) ^ ((NU8)(key->data[newByte])));
						nimln_(79, "critbits.nim");
						goto LA15;
					}
					LA20_: ;
					nimln_(80, "critbits.nim");
					TM_PZbQ6FnMafyICMjEl6Mgfg_17 = addInt(newByte, ((NI) 1));
					newByte = (NI)(TM_PZbQ6FnMafyICMjEl6Mgfg_17);
				} LA17: ;
			}
			nimln_(81, "critbits.nim");
			{
				nimln_(398, "system.nim");
				nimln_(81, "critbits.nim");
				if (!(((2 &(1U<<((NU)((*it).isLeaf)&7U)))!=0))) raiseFieldError(((NimStringDesc*) &TM_PZbQ6FnMafyICMjEl6Mgfg_4));
				if ((NU)(newByte) > (NU)((*it).isLeafU.S2.key->Sup.len)) raiseIndexError();
				if (!!(((NU8)((*it).isLeafU.S2.key->data[newByte]) == (NU8)(0)))) goto LA24_;
				nimln_(82, "critbits.nim");
				if (!(((2 &(1U<<((NU)((*it).isLeaf)&7U)))!=0))) raiseFieldError(((NimStringDesc*) &TM_PZbQ6FnMafyICMjEl6Mgfg_4));
				if ((NU)(newByte) > (NU)((*it).isLeafU.S2.key->Sup.len)) raiseIndexError();
				newOtherBits = ((NU8)((*it).isLeafU.S2.key->data[newByte]));
			}
			goto LA22_;
			LA24_: ;
			{
				nimln_(84, "critbits.nim");
				result = it;
				goto BeforeRet_;
			}
			LA22_: ;
		} LA15: ;
		{
			nimln_(85, "critbits.nim");
			while (1) {
				NI TM_PZbQ6FnMafyICMjEl6Mgfg_18;
				NI TM_PZbQ6FnMafyICMjEl6Mgfg_19;
				nimln_(398, "system.nim");
				nimln_(85, "critbits.nim");
				TM_PZbQ6FnMafyICMjEl6Mgfg_18 = subInt(newOtherBits, ((NI) 1));
				if (!!(((NI)(newOtherBits & (NI)(TM_PZbQ6FnMafyICMjEl6Mgfg_18)) == ((NI) 0)))) goto LA28;
				nimln_(86, "critbits.nim");
				TM_PZbQ6FnMafyICMjEl6Mgfg_19 = subInt(newOtherBits, ((NI) 1));
				newOtherBits = (NI)(newOtherBits & (NI)(TM_PZbQ6FnMafyICMjEl6Mgfg_19));
			} LA28: ;
		}
		nimln_(87, "critbits.nim");
		newOtherBits = (NI)(newOtherBits ^ ((NI) 255));
		nimln_(88, "critbits.nim");
		if (!(((2 &(1U<<((NU)((*it).isLeaf)&7U)))!=0))) raiseFieldError(((NimStringDesc*) &TM_PZbQ6FnMafyICMjEl6Mgfg_4));
		if ((NU)(newByte) > (NU)((*it).isLeafU.S2.key->Sup.len)) raiseIndexError();
		ch_2 = (*it).isLeafU.S2.key->data[newByte];
		nimln_(89, "critbits.nim");
		TM_PZbQ6FnMafyICMjEl6Mgfg_20 = addInt(((NI) 1), (NI)(((NU8)(ch_2)) | newOtherBits));
		dir_2 = (NI)((NU64)((NI)(TM_PZbQ6FnMafyICMjEl6Mgfg_20)) >> (NU64)(((NI) 8)));
		inner = (tyObject_NodeObj_xBU1K9bOAI19c7jtJRn2DFJw*)0;
		nimln_(92, "critbits.nim");
		inner = (tyObject_NodeObj_xBU1K9bOAI19c7jtJRn2DFJw*) newObj((&NTI_2iDqjPqOFZmNCE6zfQbG4g_), sizeof(tyObject_NodeObj_xBU1K9bOAI19c7jtJRn2DFJw));
		nimln_(93, "critbits.nim");
		result = (tyObject_NodeObj_xBU1K9bOAI19c7jtJRn2DFJw*) newObj((&NTI_2iDqjPqOFZmNCE6zfQbG4g_), sizeof(tyObject_NodeObj_xBU1K9bOAI19c7jtJRn2DFJw));
		nimln_(94, "critbits.nim");
		T29_ = (NIM_BOOL)0;
		T29_ = NIM_TRUE;
		FieldDiscriminantCheck((NI)(NU)((*result).isLeaf), (NI)(NU)(T29_), NimDT__xBU1K9bOAI19c7jtJRn2DFJw_isLeaf, 3);
		(*result).isLeaf = T29_;
		if (!(((2 &(1U<<((NU)((*result).isLeaf)&7U)))!=0))) raiseFieldError(((NimStringDesc*) &TM_PZbQ6FnMafyICMjEl6Mgfg_4));
		nimln_(95, "critbits.nim");
		T30_ = (NimStringDesc*)0;
		T30_ = (*result).isLeafU.S2.key; (*result).isLeafU.S2.key = copyStringRC1(key);
		if (T30_) nimGCunrefNoCycle(T30_);
		nimln_(96, "critbits.nim");
		(*inner).otherbits = ((NIM_CHAR) (((NI)chckRange(newOtherBits, ((NI) 0), ((NI) 255)))));
		nimln_(97, "critbits.nim");
		(*inner).byte = newByte;
		if (!(((1 &(1U<<((NU)((*inner).isLeaf)&7U)))!=0))) raiseFieldError(((NimStringDesc*) &TM_PZbQ6FnMafyICMjEl6Mgfg_6));
		nimln_(98, "critbits.nim");
		TM_PZbQ6FnMafyICMjEl6Mgfg_21 = subInt(((NI) 1), dir_2);
		if ((NU)((NI)(TM_PZbQ6FnMafyICMjEl6Mgfg_21)) > (NU)(1)) raiseIndexError();
		asgnRefNoCycle((void**) (&(*inner).isLeafU.child[((NI)(TM_PZbQ6FnMafyICMjEl6Mgfg_21))- 0]), result);
		nimln_(100, "critbits.nim");
		wherep = &(*c).root;
		{
			nimln_(101, "critbits.nim");
			while (1) {
				tyObject_NodeObj_xBU1K9bOAI19c7jtJRn2DFJw* p;
				NIM_CHAR ch_3;
				NI dir_3;
				NI TM_PZbQ6FnMafyICMjEl6Mgfg_22;
				nimln_(102, "critbits.nim");
				p = (*wherep);
				nimln_(103, "critbits.nim");
				{
					if (!(*p).isLeaf) goto LA35_;
					goto LA31;
				}
				LA35_: ;
				nimln_(104, "critbits.nim");
				{
					if (!(newByte < (*p).byte)) goto LA39_;
					goto LA31;
				}
				LA39_: ;
				nimln_(105, "critbits.nim");
				{
					NIM_BOOL T43_;
					T43_ = (NIM_BOOL)0;
					T43_ = ((*p).byte == newByte);
					if (!(T43_)) goto LA44_;
					T43_ = (newOtherBits < ((NU8)((*p).otherbits)));
					LA44_: ;
					if (!T43_) goto LA45_;
					goto LA31;
				}
				LA45_: ;
				nimln_(106, "critbits.nim");
				{
					if (!((*p).byte < (key ? key->Sup.len : 0))) goto LA49_;
					if ((NU)((*p).byte) > (NU)(key->Sup.len)) raiseIndexError();
					ch_3 = key->data[(*p).byte];
				}
				goto LA47_;
				LA49_: ;
				{
					ch_3 = 0;
				}
				LA47_: ;
				nimln_(107, "critbits.nim");
				TM_PZbQ6FnMafyICMjEl6Mgfg_22 = addInt(((NI) 1), (NI)(((NU8)(ch_3)) | ((NU8)((*p).otherbits))));
				dir_3 = (NI)((NU64)((NI)(TM_PZbQ6FnMafyICMjEl6Mgfg_22)) >> (NU64)(((NI) 8)));
				nimln_(108, "critbits.nim");
				if (!(((1 &(1U<<((NU)((*p).isLeaf)&7U)))!=0))) raiseFieldError(((NimStringDesc*) &TM_PZbQ6FnMafyICMjEl6Mgfg_6));
				if ((NU)(dir_3) > (NU)(1)) raiseIndexError();
				wherep = &(*p).isLeafU.child[(dir_3)- 0];
			}
		} LA31: ;
		if (!(((1 &(1U<<((NU)((*inner).isLeaf)&7U)))!=0))) raiseFieldError(((NimStringDesc*) &TM_PZbQ6FnMafyICMjEl6Mgfg_6));
		if ((NU)(dir_2) > (NU)(1)) raiseIndexError();
		nimln_(109, "critbits.nim");
		asgnRefNoCycle((void**) (&(*inner).isLeafU.child[(dir_2)- 0]), (*wherep));
		nimln_(110, "critbits.nim");
		unsureAsgnRef((void**) (&(*wherep)), inner);
	}
	LA1_: ;
	nimln_(111, "critbits.nim");
	TM_PZbQ6FnMafyICMjEl6Mgfg_23 = addInt((*c).count, ((NI) 1));
	(*c).count = (NI)(TM_PZbQ6FnMafyICMjEl6Mgfg_23);
	}BeforeRet_: ;
	popFrame();
	return result;
}

N_LIB_PRIVATE N_NIMCALL(void, inc_8YmcVDWhRuEPpJvI5tDYBQ)(tyObject_CritBitTree_W9co9c9b9bieBHo7glffSqTaOw* c, NimStringDesc* key) {
	NI oldCount;
	tyObject_NodeObj_xBU1K9bOAI19c7jtJRn2DFJw* n;
	nimfr_("inc", "critbits.nim");
	nimln_(167, "critbits.nim");
	oldCount = (*c).count;
	nimln_(168, "critbits.nim");
	n = rawInsert_It5l6XNiy8yPa2z0rsJ69cw(c, key);
	nimln_(169, "critbits.nim");
	{
		NI TM_PZbQ6FnMafyICMjEl6Mgfg_25;
		if (!((*c).count == oldCount)) goto LA3_;
		nimln_(171, "critbits.nim");
		if (!(((2 &(1U<<((NU)((*n).isLeaf)&7U)))!=0))) raiseFieldError(((NimStringDesc*) &TM_PZbQ6FnMafyICMjEl6Mgfg_24));
		TM_PZbQ6FnMafyICMjEl6Mgfg_25 = addInt((*n).isLeafU.S2.val, ((NI) 1));
		(*n).isLeafU.S2.val = (NI)(TM_PZbQ6FnMafyICMjEl6Mgfg_25);
	}
	LA3_: ;
	popFrame();
}

N_LIB_PRIVATE N_NIMCALL(void, incl_imDOJIOfVlx8JBSwN1tyQg)(tyObject_CritBitTree_kyjBlOvrqb2saoDaZxR9cWA* c, NimStringDesc* key) {
	tyObject_NodeObj_s6B00BU456H1of4V8TzqOw* T1_;
	nimfr_("incl", "critbits.nim");
	nimln_(175, "critbits.nim");
	T1_ = (tyObject_NodeObj_s6B00BU456H1of4V8TzqOw*)0;
	T1_ = rawInsert_TO4O1pgmb8x1EXOER8mT5g(c, key);
	T1_;
	popFrame();
}

static N_INLINE(NIM_BOOL, equalMem_fmeFeLBvgmAHG9bC8ETS9bYQsystem)(void* a, void* b, NI size) {
	NIM_BOOL result;
	int T1_;
	result = (NIM_BOOL)0;
	T1_ = (int)0;
	T1_ = memcmp(a, b, ((size_t) (size)));
	result = (T1_ == ((NI32) 0));
	return result;
}

static N_INLINE(NIM_BOOL, eqStrings)(NimStringDesc* a, NimStringDesc* b) {
	NIM_BOOL result;
	NIM_BOOL T11_;
{	result = (NIM_BOOL)0;
	{
		if (!(a == b)) goto LA3_;
		result = NIM_TRUE;
		goto BeforeRet_;
	}
	LA3_: ;
	{
		NIM_BOOL T7_;
		T7_ = (NIM_BOOL)0;
		T7_ = (a == NIM_NIL);
		if (T7_) goto LA8_;
		T7_ = (b == NIM_NIL);
		LA8_: ;
		if (!T7_) goto LA9_;
		result = NIM_FALSE;
		goto BeforeRet_;
	}
	LA9_: ;
	T11_ = (NIM_BOOL)0;
	T11_ = ((*a).Sup.len == (*b).Sup.len);
	if (!(T11_)) goto LA12_;
	T11_ = equalMem_fmeFeLBvgmAHG9bC8ETS9bYQsystem(((void*) ((*a).data)), ((void*) ((*b).data)), ((NI) ((*a).Sup.len)));
	LA12_: ;
	result = T11_;
	goto BeforeRet_;
	}BeforeRet_: ;
	return result;
}

N_LIB_PRIVATE N_NIMCALL(tyObject_NodeObj_xBU1K9bOAI19c7jtJRn2DFJw*, rawGet_LWcLAMkq9cqhQSeXJ1tgZvw)(tyObject_CritBitTree_W9co9c9b9bieBHo7glffSqTaOw c, NimStringDesc* key) {
	tyObject_NodeObj_xBU1K9bOAI19c7jtJRn2DFJw* result;
	tyObject_NodeObj_xBU1K9bOAI19c7jtJRn2DFJw* it;
	nimfr_("rawGet", "critbits.nim");
{	result = (tyObject_NodeObj_xBU1K9bOAI19c7jtJRn2DFJw*)0;
	nimln_(43, "critbits.nim");
	it = c.root;
	{
		nimln_(44, "critbits.nim");
		while (1) {
			nimln_(398, "system.nim");
			nimln_(44, "critbits.nim");
			if (!!((it == NIM_NIL))) goto LA2;
			nimln_(45, "critbits.nim");
			{
				NIM_CHAR ch;
				NI dir;
				NI TM_PZbQ6FnMafyICMjEl6Mgfg_27;
				if (!!((*it).isLeaf)) goto LA5_;
				nimln_(46, "critbits.nim");
				{
					if (!((*it).byte < (key ? key->Sup.len : 0))) goto LA9_;
					if ((NU)((*it).byte) > (NU)(key->Sup.len)) raiseIndexError();
					ch = key->data[(*it).byte];
				}
				goto LA7_;
				LA9_: ;
				{
					ch = 0;
				}
				LA7_: ;
				nimln_(47, "critbits.nim");
				TM_PZbQ6FnMafyICMjEl6Mgfg_27 = addInt(((NI) 1), (NI)(((NU8)(ch)) | ((NU8)((*it).otherbits))));
				dir = (NI)((NU64)((NI)(TM_PZbQ6FnMafyICMjEl6Mgfg_27)) >> (NU64)(((NI) 8)));
				nimln_(48, "critbits.nim");
				if (!(((1 &(1U<<((NU)((*it).isLeaf)&7U)))!=0))) raiseFieldError(((NimStringDesc*) &TM_PZbQ6FnMafyICMjEl6Mgfg_6));
				if ((NU)(dir) > (NU)(1)) raiseIndexError();
				it = (*it).isLeafU.child[(dir)- 0];
			}
			goto LA3_;
			LA5_: ;
			{
				nimln_(50, "critbits.nim");
				{
					if (!(((2 &(1U<<((NU)((*it).isLeaf)&7U)))!=0))) raiseFieldError(((NimStringDesc*) &TM_PZbQ6FnMafyICMjEl6Mgfg_4));
					if (!eqStrings((*it).isLeafU.S2.key, key)) goto LA15_;
					result = it;
				}
				goto LA13_;
				LA15_: ;
				{
					result = NIM_NIL;
				}
				LA13_: ;
				goto BeforeRet_;
			}
			LA3_: ;
		} LA2: ;
	}
	}BeforeRet_: ;
	popFrame();
	return result;
}

N_LIB_PRIVATE N_NIMCALL(void, X5BX5Deq__9a7bDNDA6jE6k1HlJc0Fppw)(tyObject_CritBitTree_W9co9c9b9bieBHo7glffSqTaOw* c, NimStringDesc* key, NI val) {
	tyObject_NodeObj_xBU1K9bOAI19c7jtJRn2DFJw* n;
	nimfr_("[]=", "critbits.nim");
	nimln_(179, "critbits.nim");
	n = rawInsert_It5l6XNiy8yPa2z0rsJ69cw(c, key);
	if (!(((2 &(1U<<((NU)((*n).isLeaf)&7U)))!=0))) raiseFieldError(((NimStringDesc*) &TM_PZbQ6FnMafyICMjEl6Mgfg_24));
	nimln_(180, "critbits.nim");
	(*n).isLeafU.S2.val = val;
	popFrame();
}

N_LIB_PRIVATE N_NIMCALL(NI, len_tr1EAKWlDHjUSryZUXVzyg)(tyObject_CritBitTree_W9co9c9b9bieBHo7glffSqTaOw c) {
	NI result;
	nimfr_("len", "critbits.nim");
	result = (NI)0;
	nimln_(40, "critbits.nim");
	result = c.count;
	popFrame();
	return result;
}

static N_INLINE(void, copyMem_E1xtACub5WcDa3vbrIXbwgsystem)(void* dest, void* source, NI size) {
	void* T1_;
	T1_ = (void*)0;
	T1_ = memcpy(dest, source, ((size_t) (size)));
}

static N_INLINE(void, appendString)(NimStringDesc* dest, NimStringDesc* src) {
	copyMem_E1xtACub5WcDa3vbrIXbwgsystem(((void*) ((&(*dest).data[((*dest).Sup.len)- 0]))), ((void*) ((*src).data)), ((NI) ((NI)((*src).Sup.len + ((NI) 1)))));
	(*dest).Sup.len += (*src).Sup.len;
}

static N_INLINE(NI, resize_bzF9a0JivP3Z4njqaxuLc5wsystem)(NI old) {
	NI result;
	result = (NI)0;
	{
		if (!(old <= ((NI) 0))) goto LA3_;
		result = ((NI) 4);
	}
	goto LA1_;
	LA3_: ;
	{
		if (!(old < ((NI) 65536))) goto LA6_;
		result = (NI)(old * ((NI) 2));
	}
	goto LA1_;
	LA6_: ;
	{
		result = (NI)((NI)(old * ((NI) 3)) / ((NI) 2));
	}
	LA1_: ;
	return result;
}

static N_INLINE(void, zeroMem_t0o5XqKanO5QJfXMGEzp2Asystem)(void* p, NI size) {
	void* T1_;
	T1_ = (void*)0;
	T1_ = memset(p, ((int) 0), ((size_t) (size)));
}

static N_INLINE(TGenericSeq*, setLengthSeq)(TGenericSeq* seq, NI elemSize, NI newLen) {
	TGenericSeq* result;
	result = (TGenericSeq*)0;
	result = seq;
	{
		NI r;
		NI T5_;
		void* T6_;
		if (!((NI)((*result).reserved & ((NI) IL64(4611686018427387903))) < newLen)) goto LA3_;
		T5_ = (NI)0;
		T5_ = resize_bzF9a0JivP3Z4njqaxuLc5wsystem((NI)((*result).reserved & ((NI) IL64(4611686018427387903))));
		r = ((T5_ >= newLen) ? T5_ : newLen);
		T6_ = (void*)0;
		T6_ = growObj_AVYny8c0GTk28gxjmat1MA(((void*) (result)), (NI)((NI)(elemSize * r) + ((NI) 16)));
		result = ((TGenericSeq*) (T6_));
		(*result).reserved = r;
	}
	goto LA1_;
	LA3_: ;
	{
		if (!(newLen < (*result).len)) goto LA8_;
		{
			TNimType* T12_;
			T12_ = (TNimType*)0;
			T12_ = extGetCellType(((void*) (result)));
			if (!!((((*(*T12_).base).flags &(1U<<((NU)(((tyEnum_TNimTypeFlag_v8QUszD1sWlSIWZz7mC4bQ) 0))&7U)))!=0))) goto LA13_;
			{
				NI i;
				NI colontmp_;
				NI res;
				i = (NI)0;
				colontmp_ = (NI)0;
				colontmp_ = (NI)((*result).len - ((NI) 1));
				res = newLen;
				{
					while (1) {
						TNimType* T18_;
						if (!(res <= colontmp_)) goto LA17;
						i = res;
						T18_ = (TNimType*)0;
						T18_ = extGetCellType(((void*) (result)));
						forAllChildrenAux_YOI1Uo54H9aas13WthjhsfA(((void*) ((NI)((NU64)((NI)((NU64)(((NI) (ptrdiff_t) (result))) + (NU64)(((NI) 16)))) + (NU64)((NI)((NU64)(i) * (NU64)(elemSize)))))), (*T18_).base, ((tyEnum_WalkOp_Wfy7gT5VQ8B3aJBxqU8D9cQ) 2));
						res += ((NI) 1);
					} LA17: ;
				}
			}
		}
		LA13_: ;
		zeroMem_t0o5XqKanO5QJfXMGEzp2Asystem(((void*) ((NI)((NU64)((NI)((NU64)(((NI) (ptrdiff_t) (result))) + (NU64)(((NI) 16)))) + (NU64)((NI)((NU64)(newLen) * (NU64)(elemSize)))))), ((NI) ((NI)((NU64)((NI)((NU64)((*result).len) - (NU64)(newLen))) * (NU64)(elemSize)))));
	}
	goto LA1_;
	LA8_: ;
	LA1_: ;
	(*result).len = newLen;
	return result;
}

static N_INLINE(tyObject_NodeObj_xBU1K9bOAI19c7jtJRn2DFJw*, pop_Yw8TX1ShKvAyRG7AcrRflAword_count_test)(tySequence_riGsizgBbQK4AtYOoYFFuw** s) {
	tyObject_NodeObj_xBU1K9bOAI19c7jtJRn2DFJw* result;
	NI L;
	NI T1_;
	NI TM_PZbQ6FnMafyICMjEl6Mgfg_31;
	nimfr_("pop", "system.nim");
	result = (tyObject_NodeObj_xBU1K9bOAI19c7jtJRn2DFJw*)0;
	nimln_(2431, "system.nim");
	T1_ = ((*s) ? (*s)->Sup.len : 0);
	TM_PZbQ6FnMafyICMjEl6Mgfg_31 = subInt(T1_, ((NI) 1));
	L = (NI)(TM_PZbQ6FnMafyICMjEl6Mgfg_31);
	nimln_(2432, "system.nim");
	if ((NU)(L) >= (NU)((*s)->Sup.len)) raiseIndexError();
	result = (*s)->data[L];
	nimln_(2433, "system.nim");
	(*s) = (tySequence_riGsizgBbQK4AtYOoYFFuw*) setLengthSeq(&((*s))->Sup, sizeof(tyObject_NodeObj_xBU1K9bOAI19c7jtJRn2DFJw*), ((NI)chckRange(L, ((NI) 0), ((NI) IL64(9223372036854775807)))));
	popFrame();
	return result;
}

N_LIB_PRIVATE N_NIMCALL(NimStringDesc*, dollar__iAFGR6c6NYkJIjy0y1bPXg)(tyObject_CritBitTree_W9co9c9b9bieBHo7glffSqTaOw c) {
	NimStringDesc* result;
	nimfr_("$", "critbits.nim");
	result = (NimStringDesc*)0;
	nimln_(311, "critbits.nim");
	{
		NI T3_;
		T3_ = (NI)0;
		T3_ = len_tr1EAKWlDHjUSryZUXVzyg(c);
		if (!(T3_ == ((NI) 0))) goto LA4_;
		nimln_(315, "critbits.nim");
		result = copyString(((NimStringDesc*) &TM_PZbQ6FnMafyICMjEl6Mgfg_28));
	}
	goto LA1_;
	LA4_: ;
	{
		NI TM_PZbQ6FnMafyICMjEl6Mgfg_29;
		nimln_(322, "critbits.nim");
		TM_PZbQ6FnMafyICMjEl6Mgfg_29 = mulInt(c.count, ((NI) 16));
		result = rawNewString(((NI)chckRange((NI)(TM_PZbQ6FnMafyICMjEl6Mgfg_29), ((NI) 0), ((NI) IL64(9223372036854775807)))));
		nimln_(323, "critbits.nim");
		result = resizeString(result, 1);
appendString(result, ((NimStringDesc*) &TM_PZbQ6FnMafyICMjEl6Mgfg_30));
		{
			NimStringDesc* key;
			NI val;
			key = (NimStringDesc*)0;
			val = (NI)0;
			{
				tyObject_NodeObj_xBU1K9bOAI19c7jtJRn2DFJw* x;
				tyObject_NodeObj_xBU1K9bOAI19c7jtJRn2DFJw* colontmp_;
				x = (tyObject_NodeObj_xBU1K9bOAI19c7jtJRn2DFJw*)0;
				colontmp_ = (tyObject_NodeObj_xBU1K9bOAI19c7jtJRn2DFJw*)0;
				nimln_(243, "critbits.nim");
				colontmp_ = c.root;
				nimln_(211, "critbits.nim");
				{
					tySequence_riGsizgBbQK4AtYOoYFFuw* stack;
					nimln_(398, "system.nim");
					nimln_(211, "critbits.nim");
					if (!!((colontmp_ == NIM_NIL))) goto LA11_;
					nimln_(214, "critbits.nim");
					stack = (tySequence_riGsizgBbQK4AtYOoYFFuw*) newSeq((&NTI_riGsizgBbQK4AtYOoYFFuw_), 1);
					asgnRefNoCycle((void**) (&stack->data[0]), colontmp_);
					{
						nimln_(215, "critbits.nim");
						while (1) {
							NI T15_;
							tyObject_NodeObj_xBU1K9bOAI19c7jtJRn2DFJw* it;
							T15_ = (stack ? stack->Sup.len : 0);
							if (!(((NI) 0) < T15_)) goto LA14;
							nimln_(216, "critbits.nim");
							it = pop_Yw8TX1ShKvAyRG7AcrRflAword_count_test((&stack));
							{
								nimln_(217, "critbits.nim");
								while (1) {
									NI T18_;
									if (!!((*it).isLeaf)) goto LA17;
									nimln_(218, "critbits.nim");
									if (!(((1 &(1U<<((NU)((*it).isLeaf)&7U)))!=0))) raiseFieldError(((NimStringDesc*) &TM_PZbQ6FnMafyICMjEl6Mgfg_6));
									stack = (tySequence_riGsizgBbQK4AtYOoYFFuw*) incrSeqV2(&(stack)->Sup, sizeof(tyObject_NodeObj_xBU1K9bOAI19c7jtJRn2DFJw*));
									T18_ = stack->Sup.len++;
									asgnRefNoCycle((void**) (&stack->data[T18_]), (*it).isLeafU.child[(((NI) 1))- 0]);
									nimln_(219, "critbits.nim");
									if (!(((1 &(1U<<((NU)((*it).isLeaf)&7U)))!=0))) raiseFieldError(((NimStringDesc*) &TM_PZbQ6FnMafyICMjEl6Mgfg_6));
									it = (*it).isLeafU.child[(((NI) 0))- 0];
									nimln_(220, "critbits.nim");
									{
										if (!!(!((it == NIM_NIL)))) goto LA21_;
										failedAssertImpl_aDmpBTs9cPuXp0Mp9cfiNeyA(((NimStringDesc*) &TM_PZbQ6FnMafyICMjEl6Mgfg_32));
									}
									LA21_: ;
								} LA17: ;
							}
							nimln_(221, "critbits.nim");
							x = it;
							nimln_(243, "critbits.nim");
							if (!(((2 &(1U<<((NU)((*x).isLeaf)&7U)))!=0))) raiseFieldError(((NimStringDesc*) &TM_PZbQ6FnMafyICMjEl6Mgfg_4));
							key = (*x).isLeafU.S2.key;
							if (!(((2 &(1U<<((NU)((*x).isLeaf)&7U)))!=0))) raiseFieldError(((NimStringDesc*) &TM_PZbQ6FnMafyICMjEl6Mgfg_24));
							val = (*x).isLeafU.S2.val;
							nimln_(325, "critbits.nim");
							{
								if (!(((NI) 1) < (result ? result->Sup.len : 0))) goto LA25_;
								result = resizeString(result, 2);
appendString(result, ((NimStringDesc*) &TM_PZbQ6FnMafyICMjEl6Mgfg_33));
							}
							LA25_: ;
							nimln_(326, "critbits.nim");
							result = resizeString(result, key->Sup.len + 0);
appendString(result, key);
							nimln_(328, "critbits.nim");
							result = resizeString(result, 2);
appendString(result, ((NimStringDesc*) &TM_PZbQ6FnMafyICMjEl6Mgfg_34));
							nimln_(329, "critbits.nim");
							addQuoted_nyaZAljVI03SH2d9cnD0WMw((&result), val);
						} LA14: ;
					}
				}
				LA11_: ;
			}
		}
		nimln_(330, "critbits.nim");
		result = resizeString(result, 1);
appendString(result, ((NimStringDesc*) &TM_PZbQ6FnMafyICMjEl6Mgfg_35));
	}
	LA1_: ;
	popFrame();
	return result;
}
NIM_EXTERNC N_NOINLINE(void, stdlib_critbitsInit000)(void) {
	nimfr_("critbits", "critbits.nim");
	popFrame();
}

NIM_EXTERNC N_NOINLINE(void, stdlib_critbitsDatInit000)(void) {
static TNimNode* TM_PZbQ6FnMafyICMjEl6Mgfg_2[3];
static TNimNode* TM_PZbQ6FnMafyICMjEl6Mgfg_3[2];
static TNimNode* TM_PZbQ6FnMafyICMjEl6Mgfg_14[3];
static TNimNode* TM_PZbQ6FnMafyICMjEl6Mgfg_15[2];
static TNimNode* TM_PZbQ6FnMafyICMjEl6Mgfg_26[2];
static TNimNode TM_PZbQ6FnMafyICMjEl6Mgfg_0[19];
NTI_s6B00BU456H1of4V8TzqOw_.size = sizeof(tyObject_NodeObj_s6B00BU456H1of4V8TzqOw);
NTI_s6B00BU456H1of4V8TzqOw_.kind = 18;
NTI_s6B00BU456H1of4V8TzqOw_.base = 0;
NTI_s6B00BU456H1of4V8TzqOw_.flags = 2;
TM_PZbQ6FnMafyICMjEl6Mgfg_2[0] = &TM_PZbQ6FnMafyICMjEl6Mgfg_0[1];
TM_PZbQ6FnMafyICMjEl6Mgfg_0[1].kind = 1;
TM_PZbQ6FnMafyICMjEl6Mgfg_0[1].offset = offsetof(tyObject_NodeObj_s6B00BU456H1of4V8TzqOw, byte);
TM_PZbQ6FnMafyICMjEl6Mgfg_0[1].typ = (&NTI_rR5Bzr1D5krxoo1NcNyeMA_);
TM_PZbQ6FnMafyICMjEl6Mgfg_0[1].name = "byte";
TM_PZbQ6FnMafyICMjEl6Mgfg_2[1] = &TM_PZbQ6FnMafyICMjEl6Mgfg_0[2];
TM_PZbQ6FnMafyICMjEl6Mgfg_0[2].kind = 1;
TM_PZbQ6FnMafyICMjEl6Mgfg_0[2].offset = offsetof(tyObject_NodeObj_s6B00BU456H1of4V8TzqOw, otherbits);
TM_PZbQ6FnMafyICMjEl6Mgfg_0[2].typ = (&NTI_nmiMWKVIe46vacnhAFrQvw_);
TM_PZbQ6FnMafyICMjEl6Mgfg_0[2].name = "otherbits";
TM_PZbQ6FnMafyICMjEl6Mgfg_2[2] = &TM_PZbQ6FnMafyICMjEl6Mgfg_0[3];
TM_PZbQ6FnMafyICMjEl6Mgfg_0[3].kind = 3;
TM_PZbQ6FnMafyICMjEl6Mgfg_0[3].offset = offsetof(tyObject_NodeObj_s6B00BU456H1of4V8TzqOw, isLeaf);
TM_PZbQ6FnMafyICMjEl6Mgfg_0[3].typ = (&NTI_VaVACK0bpYmqIQ0mKcHfQQ_);
TM_PZbQ6FnMafyICMjEl6Mgfg_0[3].name = "isLeaf";
TM_PZbQ6FnMafyICMjEl6Mgfg_0[3].sons = &NimDT__s6B00BU456H1of4V8TzqOw_isLeaf[0];
TM_PZbQ6FnMafyICMjEl6Mgfg_0[3].len = 2;
NTI_WPLPge0ABYq4JBOh9aIrU5A_.size = sizeof(tyArray_WPLPge0ABYq4JBOh9aIrU5A);
NTI_WPLPge0ABYq4JBOh9aIrU5A_.kind = 16;
NTI_WPLPge0ABYq4JBOh9aIrU5A_.base = (&NTI_1CYpj5Dhx2VK3Ym59czDTcQ_);
NTI_WPLPge0ABYq4JBOh9aIrU5A_.flags = 2;
TM_PZbQ6FnMafyICMjEl6Mgfg_0[4].kind = 1;
TM_PZbQ6FnMafyICMjEl6Mgfg_0[4].offset = offsetof(tyObject_NodeObj_s6B00BU456H1of4V8TzqOw, isLeafU.child);
TM_PZbQ6FnMafyICMjEl6Mgfg_0[4].typ = (&NTI_WPLPge0ABYq4JBOh9aIrU5A_);
TM_PZbQ6FnMafyICMjEl6Mgfg_0[4].name = "child";
NimDT__s6B00BU456H1of4V8TzqOw_isLeaf[0] = &TM_PZbQ6FnMafyICMjEl6Mgfg_0[4];
TM_PZbQ6FnMafyICMjEl6Mgfg_3[0] = &TM_PZbQ6FnMafyICMjEl6Mgfg_0[6];
TM_PZbQ6FnMafyICMjEl6Mgfg_0[6].kind = 1;
TM_PZbQ6FnMafyICMjEl6Mgfg_0[6].offset = offsetof(tyObject_NodeObj_s6B00BU456H1of4V8TzqOw, isLeafU.S2.key);
TM_PZbQ6FnMafyICMjEl6Mgfg_0[6].typ = (&NTI_77mFvmsOLKik79ci2hXkHEg_);
TM_PZbQ6FnMafyICMjEl6Mgfg_0[6].name = "key";
TM_PZbQ6FnMafyICMjEl6Mgfg_3[1] = &TM_PZbQ6FnMafyICMjEl6Mgfg_0[7];
TM_PZbQ6FnMafyICMjEl6Mgfg_0[7].len = 0; TM_PZbQ6FnMafyICMjEl6Mgfg_0[7].kind = 2;
TM_PZbQ6FnMafyICMjEl6Mgfg_0[5].len = 2; TM_PZbQ6FnMafyICMjEl6Mgfg_0[5].kind = 2; TM_PZbQ6FnMafyICMjEl6Mgfg_0[5].sons = &TM_PZbQ6FnMafyICMjEl6Mgfg_3[0];
NimDT__s6B00BU456H1of4V8TzqOw_isLeaf[1] = &TM_PZbQ6FnMafyICMjEl6Mgfg_0[5];
TM_PZbQ6FnMafyICMjEl6Mgfg_0[0].len = 3; TM_PZbQ6FnMafyICMjEl6Mgfg_0[0].kind = 2; TM_PZbQ6FnMafyICMjEl6Mgfg_0[0].sons = &TM_PZbQ6FnMafyICMjEl6Mgfg_2[0];
NTI_s6B00BU456H1of4V8TzqOw_.node = &TM_PZbQ6FnMafyICMjEl6Mgfg_0[0];
NTI_1CYpj5Dhx2VK3Ym59czDTcQ_.size = sizeof(tyObject_NodeObj_s6B00BU456H1of4V8TzqOw*);
NTI_1CYpj5Dhx2VK3Ym59czDTcQ_.kind = 22;
NTI_1CYpj5Dhx2VK3Ym59czDTcQ_.base = (&NTI_s6B00BU456H1of4V8TzqOw_);
NTI_1CYpj5Dhx2VK3Ym59czDTcQ_.flags = 2;
NTI_1CYpj5Dhx2VK3Ym59czDTcQ_.marker = Marker_tyRef_1CYpj5Dhx2VK3Ym59czDTcQ;
NTI_xBU1K9bOAI19c7jtJRn2DFJw_.size = sizeof(tyObject_NodeObj_xBU1K9bOAI19c7jtJRn2DFJw);
NTI_xBU1K9bOAI19c7jtJRn2DFJw_.kind = 18;
NTI_xBU1K9bOAI19c7jtJRn2DFJw_.base = 0;
NTI_xBU1K9bOAI19c7jtJRn2DFJw_.flags = 2;
TM_PZbQ6FnMafyICMjEl6Mgfg_14[0] = &TM_PZbQ6FnMafyICMjEl6Mgfg_0[9];
TM_PZbQ6FnMafyICMjEl6Mgfg_0[9].kind = 1;
TM_PZbQ6FnMafyICMjEl6Mgfg_0[9].offset = offsetof(tyObject_NodeObj_xBU1K9bOAI19c7jtJRn2DFJw, byte);
TM_PZbQ6FnMafyICMjEl6Mgfg_0[9].typ = (&NTI_rR5Bzr1D5krxoo1NcNyeMA_);
TM_PZbQ6FnMafyICMjEl6Mgfg_0[9].name = "byte";
TM_PZbQ6FnMafyICMjEl6Mgfg_14[1] = &TM_PZbQ6FnMafyICMjEl6Mgfg_0[10];
TM_PZbQ6FnMafyICMjEl6Mgfg_0[10].kind = 1;
TM_PZbQ6FnMafyICMjEl6Mgfg_0[10].offset = offsetof(tyObject_NodeObj_xBU1K9bOAI19c7jtJRn2DFJw, otherbits);
TM_PZbQ6FnMafyICMjEl6Mgfg_0[10].typ = (&NTI_nmiMWKVIe46vacnhAFrQvw_);
TM_PZbQ6FnMafyICMjEl6Mgfg_0[10].name = "otherbits";
TM_PZbQ6FnMafyICMjEl6Mgfg_14[2] = &TM_PZbQ6FnMafyICMjEl6Mgfg_0[11];
TM_PZbQ6FnMafyICMjEl6Mgfg_0[11].kind = 3;
TM_PZbQ6FnMafyICMjEl6Mgfg_0[11].offset = offsetof(tyObject_NodeObj_xBU1K9bOAI19c7jtJRn2DFJw, isLeaf);
TM_PZbQ6FnMafyICMjEl6Mgfg_0[11].typ = (&NTI_VaVACK0bpYmqIQ0mKcHfQQ_);
TM_PZbQ6FnMafyICMjEl6Mgfg_0[11].name = "isLeaf";
TM_PZbQ6FnMafyICMjEl6Mgfg_0[11].sons = &NimDT__xBU1K9bOAI19c7jtJRn2DFJw_isLeaf[0];
TM_PZbQ6FnMafyICMjEl6Mgfg_0[11].len = 2;
NTI_GRcX7rp8rN75VPNIuX8x7g_.size = sizeof(tyArray_GRcX7rp8rN75VPNIuX8x7g);
NTI_GRcX7rp8rN75VPNIuX8x7g_.kind = 16;
NTI_GRcX7rp8rN75VPNIuX8x7g_.base = (&NTI_2iDqjPqOFZmNCE6zfQbG4g_);
NTI_GRcX7rp8rN75VPNIuX8x7g_.flags = 2;
TM_PZbQ6FnMafyICMjEl6Mgfg_0[12].kind = 1;
TM_PZbQ6FnMafyICMjEl6Mgfg_0[12].offset = offsetof(tyObject_NodeObj_xBU1K9bOAI19c7jtJRn2DFJw, isLeafU.child);
TM_PZbQ6FnMafyICMjEl6Mgfg_0[12].typ = (&NTI_GRcX7rp8rN75VPNIuX8x7g_);
TM_PZbQ6FnMafyICMjEl6Mgfg_0[12].name = "child";
NimDT__xBU1K9bOAI19c7jtJRn2DFJw_isLeaf[0] = &TM_PZbQ6FnMafyICMjEl6Mgfg_0[12];
TM_PZbQ6FnMafyICMjEl6Mgfg_15[0] = &TM_PZbQ6FnMafyICMjEl6Mgfg_0[14];
TM_PZbQ6FnMafyICMjEl6Mgfg_0[14].kind = 1;
TM_PZbQ6FnMafyICMjEl6Mgfg_0[14].offset = offsetof(tyObject_NodeObj_xBU1K9bOAI19c7jtJRn2DFJw, isLeafU.S2.key);
TM_PZbQ6FnMafyICMjEl6Mgfg_0[14].typ = (&NTI_77mFvmsOLKik79ci2hXkHEg_);
TM_PZbQ6FnMafyICMjEl6Mgfg_0[14].name = "key";
TM_PZbQ6FnMafyICMjEl6Mgfg_15[1] = &TM_PZbQ6FnMafyICMjEl6Mgfg_0[15];
TM_PZbQ6FnMafyICMjEl6Mgfg_0[15].kind = 1;
TM_PZbQ6FnMafyICMjEl6Mgfg_0[15].offset = offsetof(tyObject_NodeObj_xBU1K9bOAI19c7jtJRn2DFJw, isLeafU.S2.val);
TM_PZbQ6FnMafyICMjEl6Mgfg_0[15].typ = (&NTI_rR5Bzr1D5krxoo1NcNyeMA_);
TM_PZbQ6FnMafyICMjEl6Mgfg_0[15].name = "val";
TM_PZbQ6FnMafyICMjEl6Mgfg_0[13].len = 2; TM_PZbQ6FnMafyICMjEl6Mgfg_0[13].kind = 2; TM_PZbQ6FnMafyICMjEl6Mgfg_0[13].sons = &TM_PZbQ6FnMafyICMjEl6Mgfg_15[0];
NimDT__xBU1K9bOAI19c7jtJRn2DFJw_isLeaf[1] = &TM_PZbQ6FnMafyICMjEl6Mgfg_0[13];
TM_PZbQ6FnMafyICMjEl6Mgfg_0[8].len = 3; TM_PZbQ6FnMafyICMjEl6Mgfg_0[8].kind = 2; TM_PZbQ6FnMafyICMjEl6Mgfg_0[8].sons = &TM_PZbQ6FnMafyICMjEl6Mgfg_14[0];
NTI_xBU1K9bOAI19c7jtJRn2DFJw_.node = &TM_PZbQ6FnMafyICMjEl6Mgfg_0[8];
NTI_2iDqjPqOFZmNCE6zfQbG4g_.size = sizeof(tyObject_NodeObj_xBU1K9bOAI19c7jtJRn2DFJw*);
NTI_2iDqjPqOFZmNCE6zfQbG4g_.kind = 22;
NTI_2iDqjPqOFZmNCE6zfQbG4g_.base = (&NTI_xBU1K9bOAI19c7jtJRn2DFJw_);
NTI_2iDqjPqOFZmNCE6zfQbG4g_.flags = 2;
NTI_2iDqjPqOFZmNCE6zfQbG4g_.marker = Marker_tyRef_2iDqjPqOFZmNCE6zfQbG4g;
NTI_W9co9c9b9bieBHo7glffSqTaOw_.size = sizeof(tyObject_CritBitTree_W9co9c9b9bieBHo7glffSqTaOw);
NTI_W9co9c9b9bieBHo7glffSqTaOw_.kind = 18;
NTI_W9co9c9b9bieBHo7glffSqTaOw_.base = 0;
NTI_W9co9c9b9bieBHo7glffSqTaOw_.flags = 2;
TM_PZbQ6FnMafyICMjEl6Mgfg_26[0] = &TM_PZbQ6FnMafyICMjEl6Mgfg_0[17];
TM_PZbQ6FnMafyICMjEl6Mgfg_0[17].kind = 1;
TM_PZbQ6FnMafyICMjEl6Mgfg_0[17].offset = offsetof(tyObject_CritBitTree_W9co9c9b9bieBHo7glffSqTaOw, root);
TM_PZbQ6FnMafyICMjEl6Mgfg_0[17].typ = (&NTI_2iDqjPqOFZmNCE6zfQbG4g_);
TM_PZbQ6FnMafyICMjEl6Mgfg_0[17].name = "root";
TM_PZbQ6FnMafyICMjEl6Mgfg_26[1] = &TM_PZbQ6FnMafyICMjEl6Mgfg_0[18];
TM_PZbQ6FnMafyICMjEl6Mgfg_0[18].kind = 1;
TM_PZbQ6FnMafyICMjEl6Mgfg_0[18].offset = offsetof(tyObject_CritBitTree_W9co9c9b9bieBHo7glffSqTaOw, count);
TM_PZbQ6FnMafyICMjEl6Mgfg_0[18].typ = (&NTI_rR5Bzr1D5krxoo1NcNyeMA_);
TM_PZbQ6FnMafyICMjEl6Mgfg_0[18].name = "count";
TM_PZbQ6FnMafyICMjEl6Mgfg_0[16].len = 2; TM_PZbQ6FnMafyICMjEl6Mgfg_0[16].kind = 2; TM_PZbQ6FnMafyICMjEl6Mgfg_0[16].sons = &TM_PZbQ6FnMafyICMjEl6Mgfg_26[0];
NTI_W9co9c9b9bieBHo7glffSqTaOw_.node = &TM_PZbQ6FnMafyICMjEl6Mgfg_0[16];
}

