/* Generated by Nim Compiler v0.18.0 */
/*   (c) 2018 Andreas Rumpf */
/* The generated code is subject to the original license. */
/* Compiled for: MacOSX, amd64, clang */
/* Command for C compiler:
   clang -c  -w  -I/Users/lowks/.asdf/installs/nim/v0.18.0/lib -o /Users/lowks/exercism/nim/hello-world/nimcache/helloworld_test.o /Users/lowks/exercism/nim/hello-world/nimcache/helloworld_test.c */
#define NIM_NEW_MANGLING_RULES
#define NIM_INTBITS 64

#include "nimbase.h"
#include <setjmp.h>
#include <string.h>
#include <stdlib.h>
#undef LANGUAGE_C
#undef MIPSEB
#undef MIPSEL
#undef PPC
#undef R3000
#undef R4000
#undef i386
#undef linux
#undef mips
#undef near
#undef powerpc
#undef unix
typedef struct NimStringDesc NimStringDesc;
typedef struct TGenericSeq TGenericSeq;
typedef struct tySequence_sM4lkSb7zS6F7OVMvW9cffQ tySequence_sM4lkSb7zS6F7OVMvW9cffQ;
typedef struct TNimType TNimType;
typedef struct TNimNode TNimNode;
typedef struct tyObject_Cell_1zcF9cV8XIAtbN8h5HRUB8g tyObject_Cell_1zcF9cV8XIAtbN8h5HRUB8g;
typedef struct tyObject_CellSeq_Axo1XVm9aaQueTOldv8le5w tyObject_CellSeq_Axo1XVm9aaQueTOldv8le5w;
typedef struct tyObject_GcHeap_1TRH1TZMaVZTnLNcIHuNFQ tyObject_GcHeap_1TRH1TZMaVZTnLNcIHuNFQ;
typedef struct tyObject_GcStack_7fytPA5bBsob6See21YMRA tyObject_GcStack_7fytPA5bBsob6See21YMRA;
typedef struct tyObject_MemRegion_x81NhDv59b8ercDZ9bi85jyg tyObject_MemRegion_x81NhDv59b8ercDZ9bi85jyg;
typedef struct tyObject_SmallChunk_tXn60W2f8h3jgAYdEmy5NQ tyObject_SmallChunk_tXn60W2f8h3jgAYdEmy5NQ;
typedef struct tyObject_BigChunk_Rv9c70Uhp2TytkX7eH78qEg tyObject_BigChunk_Rv9c70Uhp2TytkX7eH78qEg;
typedef struct tyObject_LLChunk_XsENErzHIZV9bhvyJx56wGw tyObject_LLChunk_XsENErzHIZV9bhvyJx56wGw;
typedef struct tyObject_IntSet_EZObFrE3NC9bIb3YMkY9crZA tyObject_IntSet_EZObFrE3NC9bIb3YMkY9crZA;
typedef struct tyObject_Trunk_W0r8S0Y3UGke6T9bIUWnnuw tyObject_Trunk_W0r8S0Y3UGke6T9bIUWnnuw;
typedef struct tyObject_AvlNode_IaqjtwKhxLEpvDS9bct9blEw tyObject_AvlNode_IaqjtwKhxLEpvDS9bct9blEw;
typedef struct tyObject_HeapLinks_PDV1HBZ8CQSQJC9aOBFNRSg tyObject_HeapLinks_PDV1HBZ8CQSQJC9aOBFNRSg;
typedef struct tyTuple_ujsjpB2O9cjj3uDHsXbnSzg tyTuple_ujsjpB2O9cjj3uDHsXbnSzg;
typedef struct tyObject_GcStat_0RwLoVBHZPfUAcLczmfQAg tyObject_GcStat_0RwLoVBHZPfUAcLczmfQAg;
typedef struct tyObject_CellSet_jG87P0AI9aZtss9ccTYBIISQ tyObject_CellSet_jG87P0AI9aZtss9ccTYBIISQ;
typedef struct tyObject_PageDesc_fublkgIY4LG3mT51LU2WHg tyObject_PageDesc_fublkgIY4LG3mT51LU2WHg;
typedef struct tyObject_OutputFormattercolonObjectType__dLGU9cWWYqlqOn8lpRVsx9cw tyObject_OutputFormattercolonObjectType__dLGU9cWWYqlqOn8lpRVsx9cw;
typedef struct tySequence_2gM6knqz8MaAY9c4MAR2ztg tySequence_2gM6knqz8MaAY9c4MAR2ztg;
typedef struct Exception Exception;
typedef struct RootObj RootObj;
typedef struct tySequence_uB9b75OUPRENsBAu4AnoePA tySequence_uB9b75OUPRENsBAu4AnoePA;
typedef struct TSafePoint TSafePoint;
typedef struct tyObject_TestResult_GEvSVSxdPWWgMGM48ywEYQ tyObject_TestResult_GEvSVSxdPWWgMGM48ywEYQ;
typedef struct tyObject_JUnitOutputFormattercolonObjectType__kvLOVRX6Za2S0C2QxHXy9cQ tyObject_JUnitOutputFormattercolonObjectType__kvLOVRX6Za2S0C2QxHXy9cQ;
typedef struct tyObject_ConsoleOutputFormattercolonObjectType__dU6QGtP3KgqXg9bZP3nhpWw tyObject_ConsoleOutputFormattercolonObjectType__dU6QGtP3KgqXg9bZP3nhpWw;
typedef struct tyObject_BaseChunk_Sdq7WpT6qAH858F5ZEdG3w tyObject_BaseChunk_Sdq7WpT6qAH858F5ZEdG3w;
typedef struct tyObject_FreeCell_u6M5LHprqzkn9axr04yg9bGQ tyObject_FreeCell_u6M5LHprqzkn9axr04yg9bGQ;
typedef struct tyObject_StackTraceEntry_oLyohQ7O2XOvGnflOss8EA tyObject_StackTraceEntry_oLyohQ7O2XOvGnflOss8EA;
typedef struct tyObject_StreamObj_RShkcoDOPnoCVhtpN1hDPQ tyObject_StreamObj_RShkcoDOPnoCVhtpN1hDPQ;
struct TGenericSeq {
NI len;
NI reserved;
};
struct NimStringDesc {
  TGenericSeq Sup;
NIM_CHAR data[SEQ_DECL_SIZE];
};
typedef NU8 tyEnum_TNimKind_jIBKr1ejBgsfM33Kxw4j7A;
typedef NU8 tySet_tyEnum_TNimTypeFlag_v8QUszD1sWlSIWZz7mC4bQ;
typedef N_NIMCALL_PTR(void, tyProc_ojoeKfW4VYIm36I9cpDTQIg) (void* p, NI op);
typedef N_NIMCALL_PTR(void*, tyProc_WSm2xU5ARYv9aAR4l0z9c9auQ) (void* p);
struct TNimType {
NI size;
tyEnum_TNimKind_jIBKr1ejBgsfM33Kxw4j7A kind;
tySet_tyEnum_TNimTypeFlag_v8QUszD1sWlSIWZz7mC4bQ flags;
TNimType* base;
TNimNode* node;
void* finalizer;
tyProc_ojoeKfW4VYIm36I9cpDTQIg marker;
tyProc_WSm2xU5ARYv9aAR4l0z9c9auQ deepcopy;
};
typedef NU8 tyEnum_TNimNodeKind_unfNsxrcATrufDZmpBq4HQ;
struct TNimNode {
tyEnum_TNimNodeKind_unfNsxrcATrufDZmpBq4HQ kind;
NI offset;
TNimType* typ;
NCSTRING name;
NI len;
TNimNode** sons;
};
struct tyObject_Cell_1zcF9cV8XIAtbN8h5HRUB8g {
NI refcount;
TNimType* typ;
};
struct tyObject_GcStack_7fytPA5bBsob6See21YMRA {
void* bottom;
};
struct tyObject_CellSeq_Axo1XVm9aaQueTOldv8le5w {
NI len;
NI cap;
tyObject_Cell_1zcF9cV8XIAtbN8h5HRUB8g** d;
};
typedef tyObject_SmallChunk_tXn60W2f8h3jgAYdEmy5NQ* tyArray_SiRwrEKZdLgxqz9a9aoVBglg[512];
typedef NU32 tyArray_BHbOSqU1t9b3Gt7K2c6fQig[24];
typedef tyObject_BigChunk_Rv9c70Uhp2TytkX7eH78qEg* tyArray_N1u1nqOgmuJN9cSZrnMHgOQ[32];
typedef tyArray_N1u1nqOgmuJN9cSZrnMHgOQ tyArray_B6durA4ZCi1xjJvRtyYxMg[24];
typedef tyObject_Trunk_W0r8S0Y3UGke6T9bIUWnnuw* tyArray_lh2A89ahMmYg9bCmpVaplLbA[256];
struct tyObject_IntSet_EZObFrE3NC9bIb3YMkY9crZA {
tyArray_lh2A89ahMmYg9bCmpVaplLbA data;
};
typedef tyObject_AvlNode_IaqjtwKhxLEpvDS9bct9blEw* tyArray_0aOLqZchNi8nWtMTi8ND8w[2];
struct tyObject_AvlNode_IaqjtwKhxLEpvDS9bct9blEw {
tyArray_0aOLqZchNi8nWtMTi8ND8w link;
NI key;
NI upperBound;
NI level;
};
struct tyTuple_ujsjpB2O9cjj3uDHsXbnSzg {
tyObject_BigChunk_Rv9c70Uhp2TytkX7eH78qEg* Field0;
NI Field1;
};
typedef tyTuple_ujsjpB2O9cjj3uDHsXbnSzg tyArray_LzOv2eCDGiceMKQstCLmhw[30];
struct tyObject_HeapLinks_PDV1HBZ8CQSQJC9aOBFNRSg {
NI len;
tyArray_LzOv2eCDGiceMKQstCLmhw chunks;
tyObject_HeapLinks_PDV1HBZ8CQSQJC9aOBFNRSg* next;
};
struct tyObject_MemRegion_x81NhDv59b8ercDZ9bi85jyg {
NI minLargeObj;
NI maxLargeObj;
tyArray_SiRwrEKZdLgxqz9a9aoVBglg freeSmallChunks;
NU32 flBitmap;
tyArray_BHbOSqU1t9b3Gt7K2c6fQig slBitmap;
tyArray_B6durA4ZCi1xjJvRtyYxMg matrix;
tyObject_LLChunk_XsENErzHIZV9bhvyJx56wGw* llmem;
NI currMem;
NI maxMem;
NI freeMem;
NI occ;
NI lastSize;
tyObject_IntSet_EZObFrE3NC9bIb3YMkY9crZA chunkStarts;
tyObject_AvlNode_IaqjtwKhxLEpvDS9bct9blEw* root;
tyObject_AvlNode_IaqjtwKhxLEpvDS9bct9blEw* deleted;
tyObject_AvlNode_IaqjtwKhxLEpvDS9bct9blEw* last;
tyObject_AvlNode_IaqjtwKhxLEpvDS9bct9blEw* freeAvlNodes;
NIM_BOOL locked;
NIM_BOOL blockChunkSizeIncrease;
NI nextChunkSize;
tyObject_AvlNode_IaqjtwKhxLEpvDS9bct9blEw bottomData;
tyObject_HeapLinks_PDV1HBZ8CQSQJC9aOBFNRSg heapLinks;
};
struct tyObject_GcStat_0RwLoVBHZPfUAcLczmfQAg {
NI stackScans;
NI cycleCollections;
NI maxThreshold;
NI maxStackSize;
NI maxStackCells;
NI cycleTableSize;
NI64 maxPause;
};
struct tyObject_CellSet_jG87P0AI9aZtss9ccTYBIISQ {
NI counter;
NI max;
tyObject_PageDesc_fublkgIY4LG3mT51LU2WHg* head;
tyObject_PageDesc_fublkgIY4LG3mT51LU2WHg** data;
};
struct tyObject_GcHeap_1TRH1TZMaVZTnLNcIHuNFQ {
tyObject_GcStack_7fytPA5bBsob6See21YMRA stack;
NI cycleThreshold;
tyObject_CellSeq_Axo1XVm9aaQueTOldv8le5w zct;
tyObject_CellSeq_Axo1XVm9aaQueTOldv8le5w decStack;
tyObject_CellSeq_Axo1XVm9aaQueTOldv8le5w tempStack;
NI recGcLock;
tyObject_MemRegion_x81NhDv59b8ercDZ9bi85jyg region;
tyObject_GcStat_0RwLoVBHZPfUAcLczmfQAg stat;
tyObject_CellSet_jG87P0AI9aZtss9ccTYBIISQ marked;
tyObject_CellSeq_Axo1XVm9aaQueTOldv8le5w additionalRoots;
NI gcThreadId;
};
typedef NU8 tyEnum_TestStatus_W9bTUg9c9a7UlIYkKYmd5uasQ;
typedef N_NIMCALL_PTR(void, tyProc_T4eqaYlFJYZUv9aG9b1TV0bQ) (void);
struct RootObj {
TNimType* m_type;
};
struct Exception {
  RootObj Sup;
Exception* parent;
NCSTRING name;
NimStringDesc* message;
tySequence_uB9b75OUPRENsBAu4AnoePA* trace;
Exception* up;
};
typedef struct {
N_NIMCALL_PTR(NIM_BOOL, ClP_0) (Exception* e, void* ClE_0);
void* ClE_0;
} tyProc_KeeAOYBd84Ofsw6Y7LizaQ;
struct TSafePoint {
TSafePoint* prev;
NI status;
jmp_buf context;
NIM_BOOL hasRaiseAction;
tyProc_KeeAOYBd84Ofsw6Y7LizaQ raiseAction;
};
struct tyObject_TestResult_GEvSVSxdPWWgMGM48ywEYQ {
NimStringDesc* suiteName;
NimStringDesc* testName;
tyEnum_TestStatus_W9bTUg9c9a7UlIYkKYmd5uasQ status;
};
struct tyObject_BaseChunk_Sdq7WpT6qAH858F5ZEdG3w {
NI prevSize;
NI size;
};
struct tyObject_SmallChunk_tXn60W2f8h3jgAYdEmy5NQ {
  tyObject_BaseChunk_Sdq7WpT6qAH858F5ZEdG3w Sup;
tyObject_SmallChunk_tXn60W2f8h3jgAYdEmy5NQ* next;
tyObject_SmallChunk_tXn60W2f8h3jgAYdEmy5NQ* prev;
tyObject_FreeCell_u6M5LHprqzkn9axr04yg9bGQ* freeList;
NI free;
NI acc;
NF data;
};
struct tyObject_BigChunk_Rv9c70Uhp2TytkX7eH78qEg {
  tyObject_BaseChunk_Sdq7WpT6qAH858F5ZEdG3w Sup;
tyObject_BigChunk_Rv9c70Uhp2TytkX7eH78qEg* next;
tyObject_BigChunk_Rv9c70Uhp2TytkX7eH78qEg* prev;
NF data;
};
struct tyObject_LLChunk_XsENErzHIZV9bhvyJx56wGw {
NI size;
NI acc;
tyObject_LLChunk_XsENErzHIZV9bhvyJx56wGw* next;
};
typedef NI tyArray_9a8QARi5WsUggNU9bom7kzTQ[8];
struct tyObject_Trunk_W0r8S0Y3UGke6T9bIUWnnuw {
tyObject_Trunk_W0r8S0Y3UGke6T9bIUWnnuw* next;
NI key;
tyArray_9a8QARi5WsUggNU9bom7kzTQ bits;
};
struct tyObject_PageDesc_fublkgIY4LG3mT51LU2WHg {
tyObject_PageDesc_fublkgIY4LG3mT51LU2WHg* next;
NI key;
tyArray_9a8QARi5WsUggNU9bom7kzTQ bits;
};
struct tyObject_OutputFormattercolonObjectType__dLGU9cWWYqlqOn8lpRVsx9cw {
  RootObj Sup;
};
struct tyObject_StackTraceEntry_oLyohQ7O2XOvGnflOss8EA {
NCSTRING procname;
NI line;
NCSTRING filename;
};
struct tyObject_JUnitOutputFormattercolonObjectType__kvLOVRX6Za2S0C2QxHXy9cQ {
  tyObject_OutputFormattercolonObjectType__dLGU9cWWYqlqOn8lpRVsx9cw Sup;
tyObject_StreamObj_RShkcoDOPnoCVhtpN1hDPQ* stream;
tySequence_sM4lkSb7zS6F7OVMvW9cffQ* testErrors;
NF testStartTime;
NimStringDesc* testStackTrace;
};
typedef NU8 tyEnum_OutputLevel_7UfTrIPsm9cGDPwH9bpwJDww;
struct tyObject_ConsoleOutputFormattercolonObjectType__dU6QGtP3KgqXg9bZP3nhpWw {
  tyObject_OutputFormattercolonObjectType__dLGU9cWWYqlqOn8lpRVsx9cw Sup;
NIM_BOOL colorOutput;
tyEnum_OutputLevel_7UfTrIPsm9cGDPwH9bpwJDww outputLevel;
NIM_BOOL isInSuite;
NIM_BOOL isInTest;
};
struct tyObject_FreeCell_u6M5LHprqzkn9axr04yg9bGQ {
tyObject_FreeCell_u6M5LHprqzkn9axr04yg9bGQ* next;
NI zeroField;
};
typedef N_NIMCALL_PTR(void, tyProc_cnkJEp9bna8U6yi9aVW9cAJ0Q) (tyObject_StreamObj_RShkcoDOPnoCVhtpN1hDPQ* s);
typedef N_NIMCALL_PTR(NIM_BOOL, tyProc_KjFcmLOhf4VQvVcyLJWXZw) (tyObject_StreamObj_RShkcoDOPnoCVhtpN1hDPQ* s);
typedef N_NIMCALL_PTR(void, tyProc_jlOYFw9cHausuCbPoWx2iiA) (tyObject_StreamObj_RShkcoDOPnoCVhtpN1hDPQ* s, NI pos);
typedef N_NIMCALL_PTR(NI, tyProc_Xzm85qBLb9cf9cu8VOfAr8PQ) (tyObject_StreamObj_RShkcoDOPnoCVhtpN1hDPQ* s);
typedef N_NIMCALL_PTR(NI, tyProc_tjaJtoUzLe1BMUbItlcGhQ) (tyObject_StreamObj_RShkcoDOPnoCVhtpN1hDPQ* s, void* buffer, NI bufLen);
typedef N_NIMCALL_PTR(void, tyProc_b9bsIuILxTLVZHPvJBW187A) (tyObject_StreamObj_RShkcoDOPnoCVhtpN1hDPQ* s, void* buffer, NI bufLen);
struct tyObject_StreamObj_RShkcoDOPnoCVhtpN1hDPQ {
  RootObj Sup;
tyProc_cnkJEp9bna8U6yi9aVW9cAJ0Q closeImpl;
tyProc_KjFcmLOhf4VQvVcyLJWXZw atEndImpl;
tyProc_jlOYFw9cHausuCbPoWx2iiA setPositionImpl;
tyProc_Xzm85qBLb9cf9cu8VOfAr8PQ getPositionImpl;
tyProc_tjaJtoUzLe1BMUbItlcGhQ readDataImpl;
tyProc_tjaJtoUzLe1BMUbItlcGhQ peekDataImpl;
tyProc_b9bsIuILxTLVZHPvJBW187A writeDataImpl;
tyProc_cnkJEp9bna8U6yi9aVW9cAJ0Q flushImpl;
};
struct tySequence_sM4lkSb7zS6F7OVMvW9cffQ {
  TGenericSeq Sup;
  NimStringDesc* data[SEQ_DECL_SIZE];
};
struct tySequence_2gM6knqz8MaAY9c4MAR2ztg {
  TGenericSeq Sup;
  tyObject_OutputFormattercolonObjectType__dLGU9cWWYqlqOn8lpRVsx9cw* data[SEQ_DECL_SIZE];
};
struct tySequence_uB9b75OUPRENsBAu4AnoePA {
  TGenericSeq Sup;
  tyObject_StackTraceEntry_oLyohQ7O2XOvGnflOss8EA data[SEQ_DECL_SIZE];
};
N_LIB_PRIVATE N_NIMCALL(void, ensureInitialized_8zybqvexf9aYkm9bmgyU3eLg)(void);
N_LIB_PRIVATE N_NIMCALL(NIM_BOOL, shouldRun_LgAPGDTu4rkb7Tq9asAgd9cQ)(NimStringDesc* currentSuiteName, NimStringDesc* testName);
static N_INLINE(void, nimGCunrefNoCycle)(void* p);
static N_INLINE(tyObject_Cell_1zcF9cV8XIAtbN8h5HRUB8g*, usrToCell_yB9aH5WIlwd0xkYrcdPeXrQsystem)(void* usr);
static N_INLINE(void, nimFrame)(TFrame* s);
N_LIB_PRIVATE N_NOINLINE(void, stackOverflow_II46IjNZztN9bmbxUD8dt8g)(void);
static N_INLINE(void, popFrame)(void);
static N_INLINE(void, rtlAddZCT_MV4BBk6J1qu70IbBxwEn4w_2system)(tyObject_Cell_1zcF9cV8XIAtbN8h5HRUB8g* c);
N_LIB_PRIVATE N_NOINLINE(void, addZCT_fCDI7oO1NNVXXURtxSzsRw)(tyObject_CellSeq_Axo1XVm9aaQueTOldv8le5w* s, tyObject_Cell_1zcF9cV8XIAtbN8h5HRUB8g* c);
N_NIMCALL(void*, newSeqRC1)(TNimType* typ, NI len);
N_NIMCALL(void, nimGCvisit)(void* d, NI op);
static N_NIMCALL(void, TM_4qp2gZX9anqPB0kpcB8Cugw_4)(void);
N_NIMCALL(void, nimRegisterGlobalMarker)(tyProc_T4eqaYlFJYZUv9aG9b1TV0bQ markerProc);
N_NOINLINE(void, raiseIndexError)(void);
static N_INLINE(void, asgnRef)(void** dest, void* src);
static N_INLINE(void, incRef_9cAA5YuQAAC3MVbnGeV86swsystem)(tyObject_Cell_1zcF9cV8XIAtbN8h5HRUB8g* c);
static N_INLINE(void, decRef_MV4BBk6J1qu70IbBxwEn4wsystem)(tyObject_Cell_1zcF9cV8XIAtbN8h5HRUB8g* c);
N_LIB_PRIVATE N_NIMCALL(void, testStarted_9bXmL9b2zT9aAVv9c8Tm6AvWog)(tyObject_OutputFormattercolonObjectType__dLGU9cWWYqlqOn8lpRVsx9cw* formatter, NimStringDesc* testName);
static N_INLINE(NI, addInt)(NI a, NI b);
N_NOINLINE(void, raiseOverflow)(void);
N_LIB_PRIVATE N_NIMCALL(void, failedAssertImpl_aDmpBTs9cPuXp0Mp9cfiNeyA)(NimStringDesc* msg);
static N_INLINE(void, pushSafePoint)(TSafePoint* s);
static N_NIMCALL(void, TM_4qp2gZX9anqPB0kpcB8Cugw_8)(void);
N_LIB_PRIVATE N_NIMCALL(NimStringDesc*, helloworld_gsKQNDh3DKS9bk2U4dhinhw)(NimStringDesc* name);
static N_INLINE(void, asgnRefNoCycle)(void** dest, void* src);
static N_INLINE(NIM_BOOL, eqStrings)(NimStringDesc* a, NimStringDesc* b);
static N_INLINE(NIM_BOOL, equalMem_fmeFeLBvgmAHG9bC8ETS9bYQsystem)(void* a, void* b, NI size);
N_LIB_PRIVATE N_NIMCALL(void, checkpoint_4nBz3prx9cKVVOoTZb4rNCQ)(NimStringDesc* msg);
static N_INLINE(void, appendString)(NimStringDesc* dest, NimStringDesc* src);
static N_INLINE(void, copyMem_E1xtACub5WcDa3vbrIXbwgsystem)(void* dest, void* source, NI size);
N_NIMCALL(NimStringDesc*, rawNewString)(NI space);
static N_NIMCALL(void, TM_4qp2gZX9anqPB0kpcB8Cugw_13)(void);
N_LIB_PRIVATE N_NIMCALL(void, failureOccurred_i9ctYnjK2z9bxX9cq0gYct9cIA)(tyObject_OutputFormattercolonObjectType__dLGU9cWWYqlqOn8lpRVsx9cw* formatter, tySequence_sM4lkSb7zS6F7OVMvW9cffQ* checkpoints, NimStringDesc* stackTrace);
static N_INLINE(void, popSafePoint)(void);
static N_INLINE(void, setFrame)(TFrame* s);
static N_INLINE(NimStringDesc*, getCurrentExceptionMsg_fOe1OXzHoGbgrd7IEmbp5Qsystem)(void);
static N_INLINE(Exception*, getCurrentException)(void);
N_NIMCALL(NimStringDesc*, copyString)(NimStringDesc* src);
static N_NIMCALL(void, TM_4qp2gZX9anqPB0kpcB8Cugw_16)(void);
N_LIB_PRIVATE N_NIMCALL(NimStringDesc*, getStackTrace_OenGRUrwbq9c3AFUxAFv9cuA)(Exception* e);
static N_NIMCALL(void, TM_4qp2gZX9anqPB0kpcB8Cugw_17)(void);
static N_INLINE(void, popCurrentException)(void);
static N_NIMCALL(void, TM_4qp2gZX9anqPB0kpcB8Cugw_20)(void);
N_NOINLINE(void, chckNil)(void* p);
N_NIMCALL(void, genericReset)(void* dest, TNimType* mt);
N_NIMCALL(NimStringDesc*, copyStringRC1)(NimStringDesc* src);
N_LIB_PRIVATE N_NIMCALL(void, testEnded_xoIS1BdhYWQ6hhMP22XXiw)(tyObject_TestResult_GEvSVSxdPWWgMGM48ywEYQ testResult);
N_NIMCALL(void, reraiseException)(void);
static N_NIMCALL(void, TM_4qp2gZX9anqPB0kpcB8Cugw_22)(void);
static N_NIMCALL(void, TM_4qp2gZX9anqPB0kpcB8Cugw_25)(void);
static N_NIMCALL(void, TM_4qp2gZX9anqPB0kpcB8Cugw_30)(void);
static N_NIMCALL(void, TM_4qp2gZX9anqPB0kpcB8Cugw_32)(void);
static N_NIMCALL(void, TM_4qp2gZX9anqPB0kpcB8Cugw_33)(void);
static N_NIMCALL(void, TM_4qp2gZX9anqPB0kpcB8Cugw_36)(void);
static N_NIMCALL(void, TM_4qp2gZX9anqPB0kpcB8Cugw_38)(void);
static N_NIMCALL(void, TM_4qp2gZX9anqPB0kpcB8Cugw_41)(void);
static N_NIMCALL(void, TM_4qp2gZX9anqPB0kpcB8Cugw_46)(void);
static N_NIMCALL(void, TM_4qp2gZX9anqPB0kpcB8Cugw_48)(void);
static N_NIMCALL(void, TM_4qp2gZX9anqPB0kpcB8Cugw_49)(void);
static N_NIMCALL(void, TM_4qp2gZX9anqPB0kpcB8Cugw_52)(void);
N_NIMCALL(void, chckNilDisp)(void* p);
static N_INLINE(NIM_BOOL, isObjWithCache)(TNimType* obj, TNimType* subclass, TNimType** cache);
N_LIB_PRIVATE N_NOINLINE(NIM_BOOL, isObjSlowPath_k9bdq9bQE075AR7scLFt5wIg)(TNimType* obj, TNimType* subclass, TNimType** cache);
N_LIB_PRIVATE N_NIMCALL(void, suiteStarted_9aAyDoHTMoiLoSiMpkUAFNw)(tyObject_JUnitOutputFormattercolonObjectType__kvLOVRX6Za2S0C2QxHXy9cQ* formatter, NimStringDesc* suiteName);
N_NIMCALL(void, chckObj)(TNimType* obj, TNimType* subclass);
N_LIB_PRIVATE N_NIMCALL(void, suiteStarted_3pDl7sjdCupGLpWwbS2CHg)(tyObject_ConsoleOutputFormattercolonObjectType__dU6QGtP3KgqXg9bZP3nhpWw* formatter, NimStringDesc* suiteName);
N_LIB_PRIVATE N_NIMCALL(void, suiteStarted_zvRCVP5x4ZBpPV2Xx9cPHZA)(tyObject_OutputFormattercolonObjectType__dLGU9cWWYqlqOn8lpRVsx9cw* formatter, NimStringDesc* suiteName);
N_LIB_PRIVATE N_NIMCALL(void, testStarted_EYS8dFM0pZmDNdV9c1cyo4Q)(tyObject_JUnitOutputFormattercolonObjectType__kvLOVRX6Za2S0C2QxHXy9cQ* formatter, NimStringDesc* testName);
N_LIB_PRIVATE N_NIMCALL(void, testStarted_0WlfvTsMUPRHUfLeuXrGAg)(tyObject_ConsoleOutputFormattercolonObjectType__dU6QGtP3KgqXg9bZP3nhpWw* formatter, NimStringDesc* testName);
N_LIB_PRIVATE N_NIMCALL(void, testStarted_YRuPwQXlDxZko9bSMypk3hA)(tyObject_OutputFormattercolonObjectType__dLGU9cWWYqlqOn8lpRVsx9cw* formatter, NimStringDesc* testName);
N_LIB_PRIVATE N_NIMCALL(void, failureOccurred_NAlHeCfOfz1bBvtw2rCPGw)(tyObject_JUnitOutputFormattercolonObjectType__kvLOVRX6Za2S0C2QxHXy9cQ* formatter, tySequence_sM4lkSb7zS6F7OVMvW9cffQ* checkpoints, NimStringDesc* stackTrace);
N_LIB_PRIVATE N_NIMCALL(void, failureOccurred_HopmjhtOQil8N9axQ5kNI3w)(tyObject_ConsoleOutputFormattercolonObjectType__dU6QGtP3KgqXg9bZP3nhpWw* formatter, tySequence_sM4lkSb7zS6F7OVMvW9cffQ* checkpoints, NimStringDesc* stackTrace);
N_LIB_PRIVATE N_NIMCALL(void, failureOccurred_Fsq9aCTSjbGiV7TYpR757Lw)(tyObject_OutputFormattercolonObjectType__dLGU9cWWYqlqOn8lpRVsx9cw* formatter, tySequence_sM4lkSb7zS6F7OVMvW9cffQ* checkpoints, NimStringDesc* stackTrace);
N_LIB_PRIVATE N_NIMCALL(void, testEnded_E5f9a05hVCAPvYslPV2f4TQ)(tyObject_JUnitOutputFormattercolonObjectType__kvLOVRX6Za2S0C2QxHXy9cQ* formatter, tyObject_TestResult_GEvSVSxdPWWgMGM48ywEYQ testResult);
N_LIB_PRIVATE N_NIMCALL(void, testEnded_fZDr7JVThcpXnuqtgFvwWQ)(tyObject_ConsoleOutputFormattercolonObjectType__dU6QGtP3KgqXg9bZP3nhpWw* formatter, tyObject_TestResult_GEvSVSxdPWWgMGM48ywEYQ testResult);
N_LIB_PRIVATE N_NIMCALL(void, testEnded_hPRwDS9aOIRJ5MB9buAX30Wg)(tyObject_OutputFormattercolonObjectType__dLGU9cWWYqlqOn8lpRVsx9cw* formatter, tyObject_TestResult_GEvSVSxdPWWgMGM48ywEYQ testResult);
N_LIB_PRIVATE N_NIMCALL(void, suiteEnded_EF53BADEiH9a6amiy7eitMg_2)(tyObject_JUnitOutputFormattercolonObjectType__kvLOVRX6Za2S0C2QxHXy9cQ* formatter);
N_LIB_PRIVATE N_NIMCALL(void, suiteEnded_IIGQUyJJjT9cNV9c34JPjWGA)(tyObject_ConsoleOutputFormattercolonObjectType__dU6QGtP3KgqXg9bZP3nhpWw* formatter);
N_LIB_PRIVATE N_NIMCALL(void, suiteEnded_RS3dEHKAbuhOugXu1dXVHg)(tyObject_OutputFormattercolonObjectType__dLGU9cWWYqlqOn8lpRVsx9cw* formatter);
static N_INLINE(void, initStackBottomWith)(void* locals);
N_NOINLINE(void, setStackBottom)(void* theStackBottom);
NIM_EXTERNC N_NOINLINE(void, systemInit000)(void);
NIM_EXTERNC N_NOINLINE(void, systemDatInit000)(void);
NIM_EXTERNC N_NOINLINE(void, stdlib_macrosInit000)(void);
NIM_EXTERNC N_NOINLINE(void, stdlib_macrosDatInit000)(void);
NIM_EXTERNC N_NOINLINE(void, stdlib_parseutilsInit000)(void);
NIM_EXTERNC N_NOINLINE(void, stdlib_parseutilsDatInit000)(void);
NIM_EXTERNC N_NOINLINE(void, stdlib_mathInit000)(void);
NIM_EXTERNC N_NOINLINE(void, stdlib_mathDatInit000)(void);
NIM_EXTERNC N_NOINLINE(void, stdlib_algorithmInit000)(void);
NIM_EXTERNC N_NOINLINE(void, stdlib_algorithmDatInit000)(void);
NIM_EXTERNC N_NOINLINE(void, stdlib_strutilsInit000)(void);
NIM_EXTERNC N_NOINLINE(void, stdlib_strutilsDatInit000)(void);
NIM_EXTERNC N_NOINLINE(void, stdlib_streamsInit000)(void);
NIM_EXTERNC N_NOINLINE(void, stdlib_streamsDatInit000)(void);
NIM_EXTERNC N_NOINLINE(void, stdlib_posixInit000)(void);
NIM_EXTERNC N_NOINLINE(void, stdlib_posixDatInit000)(void);
NIM_EXTERNC N_NOINLINE(void, stdlib_timesInit000)(void);
NIM_EXTERNC N_NOINLINE(void, stdlib_timesDatInit000)(void);
NIM_EXTERNC N_NOINLINE(void, stdlib_hashesInit000)(void);
NIM_EXTERNC N_NOINLINE(void, stdlib_hashesDatInit000)(void);
NIM_EXTERNC N_NOINLINE(void, stdlib_setsInit000)(void);
NIM_EXTERNC N_NOINLINE(void, stdlib_setsDatInit000)(void);
NIM_EXTERNC N_NOINLINE(void, stdlib_ospathsInit000)(void);
NIM_EXTERNC N_NOINLINE(void, stdlib_ospathsDatInit000)(void);
NIM_EXTERNC N_NOINLINE(void, stdlib_osInit000)(void);
NIM_EXTERNC N_NOINLINE(void, stdlib_osDatInit000)(void);
NIM_EXTERNC N_NOINLINE(void, stdlib_unicodeInit000)(void);
NIM_EXTERNC N_NOINLINE(void, stdlib_unicodeDatInit000)(void);
NIM_EXTERNC N_NOINLINE(void, stdlib_strformatInit000)(void);
NIM_EXTERNC N_NOINLINE(void, stdlib_strformatDatInit000)(void);
NIM_EXTERNC N_NOINLINE(void, stdlib_colorsInit000)(void);
NIM_EXTERNC N_NOINLINE(void, stdlib_colorsDatInit000)(void);
NIM_EXTERNC N_NOINLINE(void, stdlib_tablesInit000)(void);
NIM_EXTERNC N_NOINLINE(void, stdlib_tablesDatInit000)(void);
NIM_EXTERNC N_NOINLINE(void, stdlib_termiosInit000)(void);
NIM_EXTERNC N_NOINLINE(void, stdlib_termiosDatInit000)(void);
NIM_EXTERNC N_NOINLINE(void, stdlib_terminalInit000)(void);
NIM_EXTERNC N_NOINLINE(void, stdlib_terminalDatInit000)(void);
NIM_EXTERNC N_NOINLINE(void, stdlib_unittestInit000)(void);
NIM_EXTERNC N_NOINLINE(void, stdlib_unittestDatInit000)(void);
NIM_EXTERNC N_NOINLINE(void, unknown_helloworldInit000)(void);
NIM_EXTERNC N_NOINLINE(void, unknown_helloworldDatInit000)(void);
NIM_EXTERNC N_NOINLINE(void, NimMainModule)(void);
NIM_EXTERNC N_NOINLINE(void, helloworld_testDatInit000)(void);
extern tySequence_sM4lkSb7zS6F7OVMvW9cffQ* checkpoints_bq5hLRYOyiTcYy29a9akD9c9bQ;
extern TNimType NTI_sM4lkSb7zS6F7OVMvW9cffQ_;
extern TFrame* framePtr_HRfVMH3jYeBJz6Q6X9b6Ptw;
extern tyObject_GcHeap_1TRH1TZMaVZTnLNcIHuNFQ gch_IcYaEuuWivYAS86vFMTS3Q;
tyEnum_TestStatus_W9bTUg9c9a7UlIYkKYmd5uasQ testStatusIMPL_Q4qcz3YlFyWrLneTJlsS4Q;
tyObject_OutputFormattercolonObjectType__dLGU9cWWYqlqOn8lpRVsx9cw* formatter_6vZ0eCyziJIpjOJxE6ZZSA;
extern TNimType NTI_po6hYFavJCZm28qf1dR3mw_;
extern tySequence_2gM6knqz8MaAY9c4MAR2ztg* formatters_55U7g4zhjHV9bCI6emTgDiA;
extern TSafePoint* excHandler_rqLlY5bs9atDw2OXYqJEn5g;
NimStringDesc* colonc1__WzG62vRKCCCuEmzM9bJ2gjA;
extern TNimType NTI_77mFvmsOLKik79ci2hXkHEg_;
tyObject_OutputFormattercolonObjectType__dLGU9cWWYqlqOn8lpRVsx9cw* formatter_6vZ0eCyziJIpjOJxE6ZZSA_2;
extern NIM_BOOL abortOnError_Bte3Uiwc4Q19ago2N4C89cUA;
extern NI nim_program_result;
extern Exception* currException_9bVPeDJlYTi9bQApZpfH8wjg;
NimStringDesc* stackTrace_yo79audNUOaALqoPY6lz8tQ;
tyObject_OutputFormattercolonObjectType__dLGU9cWWYqlqOn8lpRVsx9cw* formatter_6vZ0eCyziJIpjOJxE6ZZSA_3;
tyObject_TestResult_GEvSVSxdPWWgMGM48ywEYQ testResult_zKJcLcg3TmFPRC7R7c9cT9bg;
extern TNimType NTI_GEvSVSxdPWWgMGM48ywEYQ_;
tyEnum_TestStatus_W9bTUg9c9a7UlIYkKYmd5uasQ testStatusIMPL_Q4qcz3YlFyWrLneTJlsS4Q_2;
tyObject_OutputFormattercolonObjectType__dLGU9cWWYqlqOn8lpRVsx9cw* formatter_6vZ0eCyziJIpjOJxE6ZZSA_4;
NimStringDesc* colonc1__WzG62vRKCCCuEmzM9bJ2gjA_2;
tyObject_OutputFormattercolonObjectType__dLGU9cWWYqlqOn8lpRVsx9cw* formatter_6vZ0eCyziJIpjOJxE6ZZSA_5;
NimStringDesc* stackTrace_yo79audNUOaALqoPY6lz8tQ_2;
tyObject_OutputFormattercolonObjectType__dLGU9cWWYqlqOn8lpRVsx9cw* formatter_6vZ0eCyziJIpjOJxE6ZZSA_6;
tyObject_TestResult_GEvSVSxdPWWgMGM48ywEYQ testResult_zKJcLcg3TmFPRC7R7c9cT9bg_2;
tyEnum_TestStatus_W9bTUg9c9a7UlIYkKYmd5uasQ testStatusIMPL_Q4qcz3YlFyWrLneTJlsS4Q_3;
tyObject_OutputFormattercolonObjectType__dLGU9cWWYqlqOn8lpRVsx9cw* formatter_6vZ0eCyziJIpjOJxE6ZZSA_7;
NimStringDesc* colonc1__WzG62vRKCCCuEmzM9bJ2gjA_3;
tyObject_OutputFormattercolonObjectType__dLGU9cWWYqlqOn8lpRVsx9cw* formatter_6vZ0eCyziJIpjOJxE6ZZSA_8;
NimStringDesc* stackTrace_yo79audNUOaALqoPY6lz8tQ_3;
tyObject_OutputFormattercolonObjectType__dLGU9cWWYqlqOn8lpRVsx9cw* formatter_6vZ0eCyziJIpjOJxE6ZZSA_9;
tyObject_TestResult_GEvSVSxdPWWgMGM48ywEYQ testResult_zKJcLcg3TmFPRC7R7c9cT9bg_3;
extern TNimType NTI_kvLOVRX6Za2S0C2QxHXy9cQ_;
static TNimType* Nim_OfCheck_CACHE54[2];
extern TNimType NTI_dU6QGtP3KgqXg9bZP3nhpWw_;
static TNimType* Nim_OfCheck_CACHE55[2];
extern TNimType NTI_dLGU9cWWYqlqOn8lpRVsx9cw_;
static TNimType* Nim_OfCheck_CACHE56[2];
static TNimType* Nim_OfCheck_CACHE57[2];
static TNimType* Nim_OfCheck_CACHE58[2];
static TNimType* Nim_OfCheck_CACHE59[2];
static TNimType* Nim_OfCheck_CACHE60[2];
static TNimType* Nim_OfCheck_CACHE61[2];
static TNimType* Nim_OfCheck_CACHE62[2];
static TNimType* Nim_OfCheck_CACHE63[2];
static TNimType* Nim_OfCheck_CACHE64[2];
static TNimType* Nim_OfCheck_CACHE65[2];
static TNimType* Nim_OfCheck_CACHE66[2];
static TNimType* Nim_OfCheck_CACHE67[2];
static TNimType* Nim_OfCheck_CACHE68[2];
STRING_LITERAL(TM_4qp2gZX9anqPB0kpcB8Cugw_2, "", 0);
STRING_LITERAL(TM_4qp2gZX9anqPB0kpcB8Cugw_3, "no name", 7);
STRING_LITERAL(TM_4qp2gZX9anqPB0kpcB8Cugw_6, "len(a) == L seq modified while iterating over it", 48);
STRING_LITERAL(TM_4qp2gZX9anqPB0kpcB8Cugw_9, "World", 5);
STRING_LITERAL(TM_4qp2gZX9anqPB0kpcB8Cugw_10, "Hello, World!", 13);
STRING_LITERAL(TM_4qp2gZX9anqPB0kpcB8Cugw_11, "helloworld_test.nim(6, 21): Check failed: helloworld() == \"Hell"
"o, World!\"", 73);
STRING_LITERAL(TM_4qp2gZX9anqPB0kpcB8Cugw_12, "helloworld() was ", 17);
STRING_LITERAL(TM_4qp2gZX9anqPB0kpcB8Cugw_15, "Unhandled exception: ", 21);
STRING_LITERAL(TM_4qp2gZX9anqPB0kpcB8Cugw_21, "sample name", 11);
STRING_LITERAL(TM_4qp2gZX9anqPB0kpcB8Cugw_26, "Alice", 5);
STRING_LITERAL(TM_4qp2gZX9anqPB0kpcB8Cugw_27, "Hello, Alice!", 13);
STRING_LITERAL(TM_4qp2gZX9anqPB0kpcB8Cugw_28, "helloworld_test.nim(9, 28): Check failed: helloworld(\"Alice\") ="
"= \"Hello, Alice!\"", 80);
STRING_LITERAL(TM_4qp2gZX9anqPB0kpcB8Cugw_29, "helloworld(\"Alice\") was ", 24);
STRING_LITERAL(TM_4qp2gZX9anqPB0kpcB8Cugw_37, "other sample name", 17);
STRING_LITERAL(TM_4qp2gZX9anqPB0kpcB8Cugw_42, "Bob", 3);
STRING_LITERAL(TM_4qp2gZX9anqPB0kpcB8Cugw_43, "Hello, Bob!", 11);
STRING_LITERAL(TM_4qp2gZX9anqPB0kpcB8Cugw_44, "helloworld_test.nim(12, 26): Check failed: helloworld(\"Bob\") =="
" \"Hello, Bob!\"", 77);
STRING_LITERAL(TM_4qp2gZX9anqPB0kpcB8Cugw_45, "helloworld(\"Bob\") was ", 22);

static N_INLINE(void, nimFrame)(TFrame* s) {
	NI T1_;
	T1_ = (NI)0;
	{
		if (!(framePtr_HRfVMH3jYeBJz6Q6X9b6Ptw == NIM_NIL)) goto LA4_;
		T1_ = ((NI) 0);
	}
	goto LA2_;
	LA4_: ;
	{
		T1_ = ((NI) ((NI16)((*framePtr_HRfVMH3jYeBJz6Q6X9b6Ptw).calldepth + ((NI16) 1))));
	}
	LA2_: ;
	(*s).calldepth = ((NI16) (T1_));
	(*s).prev = framePtr_HRfVMH3jYeBJz6Q6X9b6Ptw;
	framePtr_HRfVMH3jYeBJz6Q6X9b6Ptw = s;
	{
		if (!((*s).calldepth == ((NI16) 2000))) goto LA9_;
		stackOverflow_II46IjNZztN9bmbxUD8dt8g();
	}
	LA9_: ;
}

static N_INLINE(void, popFrame)(void) {
	framePtr_HRfVMH3jYeBJz6Q6X9b6Ptw = (*framePtr_HRfVMH3jYeBJz6Q6X9b6Ptw).prev;
}

static N_INLINE(tyObject_Cell_1zcF9cV8XIAtbN8h5HRUB8g*, usrToCell_yB9aH5WIlwd0xkYrcdPeXrQsystem)(void* usr) {
	tyObject_Cell_1zcF9cV8XIAtbN8h5HRUB8g* result;
	nimfr_("usrToCell", "gc.nim");
	result = (tyObject_Cell_1zcF9cV8XIAtbN8h5HRUB8g*)0;
	nimln_(132, "gc.nim");
	result = ((tyObject_Cell_1zcF9cV8XIAtbN8h5HRUB8g*) ((NI)((NU64)(((NI) (ptrdiff_t) (usr))) - (NU64)(((NI)sizeof(tyObject_Cell_1zcF9cV8XIAtbN8h5HRUB8g))))));
	popFrame();
	return result;
}

static N_INLINE(void, rtlAddZCT_MV4BBk6J1qu70IbBxwEn4w_2system)(tyObject_Cell_1zcF9cV8XIAtbN8h5HRUB8g* c) {
	nimfr_("rtlAddZCT", "gc.nim");
	nimln_(211, "gc.nim");
	addZCT_fCDI7oO1NNVXXURtxSzsRw((&gch_IcYaEuuWivYAS86vFMTS3Q.zct), c);
	popFrame();
}

static N_INLINE(void, nimGCunrefNoCycle)(void* p) {
	tyObject_Cell_1zcF9cV8XIAtbN8h5HRUB8g* c;
	nimfr_("nimGCunrefNoCycle", "gc.nim");
	nimln_(250, "gc.nim");
	c = usrToCell_yB9aH5WIlwd0xkYrcdPeXrQsystem(p);
	nimln_(252, "gc.nim");
	{
		(*c).refcount -= ((NI) 8);
		if (!((NU64)((*c).refcount) < (NU64)(((NI) 8)))) goto LA3_;
		nimln_(253, "gc.nim");
		rtlAddZCT_MV4BBk6J1qu70IbBxwEn4w_2system(c);
	}
	LA3_: ;
	popFrame();
}
static N_NIMCALL(void, TM_4qp2gZX9anqPB0kpcB8Cugw_4)(void) {
	nimGCvisit((void*)formatter_6vZ0eCyziJIpjOJxE6ZZSA, 0);
}

static N_INLINE(void, incRef_9cAA5YuQAAC3MVbnGeV86swsystem)(tyObject_Cell_1zcF9cV8XIAtbN8h5HRUB8g* c) {
	nimfr_("incRef", "gc.nim");
	nimln_(191, "gc.nim");
	(*c).refcount = (NI)((NU64)((*c).refcount) + (NU64)(((NI) 8)));
	popFrame();
}

static N_INLINE(void, decRef_MV4BBk6J1qu70IbBxwEn4wsystem)(tyObject_Cell_1zcF9cV8XIAtbN8h5HRUB8g* c) {
	nimfr_("decRef", "gc.nim");
	nimln_(218, "gc.nim");
	{
		(*c).refcount -= ((NI) 8);
		if (!((NU64)((*c).refcount) < (NU64)(((NI) 8)))) goto LA3_;
		nimln_(219, "gc.nim");
		rtlAddZCT_MV4BBk6J1qu70IbBxwEn4w_2system(c);
	}
	LA3_: ;
	popFrame();
}

static N_INLINE(void, asgnRef)(void** dest, void* src) {
	nimfr_("asgnRef", "gc.nim");
	nimln_(264, "gc.nim");
	{
		tyObject_Cell_1zcF9cV8XIAtbN8h5HRUB8g* T5_;
		nimln_(398, "system.nim");
		nimln_(264, "gc.nim");
		if (!!((src == NIM_NIL))) goto LA3_;
		T5_ = (tyObject_Cell_1zcF9cV8XIAtbN8h5HRUB8g*)0;
		T5_ = usrToCell_yB9aH5WIlwd0xkYrcdPeXrQsystem(src);
		incRef_9cAA5YuQAAC3MVbnGeV86swsystem(T5_);
	}
	LA3_: ;
	nimln_(265, "gc.nim");
	{
		tyObject_Cell_1zcF9cV8XIAtbN8h5HRUB8g* T10_;
		nimln_(398, "system.nim");
		nimln_(265, "gc.nim");
		if (!!(((*dest) == NIM_NIL))) goto LA8_;
		T10_ = (tyObject_Cell_1zcF9cV8XIAtbN8h5HRUB8g*)0;
		T10_ = usrToCell_yB9aH5WIlwd0xkYrcdPeXrQsystem((*dest));
		decRef_MV4BBk6J1qu70IbBxwEn4wsystem(T10_);
	}
	LA8_: ;
	nimln_(266, "gc.nim");
	(*dest) = src;
	popFrame();
}

static N_INLINE(NI, addInt)(NI a, NI b) {
	NI result;
{	result = (NI)0;
	result = (NI)((NU64)(a) + (NU64)(b));
	{
		NIM_BOOL T3_;
		T3_ = (NIM_BOOL)0;
		T3_ = (((NI) 0) <= (NI)(result ^ a));
		if (T3_) goto LA4_;
		T3_ = (((NI) 0) <= (NI)(result ^ b));
		LA4_: ;
		if (!T3_) goto LA5_;
		goto BeforeRet_;
	}
	LA5_: ;
	raiseOverflow();
	}BeforeRet_: ;
	return result;
}

static N_INLINE(void, pushSafePoint)(TSafePoint* s) {
	(*s).hasRaiseAction = NIM_FALSE;
	(*s).prev = excHandler_rqLlY5bs9atDw2OXYqJEn5g;
	excHandler_rqLlY5bs9atDw2OXYqJEn5g = s;
}
static N_NIMCALL(void, TM_4qp2gZX9anqPB0kpcB8Cugw_8)(void) {
	nimGCvisit((void*)colonc1__WzG62vRKCCCuEmzM9bJ2gjA, 0);
}

static N_INLINE(void, asgnRefNoCycle)(void** dest, void* src) {
	nimfr_("asgnRefNoCycle", "gc.nim");
	nimln_(271, "gc.nim");
	{
		tyObject_Cell_1zcF9cV8XIAtbN8h5HRUB8g* c;
		nimln_(398, "system.nim");
		nimln_(271, "gc.nim");
		if (!!((src == NIM_NIL))) goto LA3_;
		nimln_(272, "gc.nim");
		c = usrToCell_yB9aH5WIlwd0xkYrcdPeXrQsystem(src);
		nimln_(273, "gc.nim");
		(*c).refcount += ((NI) 8);
	}
	LA3_: ;
	nimln_(274, "gc.nim");
	{
		tyObject_Cell_1zcF9cV8XIAtbN8h5HRUB8g* c_2;
		nimln_(398, "system.nim");
		nimln_(274, "gc.nim");
		if (!!(((*dest) == NIM_NIL))) goto LA7_;
		nimln_(275, "gc.nim");
		c_2 = usrToCell_yB9aH5WIlwd0xkYrcdPeXrQsystem((*dest));
		nimln_(276, "gc.nim");
		{
			(*c_2).refcount -= ((NI) 8);
			if (!((NU64)((*c_2).refcount) < (NU64)(((NI) 8)))) goto LA11_;
			nimln_(277, "gc.nim");
			rtlAddZCT_MV4BBk6J1qu70IbBxwEn4w_2system(c_2);
		}
		LA11_: ;
	}
	LA7_: ;
	nimln_(278, "gc.nim");
	(*dest) = src;
	popFrame();
}

static N_INLINE(NIM_BOOL, equalMem_fmeFeLBvgmAHG9bC8ETS9bYQsystem)(void* a, void* b, NI size) {
	NIM_BOOL result;
	int T1_;
	result = (NIM_BOOL)0;
	T1_ = (int)0;
	T1_ = memcmp(a, b, ((size_t) (size)));
	result = (T1_ == ((NI32) 0));
	return result;
}

static N_INLINE(NIM_BOOL, eqStrings)(NimStringDesc* a, NimStringDesc* b) {
	NIM_BOOL result;
	NIM_BOOL T11_;
{	result = (NIM_BOOL)0;
	{
		if (!(a == b)) goto LA3_;
		result = NIM_TRUE;
		goto BeforeRet_;
	}
	LA3_: ;
	{
		NIM_BOOL T7_;
		T7_ = (NIM_BOOL)0;
		T7_ = (a == NIM_NIL);
		if (T7_) goto LA8_;
		T7_ = (b == NIM_NIL);
		LA8_: ;
		if (!T7_) goto LA9_;
		result = NIM_FALSE;
		goto BeforeRet_;
	}
	LA9_: ;
	T11_ = (NIM_BOOL)0;
	T11_ = ((*a).Sup.len == (*b).Sup.len);
	if (!(T11_)) goto LA12_;
	T11_ = equalMem_fmeFeLBvgmAHG9bC8ETS9bYQsystem(((void*) ((*a).data)), ((void*) ((*b).data)), ((NI) ((*a).Sup.len)));
	LA12_: ;
	result = T11_;
	goto BeforeRet_;
	}BeforeRet_: ;
	return result;
}

static N_INLINE(void, copyMem_E1xtACub5WcDa3vbrIXbwgsystem)(void* dest, void* source, NI size) {
	void* T1_;
	T1_ = (void*)0;
	T1_ = memcpy(dest, source, ((size_t) (size)));
}

static N_INLINE(void, appendString)(NimStringDesc* dest, NimStringDesc* src) {
	copyMem_E1xtACub5WcDa3vbrIXbwgsystem(((void*) ((&(*dest).data[((*dest).Sup.len)- 0]))), ((void*) ((*src).data)), ((NI) ((NI)((*src).Sup.len + ((NI) 1)))));
	(*dest).Sup.len += (*src).Sup.len;
}
static N_NIMCALL(void, TM_4qp2gZX9anqPB0kpcB8Cugw_13)(void) {
	nimGCvisit((void*)formatter_6vZ0eCyziJIpjOJxE6ZZSA_2, 0);
}

static N_INLINE(void, popSafePoint)(void) {
	excHandler_rqLlY5bs9atDw2OXYqJEn5g = (*excHandler_rqLlY5bs9atDw2OXYqJEn5g).prev;
}

static N_INLINE(void, setFrame)(TFrame* s) {
	framePtr_HRfVMH3jYeBJz6Q6X9b6Ptw = s;
}

static N_INLINE(Exception*, getCurrentException)(void) {
	Exception* result;
	nimfr_("getCurrentException", "system.nim");
	result = (Exception*)0;
	nimln_(3350, "system.nim");
	result = currException_9bVPeDJlYTi9bQApZpfH8wjg;
	popFrame();
	return result;
}

static N_INLINE(NimStringDesc*, getCurrentExceptionMsg_fOe1OXzHoGbgrd7IEmbp5Qsystem)(void) {
	NimStringDesc* result;
	Exception* e;
	nimfr_("getCurrentExceptionMsg", "system.nim");
{	result = (NimStringDesc*)0;
	nimln_(3355, "system.nim");
	e = getCurrentException();
	nimln_(3356, "system.nim");
	{
		if (!(e == NIM_NIL)) goto LA3_;
		result = copyString(((NimStringDesc*) &TM_4qp2gZX9anqPB0kpcB8Cugw_2));
	}
	goto LA1_;
	LA3_: ;
	{
		result = copyString((*e).message);
	}
	LA1_: ;
	goto BeforeRet_;
	}BeforeRet_: ;
	popFrame();
	return result;
}
static N_NIMCALL(void, TM_4qp2gZX9anqPB0kpcB8Cugw_16)(void) {
	nimGCvisit((void*)stackTrace_yo79audNUOaALqoPY6lz8tQ, 0);
}
static N_NIMCALL(void, TM_4qp2gZX9anqPB0kpcB8Cugw_17)(void) {
	nimGCvisit((void*)formatter_6vZ0eCyziJIpjOJxE6ZZSA_3, 0);
}

static N_INLINE(void, popCurrentException)(void) {
	asgnRef((void**) (&currException_9bVPeDJlYTi9bQApZpfH8wjg), (*currException_9bVPeDJlYTi9bQApZpfH8wjg).up);
}
static N_NIMCALL(void, TM_4qp2gZX9anqPB0kpcB8Cugw_20)(void) {
	nimGCvisit((void*)testResult_zKJcLcg3TmFPRC7R7c9cT9bg.suiteName, 0);
	nimGCvisit((void*)testResult_zKJcLcg3TmFPRC7R7c9cT9bg.testName, 0);
}
static N_NIMCALL(void, TM_4qp2gZX9anqPB0kpcB8Cugw_22)(void) {
	nimGCvisit((void*)formatter_6vZ0eCyziJIpjOJxE6ZZSA_4, 0);
}
static N_NIMCALL(void, TM_4qp2gZX9anqPB0kpcB8Cugw_25)(void) {
	nimGCvisit((void*)colonc1__WzG62vRKCCCuEmzM9bJ2gjA_2, 0);
}
static N_NIMCALL(void, TM_4qp2gZX9anqPB0kpcB8Cugw_30)(void) {
	nimGCvisit((void*)formatter_6vZ0eCyziJIpjOJxE6ZZSA_5, 0);
}
static N_NIMCALL(void, TM_4qp2gZX9anqPB0kpcB8Cugw_32)(void) {
	nimGCvisit((void*)stackTrace_yo79audNUOaALqoPY6lz8tQ_2, 0);
}
static N_NIMCALL(void, TM_4qp2gZX9anqPB0kpcB8Cugw_33)(void) {
	nimGCvisit((void*)formatter_6vZ0eCyziJIpjOJxE6ZZSA_6, 0);
}
static N_NIMCALL(void, TM_4qp2gZX9anqPB0kpcB8Cugw_36)(void) {
	nimGCvisit((void*)testResult_zKJcLcg3TmFPRC7R7c9cT9bg_2.suiteName, 0);
	nimGCvisit((void*)testResult_zKJcLcg3TmFPRC7R7c9cT9bg_2.testName, 0);
}
static N_NIMCALL(void, TM_4qp2gZX9anqPB0kpcB8Cugw_38)(void) {
	nimGCvisit((void*)formatter_6vZ0eCyziJIpjOJxE6ZZSA_7, 0);
}
static N_NIMCALL(void, TM_4qp2gZX9anqPB0kpcB8Cugw_41)(void) {
	nimGCvisit((void*)colonc1__WzG62vRKCCCuEmzM9bJ2gjA_3, 0);
}
static N_NIMCALL(void, TM_4qp2gZX9anqPB0kpcB8Cugw_46)(void) {
	nimGCvisit((void*)formatter_6vZ0eCyziJIpjOJxE6ZZSA_8, 0);
}
static N_NIMCALL(void, TM_4qp2gZX9anqPB0kpcB8Cugw_48)(void) {
	nimGCvisit((void*)stackTrace_yo79audNUOaALqoPY6lz8tQ_3, 0);
}
static N_NIMCALL(void, TM_4qp2gZX9anqPB0kpcB8Cugw_49)(void) {
	nimGCvisit((void*)formatter_6vZ0eCyziJIpjOJxE6ZZSA_9, 0);
}
static N_NIMCALL(void, TM_4qp2gZX9anqPB0kpcB8Cugw_52)(void) {
	nimGCvisit((void*)testResult_zKJcLcg3TmFPRC7R7c9cT9bg_3.suiteName, 0);
	nimGCvisit((void*)testResult_zKJcLcg3TmFPRC7R7c9cT9bg_3.testName, 0);
}

static N_INLINE(NIM_BOOL, isObjWithCache)(TNimType* obj, TNimType* subclass, TNimType** cache) {
	NIM_BOOL result;
{	result = (NIM_BOOL)0;
	{
		if (!(obj == subclass)) goto LA3_;
		result = NIM_TRUE;
		goto BeforeRet_;
	}
	LA3_: ;
	{
		if (!((*obj).base == subclass)) goto LA7_;
		result = NIM_TRUE;
		goto BeforeRet_;
	}
	LA7_: ;
	{
		if (!(cache[(((NI) 0))- 0] == obj)) goto LA11_;
		result = NIM_FALSE;
		goto BeforeRet_;
	}
	LA11_: ;
	{
		if (!(cache[(((NI) 1))- 0] == obj)) goto LA15_;
		result = NIM_TRUE;
		goto BeforeRet_;
	}
	LA15_: ;
	result = isObjSlowPath_k9bdq9bQE075AR7scLFt5wIg(obj, subclass, cache);
	goto BeforeRet_;
	}BeforeRet_: ;
	return result;
}

N_LIB_PRIVATE N_NIMCALL(void, suiteStarted_GgW0QiD89cMFXShyPQ8t8qg)(tyObject_OutputFormattercolonObjectType__dLGU9cWWYqlqOn8lpRVsx9cw* formatter, NimStringDesc* suiteName) {
	nimfr_("suiteStarted", "unittest.nim");
	nimln_(157, "unittest.nim");
	chckNilDisp(formatter);
	{
		if (!((formatter) && (isObjWithCache((*formatter).Sup.m_type, (&NTI_kvLOVRX6Za2S0C2QxHXy9cQ_), Nim_OfCheck_CACHE54)))) goto LA3_;
		if (formatter) chckObj((*formatter).Sup.m_type, (&NTI_kvLOVRX6Za2S0C2QxHXy9cQ_));
		suiteStarted_9aAyDoHTMoiLoSiMpkUAFNw(((tyObject_JUnitOutputFormattercolonObjectType__kvLOVRX6Za2S0C2QxHXy9cQ*) (formatter)), suiteName);
	}
	goto LA1_;
	LA3_: ;
	{
		if (!((formatter) && (isObjWithCache((*formatter).Sup.m_type, (&NTI_dU6QGtP3KgqXg9bZP3nhpWw_), Nim_OfCheck_CACHE55)))) goto LA6_;
		if (formatter) chckObj((*formatter).Sup.m_type, (&NTI_dU6QGtP3KgqXg9bZP3nhpWw_));
		suiteStarted_3pDl7sjdCupGLpWwbS2CHg(((tyObject_ConsoleOutputFormattercolonObjectType__dU6QGtP3KgqXg9bZP3nhpWw*) (formatter)), suiteName);
	}
	goto LA1_;
	LA6_: ;
	{
		if (!((formatter) && (isObjWithCache((*formatter).Sup.m_type, (&NTI_dLGU9cWWYqlqOn8lpRVsx9cw_), Nim_OfCheck_CACHE56)))) goto LA9_;
		suiteStarted_zvRCVP5x4ZBpPV2Xx9cPHZA(formatter, suiteName);
	}
	goto LA1_;
	LA9_: ;
	LA1_: ;
	popFrame();
}

N_LIB_PRIVATE N_NIMCALL(void, testStarted_9bXmL9b2zT9aAVv9c8Tm6AvWog)(tyObject_OutputFormattercolonObjectType__dLGU9cWWYqlqOn8lpRVsx9cw* formatter, NimStringDesc* testName) {
	nimfr_("testStarted", "unittest.nim");
	nimln_(159, "unittest.nim");
	chckNilDisp(formatter);
	{
		if (!((formatter) && (isObjWithCache((*formatter).Sup.m_type, (&NTI_kvLOVRX6Za2S0C2QxHXy9cQ_), Nim_OfCheck_CACHE57)))) goto LA3_;
		if (formatter) chckObj((*formatter).Sup.m_type, (&NTI_kvLOVRX6Za2S0C2QxHXy9cQ_));
		testStarted_EYS8dFM0pZmDNdV9c1cyo4Q(((tyObject_JUnitOutputFormattercolonObjectType__kvLOVRX6Za2S0C2QxHXy9cQ*) (formatter)), testName);
	}
	goto LA1_;
	LA3_: ;
	{
		if (!((formatter) && (isObjWithCache((*formatter).Sup.m_type, (&NTI_dU6QGtP3KgqXg9bZP3nhpWw_), Nim_OfCheck_CACHE58)))) goto LA6_;
		if (formatter) chckObj((*formatter).Sup.m_type, (&NTI_dU6QGtP3KgqXg9bZP3nhpWw_));
		testStarted_0WlfvTsMUPRHUfLeuXrGAg(((tyObject_ConsoleOutputFormattercolonObjectType__dU6QGtP3KgqXg9bZP3nhpWw*) (formatter)), testName);
	}
	goto LA1_;
	LA6_: ;
	{
		if (!((formatter) && (isObjWithCache((*formatter).Sup.m_type, (&NTI_dLGU9cWWYqlqOn8lpRVsx9cw_), Nim_OfCheck_CACHE59)))) goto LA9_;
		testStarted_YRuPwQXlDxZko9bSMypk3hA(formatter, testName);
	}
	goto LA1_;
	LA9_: ;
	LA1_: ;
	popFrame();
}

N_LIB_PRIVATE N_NIMCALL(void, failureOccurred_i9ctYnjK2z9bxX9cq0gYct9cIA)(tyObject_OutputFormattercolonObjectType__dLGU9cWWYqlqOn8lpRVsx9cw* formatter, tySequence_sM4lkSb7zS6F7OVMvW9cffQ* checkpoints, NimStringDesc* stackTrace) {
	nimfr_("failureOccurred", "unittest.nim");
	nimln_(161, "unittest.nim");
	chckNilDisp(formatter);
	{
		if (!((formatter) && (isObjWithCache((*formatter).Sup.m_type, (&NTI_kvLOVRX6Za2S0C2QxHXy9cQ_), Nim_OfCheck_CACHE60)))) goto LA3_;
		if (formatter) chckObj((*formatter).Sup.m_type, (&NTI_kvLOVRX6Za2S0C2QxHXy9cQ_));
		failureOccurred_NAlHeCfOfz1bBvtw2rCPGw(((tyObject_JUnitOutputFormattercolonObjectType__kvLOVRX6Za2S0C2QxHXy9cQ*) (formatter)), checkpoints, stackTrace);
	}
	goto LA1_;
	LA3_: ;
	{
		if (!((formatter) && (isObjWithCache((*formatter).Sup.m_type, (&NTI_dU6QGtP3KgqXg9bZP3nhpWw_), Nim_OfCheck_CACHE61)))) goto LA6_;
		if (formatter) chckObj((*formatter).Sup.m_type, (&NTI_dU6QGtP3KgqXg9bZP3nhpWw_));
		failureOccurred_HopmjhtOQil8N9axQ5kNI3w(((tyObject_ConsoleOutputFormattercolonObjectType__dU6QGtP3KgqXg9bZP3nhpWw*) (formatter)), checkpoints, stackTrace);
	}
	goto LA1_;
	LA6_: ;
	{
		if (!((formatter) && (isObjWithCache((*formatter).Sup.m_type, (&NTI_dLGU9cWWYqlqOn8lpRVsx9cw_), Nim_OfCheck_CACHE62)))) goto LA9_;
		failureOccurred_Fsq9aCTSjbGiV7TYpR757Lw(formatter, checkpoints, stackTrace);
	}
	goto LA1_;
	LA9_: ;
	LA1_: ;
	popFrame();
}

N_LIB_PRIVATE N_NIMCALL(void, testEnded_azSnnJ3hAiHHuUdLzViJlw)(tyObject_OutputFormattercolonObjectType__dLGU9cWWYqlqOn8lpRVsx9cw* formatter, tyObject_TestResult_GEvSVSxdPWWgMGM48ywEYQ testResult) {
	nimfr_("testEnded", "unittest.nim");
	nimln_(165, "unittest.nim");
	chckNilDisp(formatter);
	{
		if (!((formatter) && (isObjWithCache((*formatter).Sup.m_type, (&NTI_kvLOVRX6Za2S0C2QxHXy9cQ_), Nim_OfCheck_CACHE63)))) goto LA3_;
		if (formatter) chckObj((*formatter).Sup.m_type, (&NTI_kvLOVRX6Za2S0C2QxHXy9cQ_));
		testEnded_E5f9a05hVCAPvYslPV2f4TQ(((tyObject_JUnitOutputFormattercolonObjectType__kvLOVRX6Za2S0C2QxHXy9cQ*) (formatter)), testResult);
	}
	goto LA1_;
	LA3_: ;
	{
		if (!((formatter) && (isObjWithCache((*formatter).Sup.m_type, (&NTI_dU6QGtP3KgqXg9bZP3nhpWw_), Nim_OfCheck_CACHE64)))) goto LA6_;
		if (formatter) chckObj((*formatter).Sup.m_type, (&NTI_dU6QGtP3KgqXg9bZP3nhpWw_));
		testEnded_fZDr7JVThcpXnuqtgFvwWQ(((tyObject_ConsoleOutputFormattercolonObjectType__dU6QGtP3KgqXg9bZP3nhpWw*) (formatter)), testResult);
	}
	goto LA1_;
	LA6_: ;
	{
		if (!((formatter) && (isObjWithCache((*formatter).Sup.m_type, (&NTI_dLGU9cWWYqlqOn8lpRVsx9cw_), Nim_OfCheck_CACHE65)))) goto LA9_;
		testEnded_hPRwDS9aOIRJ5MB9buAX30Wg(formatter, testResult);
	}
	goto LA1_;
	LA9_: ;
	LA1_: ;
	popFrame();
}

N_LIB_PRIVATE N_NIMCALL(void, suiteEnded_K2O75e2roACICAuYiNImyw)(tyObject_OutputFormattercolonObjectType__dLGU9cWWYqlqOn8lpRVsx9cw* formatter) {
	nimfr_("suiteEnded", "unittest.nim");
	nimln_(167, "unittest.nim");
	chckNilDisp(formatter);
	{
		if (!((formatter) && (isObjWithCache((*formatter).Sup.m_type, (&NTI_kvLOVRX6Za2S0C2QxHXy9cQ_), Nim_OfCheck_CACHE66)))) goto LA3_;
		if (formatter) chckObj((*formatter).Sup.m_type, (&NTI_kvLOVRX6Za2S0C2QxHXy9cQ_));
		suiteEnded_EF53BADEiH9a6amiy7eitMg_2(((tyObject_JUnitOutputFormattercolonObjectType__kvLOVRX6Za2S0C2QxHXy9cQ*) (formatter)));
	}
	goto LA1_;
	LA3_: ;
	{
		if (!((formatter) && (isObjWithCache((*formatter).Sup.m_type, (&NTI_dU6QGtP3KgqXg9bZP3nhpWw_), Nim_OfCheck_CACHE67)))) goto LA6_;
		if (formatter) chckObj((*formatter).Sup.m_type, (&NTI_dU6QGtP3KgqXg9bZP3nhpWw_));
		suiteEnded_IIGQUyJJjT9cNV9c34JPjWGA(((tyObject_ConsoleOutputFormattercolonObjectType__dU6QGtP3KgqXg9bZP3nhpWw*) (formatter)));
	}
	goto LA1_;
	LA6_: ;
	{
		if (!((formatter) && (isObjWithCache((*formatter).Sup.m_type, (&NTI_dLGU9cWWYqlqOn8lpRVsx9cw_), Nim_OfCheck_CACHE68)))) goto LA9_;
		suiteEnded_RS3dEHKAbuhOugXu1dXVHg(formatter);
	}
	goto LA1_;
	LA9_: ;
	LA1_: ;
	popFrame();
}

static N_INLINE(void, initStackBottomWith)(void* locals) {
	setStackBottom(locals);
}
void PreMainInner(void) {
	systemInit000();
	stdlib_macrosDatInit000();
	stdlib_parseutilsDatInit000();
	stdlib_mathDatInit000();
	stdlib_algorithmDatInit000();
	stdlib_strutilsDatInit000();
	stdlib_streamsDatInit000();
	stdlib_posixDatInit000();
	stdlib_timesDatInit000();
	stdlib_hashesDatInit000();
	stdlib_setsDatInit000();
	stdlib_ospathsDatInit000();
	stdlib_osDatInit000();
	stdlib_unicodeDatInit000();
	stdlib_strformatDatInit000();
	stdlib_colorsDatInit000();
	stdlib_tablesDatInit000();
	stdlib_termiosDatInit000();
	stdlib_terminalDatInit000();
	stdlib_unittestDatInit000();
	unknown_helloworldDatInit000();
	helloworld_testDatInit000();
	stdlib_macrosInit000();
	stdlib_parseutilsInit000();
	stdlib_mathInit000();
	stdlib_algorithmInit000();
	stdlib_strutilsInit000();
	stdlib_streamsInit000();
	stdlib_posixInit000();
	stdlib_timesInit000();
	stdlib_hashesInit000();
	stdlib_setsInit000();
	stdlib_ospathsInit000();
	stdlib_osInit000();
	stdlib_unicodeInit000();
	stdlib_strformatInit000();
	stdlib_colorsInit000();
	stdlib_tablesInit000();
	stdlib_termiosInit000();
	stdlib_terminalInit000();
	stdlib_unittestInit000();
	unknown_helloworldInit000();
}

void PreMain(void) {
	void (*volatile inner)(void);
	systemDatInit000();
	inner = PreMainInner;
	initStackBottomWith((void *)&inner);
	(*inner)();
}

int cmdCount;
char** cmdLine;
char** gEnv;
N_CDECL(void, NimMainInner)(void) {
	NimMainModule();
}

N_CDECL(void, NimMain)(void) {
	void (*volatile inner)(void);
	PreMain();
	inner = NimMainInner;
	initStackBottomWith((void *)&inner);
	(*inner)();
}

int main(int argc, char** args, char** env) {
	cmdLine = args;
	cmdCount = argc;
	gEnv = env;
	NimMain();
	return nim_program_result;
}

NIM_EXTERNC N_NOINLINE(void, NimMainModule)(void) {
	nimfr_("helloworld_test", "helloworld_test.nim");
nimRegisterGlobalMarker(TM_4qp2gZX9anqPB0kpcB8Cugw_4);
nimRegisterGlobalMarker(TM_4qp2gZX9anqPB0kpcB8Cugw_8);
nimRegisterGlobalMarker(TM_4qp2gZX9anqPB0kpcB8Cugw_13);
nimRegisterGlobalMarker(TM_4qp2gZX9anqPB0kpcB8Cugw_16);
nimRegisterGlobalMarker(TM_4qp2gZX9anqPB0kpcB8Cugw_17);
nimRegisterGlobalMarker(TM_4qp2gZX9anqPB0kpcB8Cugw_20);
nimRegisterGlobalMarker(TM_4qp2gZX9anqPB0kpcB8Cugw_22);
nimRegisterGlobalMarker(TM_4qp2gZX9anqPB0kpcB8Cugw_25);
nimRegisterGlobalMarker(TM_4qp2gZX9anqPB0kpcB8Cugw_30);
nimRegisterGlobalMarker(TM_4qp2gZX9anqPB0kpcB8Cugw_32);
nimRegisterGlobalMarker(TM_4qp2gZX9anqPB0kpcB8Cugw_33);
nimRegisterGlobalMarker(TM_4qp2gZX9anqPB0kpcB8Cugw_36);
nimRegisterGlobalMarker(TM_4qp2gZX9anqPB0kpcB8Cugw_38);
nimRegisterGlobalMarker(TM_4qp2gZX9anqPB0kpcB8Cugw_41);
nimRegisterGlobalMarker(TM_4qp2gZX9anqPB0kpcB8Cugw_46);
nimRegisterGlobalMarker(TM_4qp2gZX9anqPB0kpcB8Cugw_48);
nimRegisterGlobalMarker(TM_4qp2gZX9anqPB0kpcB8Cugw_49);
nimRegisterGlobalMarker(TM_4qp2gZX9anqPB0kpcB8Cugw_52);
	nimln_(465, "unittest.nim");
	ensureInitialized_8zybqvexf9aYkm9bmgyU3eLg();
	nimln_(5, "helloworld_test.nim");
	{
		NIM_BOOL T3_;
		TSafePoint TM_4qp2gZX9anqPB0kpcB8Cugw_7;
		nimln_(467, "unittest.nim");
		T3_ = (NIM_BOOL)0;
		T3_ = shouldRun_LgAPGDTu4rkb7Tq9asAgd9cQ(((NimStringDesc*) &TM_4qp2gZX9anqPB0kpcB8Cugw_2), ((NimStringDesc*) &TM_4qp2gZX9anqPB0kpcB8Cugw_3));
		if (!T3_) goto LA4_;
		nimln_(468, "unittest.nim");
		if (checkpoints_bq5hLRYOyiTcYy29a9akD9c9bQ) { nimGCunrefNoCycle(checkpoints_bq5hLRYOyiTcYy29a9akD9c9bQ); checkpoints_bq5hLRYOyiTcYy29a9akD9c9bQ = NIM_NIL; }
		checkpoints_bq5hLRYOyiTcYy29a9akD9c9bQ = (tySequence_sM4lkSb7zS6F7OVMvW9cffQ*) newSeqRC1((&NTI_sM4lkSb7zS6F7OVMvW9cffQ_), 0);
		nimln_(469, "unittest.nim");
		testStatusIMPL_Q4qcz3YlFyWrLneTJlsS4Q = ((tyEnum_TestStatus_W9bTUg9c9a7UlIYkKYmd5uasQ) 0);
		{
			NI i;
			NI L;
			NI T7_;
			nimln_(3805, "system.nim");
			i = ((NI) 0);
			nimln_(3806, "system.nim");
			T7_ = (formatters_55U7g4zhjHV9bCI6emTgDiA ? formatters_55U7g4zhjHV9bCI6emTgDiA->Sup.len : 0);
			L = T7_;
			{
				nimln_(3807, "system.nim");
				while (1) {
					NI TM_4qp2gZX9anqPB0kpcB8Cugw_5;
					if (!(i < L)) goto LA9;
					nimln_(3808, "system.nim");
					if ((NU)(i) >= (NU)(formatters_55U7g4zhjHV9bCI6emTgDiA->Sup.len)) raiseIndexError();
					asgnRef((void**) (&formatter_6vZ0eCyziJIpjOJxE6ZZSA), formatters_55U7g4zhjHV9bCI6emTgDiA->data[i]);
					nimln_(472, "unittest.nim");
					testStarted_9bXmL9b2zT9aAVv9c8Tm6AvWog(formatter_6vZ0eCyziJIpjOJxE6ZZSA, ((NimStringDesc*) &TM_4qp2gZX9anqPB0kpcB8Cugw_3));
					nimln_(3809, "system.nim");
					TM_4qp2gZX9anqPB0kpcB8Cugw_5 = addInt(i, ((NI) 1));
					i = (NI)(TM_4qp2gZX9anqPB0kpcB8Cugw_5);
					nimln_(3810, "system.nim");
					{
						NI T12_;
						T12_ = (formatters_55U7g4zhjHV9bCI6emTgDiA ? formatters_55U7g4zhjHV9bCI6emTgDiA->Sup.len : 0);
						if (!!((T12_ == L))) goto LA13_;
						failedAssertImpl_aDmpBTs9cPuXp0Mp9cfiNeyA(((NimStringDesc*) &TM_4qp2gZX9anqPB0kpcB8Cugw_6));
					}
					LA13_: ;
				} LA9: ;
			}
		}
		nimln_(474, "unittest.nim");
		pushSafePoint(&TM_4qp2gZX9anqPB0kpcB8Cugw_7);
		TM_4qp2gZX9anqPB0kpcB8Cugw_7.status = _setjmp(TM_4qp2gZX9anqPB0kpcB8Cugw_7.context);
		if (TM_4qp2gZX9anqPB0kpcB8Cugw_7.status == 0) {
			{
				nimln_(583, "unittest.nim");
				asgnRefNoCycle((void**) (&colonc1__WzG62vRKCCCuEmzM9bJ2gjA), helloworld_gsKQNDh3DKS9bk2U4dhinhw(((NimStringDesc*) &TM_4qp2gZX9anqPB0kpcB8Cugw_9)));
				nimln_(636, "unittest.nim");
				{
					NimStringDesc* T21_;
					nimln_(633, "unittest.nim");
					nimln_(612, "unittest.nim");
					if (!!(eqStrings(colonc1__WzG62vRKCCCuEmzM9bJ2gjA, ((NimStringDesc*) &TM_4qp2gZX9anqPB0kpcB8Cugw_10)))) goto LA19_;
					nimln_(637, "unittest.nim");
					checkpoint_4nBz3prx9cKVVOoTZb4rNCQ(((NimStringDesc*) &TM_4qp2gZX9anqPB0kpcB8Cugw_11));
					nimln_(588, "unittest.nim");
					T21_ = (NimStringDesc*)0;
					nimln_(612, "unittest.nim");
					T21_ = rawNewString(colonc1__WzG62vRKCCCuEmzM9bJ2gjA->Sup.len + 17);
appendString(T21_, ((NimStringDesc*) &TM_4qp2gZX9anqPB0kpcB8Cugw_12));
appendString(T21_, colonc1__WzG62vRKCCCuEmzM9bJ2gjA);
					checkpoint_4nBz3prx9cKVVOoTZb4rNCQ(T21_);
					nimln_(529, "unittest.nim");
					testStatusIMPL_Q4qcz3YlFyWrLneTJlsS4Q = ((tyEnum_TestStatus_W9bTUg9c9a7UlIYkKYmd5uasQ) 1);
					nimln_(533, "unittest.nim");
					ensureInitialized_8zybqvexf9aYkm9bmgyU3eLg();
					{
						NI volatile i_2;
						NI L_2;
						NI T23_;
						nimln_(3805, "system.nim");
						i_2 = ((NI) 0);
						nimln_(3806, "system.nim");
						T23_ = (formatters_55U7g4zhjHV9bCI6emTgDiA ? formatters_55U7g4zhjHV9bCI6emTgDiA->Sup.len : 0);
						L_2 = T23_;
						{
							nimln_(3807, "system.nim");
							while (1) {
								NI TM_4qp2gZX9anqPB0kpcB8Cugw_14;
								if (!(i_2 < L_2)) goto LA25;
								nimln_(3808, "system.nim");
								if ((NU)(i_2) >= (NU)(formatters_55U7g4zhjHV9bCI6emTgDiA->Sup.len)) raiseIndexError();
								asgnRef((void**) (&formatter_6vZ0eCyziJIpjOJxE6ZZSA_2), formatters_55U7g4zhjHV9bCI6emTgDiA->data[i_2]);
								nimln_(540, "unittest.nim");
								failureOccurred_i9ctYnjK2z9bxX9cq0gYct9cIA(formatter_6vZ0eCyziJIpjOJxE6ZZSA_2, checkpoints_bq5hLRYOyiTcYy29a9akD9c9bQ, NIM_NIL);
								nimln_(3809, "system.nim");
								TM_4qp2gZX9anqPB0kpcB8Cugw_14 = addInt(i_2, ((NI) 1));
								i_2 = (NI)(TM_4qp2gZX9anqPB0kpcB8Cugw_14);
								nimln_(3810, "system.nim");
								{
									NI T28_;
									T28_ = (formatters_55U7g4zhjHV9bCI6emTgDiA ? formatters_55U7g4zhjHV9bCI6emTgDiA->Sup.len : 0);
									if (!!((T28_ == L_2))) goto LA29_;
									failedAssertImpl_aDmpBTs9cPuXp0Mp9cfiNeyA(((NimStringDesc*) &TM_4qp2gZX9anqPB0kpcB8Cugw_6));
								}
								LA29_: ;
							} LA25: ;
						}
					}
					nimln_(543, "unittest.nim");
					{
						if (!abortOnError_Bte3Uiwc4Q19ago2N4C89cUA) goto LA33_;
						exit(nim_program_result);
					}
					LA33_: ;
					nimln_(545, "unittest.nim");
					if (checkpoints_bq5hLRYOyiTcYy29a9akD9c9bQ) { nimGCunrefNoCycle(checkpoints_bq5hLRYOyiTcYy29a9akD9c9bQ); checkpoints_bq5hLRYOyiTcYy29a9akD9c9bQ = NIM_NIL; }
					checkpoints_bq5hLRYOyiTcYy29a9akD9c9bQ = (tySequence_sM4lkSb7zS6F7OVMvW9cffQ*) newSeqRC1((&NTI_sM4lkSb7zS6F7OVMvW9cffQ_), 0);
				}
				LA19_: ;
			}
			popSafePoint();
		}
		else {
			popSafePoint();
			setFrame((TFrame*)&FR_);
			{
				NimStringDesc* T37_;
				NimStringDesc* T38_;
				Exception* T39_;
				TM_4qp2gZX9anqPB0kpcB8Cugw_7.status = 0;
				nimln_(482, "unittest.nim");
				T37_ = (NimStringDesc*)0;
				T38_ = (NimStringDesc*)0;
				T38_ = getCurrentExceptionMsg_fOe1OXzHoGbgrd7IEmbp5Qsystem();
				T37_ = rawNewString(T38_->Sup.len + 21);
appendString(T37_, ((NimStringDesc*) &TM_4qp2gZX9anqPB0kpcB8Cugw_15));
appendString(T37_, T38_);
				checkpoint_4nBz3prx9cKVVOoTZb4rNCQ(T37_);
				nimln_(483, "unittest.nim");
				T39_ = (Exception*)0;
				T39_ = getCurrentException();
				asgnRefNoCycle((void**) (&stackTrace_yo79audNUOaALqoPY6lz8tQ), getStackTrace_OenGRUrwbq9c3AFUxAFv9cuA(T39_));
				nimln_(529, "unittest.nim");
				testStatusIMPL_Q4qcz3YlFyWrLneTJlsS4Q = ((tyEnum_TestStatus_W9bTUg9c9a7UlIYkKYmd5uasQ) 1);
				nimln_(533, "unittest.nim");
				ensureInitialized_8zybqvexf9aYkm9bmgyU3eLg();
				{
					NI i_3;
					NI L_3;
					NI T41_;
					nimln_(3805, "system.nim");
					i_3 = ((NI) 0);
					nimln_(3806, "system.nim");
					T41_ = (formatters_55U7g4zhjHV9bCI6emTgDiA ? formatters_55U7g4zhjHV9bCI6emTgDiA->Sup.len : 0);
					L_3 = T41_;
					{
						nimln_(3807, "system.nim");
						while (1) {
							NI TM_4qp2gZX9anqPB0kpcB8Cugw_18;
							if (!(i_3 < L_3)) goto LA43;
							nimln_(3808, "system.nim");
							if ((NU)(i_3) >= (NU)(formatters_55U7g4zhjHV9bCI6emTgDiA->Sup.len)) raiseIndexError();
							asgnRef((void**) (&formatter_6vZ0eCyziJIpjOJxE6ZZSA_3), formatters_55U7g4zhjHV9bCI6emTgDiA->data[i_3]);
							nimln_(538, "unittest.nim");
							failureOccurred_i9ctYnjK2z9bxX9cq0gYct9cIA(formatter_6vZ0eCyziJIpjOJxE6ZZSA_3, checkpoints_bq5hLRYOyiTcYy29a9akD9c9bQ, stackTrace_yo79audNUOaALqoPY6lz8tQ);
							nimln_(3809, "system.nim");
							TM_4qp2gZX9anqPB0kpcB8Cugw_18 = addInt(i_3, ((NI) 1));
							i_3 = (NI)(TM_4qp2gZX9anqPB0kpcB8Cugw_18);
							nimln_(3810, "system.nim");
							{
								NI T46_;
								T46_ = (formatters_55U7g4zhjHV9bCI6emTgDiA ? formatters_55U7g4zhjHV9bCI6emTgDiA->Sup.len : 0);
								if (!!((T46_ == L_3))) goto LA47_;
								failedAssertImpl_aDmpBTs9cPuXp0Mp9cfiNeyA(((NimStringDesc*) &TM_4qp2gZX9anqPB0kpcB8Cugw_6));
							}
							LA47_: ;
						} LA43: ;
					}
				}
				nimln_(543, "unittest.nim");
				{
					if (!abortOnError_Bte3Uiwc4Q19ago2N4C89cUA) goto LA51_;
					exit(nim_program_result);
				}
				LA51_: ;
				nimln_(545, "unittest.nim");
				if (checkpoints_bq5hLRYOyiTcYy29a9akD9c9bQ) { nimGCunrefNoCycle(checkpoints_bq5hLRYOyiTcYy29a9akD9c9bQ); checkpoints_bq5hLRYOyiTcYy29a9akD9c9bQ = NIM_NIL; }
				checkpoints_bq5hLRYOyiTcYy29a9akD9c9bQ = (tySequence_sM4lkSb7zS6F7OVMvW9cffQ*) newSeqRC1((&NTI_sM4lkSb7zS6F7OVMvW9cffQ_), 0);
				popCurrentException();
			}
		}
		{
			NimStringDesc* T58_;
			NimStringDesc* T59_;
			nimln_(487, "unittest.nim");
			{
				NI TM_4qp2gZX9anqPB0kpcB8Cugw_19;
				if (!(testStatusIMPL_Q4qcz3YlFyWrLneTJlsS4Q == ((tyEnum_TestStatus_W9bTUg9c9a7UlIYkKYmd5uasQ) 1))) goto LA56_;
				nimln_(488, "unittest.nim");
				TM_4qp2gZX9anqPB0kpcB8Cugw_19 = addInt(nim_program_result, ((NI) 1));
				nim_program_result = (NI)(TM_4qp2gZX9anqPB0kpcB8Cugw_19);
			}
			LA56_: ;
			nimln_(489, "unittest.nim");
			chckNil((void*)(&testResult_zKJcLcg3TmFPRC7R7c9cT9bg));
			genericReset((void*)(&testResult_zKJcLcg3TmFPRC7R7c9cT9bg), (&NTI_GEvSVSxdPWWgMGM48ywEYQ_));
			T58_ = (NimStringDesc*)0;
			T58_ = testResult_zKJcLcg3TmFPRC7R7c9cT9bg.suiteName; testResult_zKJcLcg3TmFPRC7R7c9cT9bg.suiteName = copyStringRC1(NIM_NIL);
			if (T58_) nimGCunrefNoCycle(T58_);
			T59_ = (NimStringDesc*)0;
			T59_ = testResult_zKJcLcg3TmFPRC7R7c9cT9bg.testName; testResult_zKJcLcg3TmFPRC7R7c9cT9bg.testName = copyStringRC1(((NimStringDesc*) &TM_4qp2gZX9anqPB0kpcB8Cugw_3));
			if (T59_) nimGCunrefNoCycle(T59_);
			testResult_zKJcLcg3TmFPRC7R7c9cT9bg.status = testStatusIMPL_Q4qcz3YlFyWrLneTJlsS4Q;
			nimln_(494, "unittest.nim");
			testEnded_xoIS1BdhYWQ6hhMP22XXiw(testResult_zKJcLcg3TmFPRC7R7c9cT9bg);
			nimln_(495, "unittest.nim");
			if (checkpoints_bq5hLRYOyiTcYy29a9akD9c9bQ) { nimGCunrefNoCycle(checkpoints_bq5hLRYOyiTcYy29a9akD9c9bQ); checkpoints_bq5hLRYOyiTcYy29a9akD9c9bQ = NIM_NIL; }
			checkpoints_bq5hLRYOyiTcYy29a9akD9c9bQ = (tySequence_sM4lkSb7zS6F7OVMvW9cffQ*) newSeqRC1((&NTI_sM4lkSb7zS6F7OVMvW9cffQ_), 0);
		}
		if (TM_4qp2gZX9anqPB0kpcB8Cugw_7.status != 0) reraiseException();
	}
	LA4_: ;
	nimln_(465, "unittest.nim");
	ensureInitialized_8zybqvexf9aYkm9bmgyU3eLg();
	nimln_(8, "helloworld_test.nim");
	{
		NIM_BOOL T62_;
		TSafePoint TM_4qp2gZX9anqPB0kpcB8Cugw_24;
		nimln_(467, "unittest.nim");
		T62_ = (NIM_BOOL)0;
		T62_ = shouldRun_LgAPGDTu4rkb7Tq9asAgd9cQ(((NimStringDesc*) &TM_4qp2gZX9anqPB0kpcB8Cugw_2), ((NimStringDesc*) &TM_4qp2gZX9anqPB0kpcB8Cugw_21));
		if (!T62_) goto LA63_;
		nimln_(468, "unittest.nim");
		if (checkpoints_bq5hLRYOyiTcYy29a9akD9c9bQ) { nimGCunrefNoCycle(checkpoints_bq5hLRYOyiTcYy29a9akD9c9bQ); checkpoints_bq5hLRYOyiTcYy29a9akD9c9bQ = NIM_NIL; }
		checkpoints_bq5hLRYOyiTcYy29a9akD9c9bQ = (tySequence_sM4lkSb7zS6F7OVMvW9cffQ*) newSeqRC1((&NTI_sM4lkSb7zS6F7OVMvW9cffQ_), 0);
		nimln_(469, "unittest.nim");
		testStatusIMPL_Q4qcz3YlFyWrLneTJlsS4Q_2 = ((tyEnum_TestStatus_W9bTUg9c9a7UlIYkKYmd5uasQ) 0);
		{
			NI i_4;
			NI L_4;
			NI T66_;
			nimln_(3805, "system.nim");
			i_4 = ((NI) 0);
			nimln_(3806, "system.nim");
			T66_ = (formatters_55U7g4zhjHV9bCI6emTgDiA ? formatters_55U7g4zhjHV9bCI6emTgDiA->Sup.len : 0);
			L_4 = T66_;
			{
				nimln_(3807, "system.nim");
				while (1) {
					NI TM_4qp2gZX9anqPB0kpcB8Cugw_23;
					if (!(i_4 < L_4)) goto LA68;
					nimln_(3808, "system.nim");
					if ((NU)(i_4) >= (NU)(formatters_55U7g4zhjHV9bCI6emTgDiA->Sup.len)) raiseIndexError();
					asgnRef((void**) (&formatter_6vZ0eCyziJIpjOJxE6ZZSA_4), formatters_55U7g4zhjHV9bCI6emTgDiA->data[i_4]);
					nimln_(472, "unittest.nim");
					testStarted_9bXmL9b2zT9aAVv9c8Tm6AvWog(formatter_6vZ0eCyziJIpjOJxE6ZZSA_4, ((NimStringDesc*) &TM_4qp2gZX9anqPB0kpcB8Cugw_21));
					nimln_(3809, "system.nim");
					TM_4qp2gZX9anqPB0kpcB8Cugw_23 = addInt(i_4, ((NI) 1));
					i_4 = (NI)(TM_4qp2gZX9anqPB0kpcB8Cugw_23);
					nimln_(3810, "system.nim");
					{
						NI T71_;
						T71_ = (formatters_55U7g4zhjHV9bCI6emTgDiA ? formatters_55U7g4zhjHV9bCI6emTgDiA->Sup.len : 0);
						if (!!((T71_ == L_4))) goto LA72_;
						failedAssertImpl_aDmpBTs9cPuXp0Mp9cfiNeyA(((NimStringDesc*) &TM_4qp2gZX9anqPB0kpcB8Cugw_6));
					}
					LA72_: ;
				} LA68: ;
			}
		}
		nimln_(474, "unittest.nim");
		pushSafePoint(&TM_4qp2gZX9anqPB0kpcB8Cugw_24);
		TM_4qp2gZX9anqPB0kpcB8Cugw_24.status = _setjmp(TM_4qp2gZX9anqPB0kpcB8Cugw_24.context);
		if (TM_4qp2gZX9anqPB0kpcB8Cugw_24.status == 0) {
			{
				nimln_(583, "unittest.nim");
				asgnRefNoCycle((void**) (&colonc1__WzG62vRKCCCuEmzM9bJ2gjA_2), helloworld_gsKQNDh3DKS9bk2U4dhinhw(((NimStringDesc*) &TM_4qp2gZX9anqPB0kpcB8Cugw_26)));
				nimln_(636, "unittest.nim");
				{
					NimStringDesc* T80_;
					nimln_(633, "unittest.nim");
					nimln_(612, "unittest.nim");
					if (!!(eqStrings(colonc1__WzG62vRKCCCuEmzM9bJ2gjA_2, ((NimStringDesc*) &TM_4qp2gZX9anqPB0kpcB8Cugw_27)))) goto LA78_;
					nimln_(637, "unittest.nim");
					checkpoint_4nBz3prx9cKVVOoTZb4rNCQ(((NimStringDesc*) &TM_4qp2gZX9anqPB0kpcB8Cugw_28));
					nimln_(588, "unittest.nim");
					T80_ = (NimStringDesc*)0;
					nimln_(612, "unittest.nim");
					T80_ = rawNewString(colonc1__WzG62vRKCCCuEmzM9bJ2gjA_2->Sup.len + 24);
appendString(T80_, ((NimStringDesc*) &TM_4qp2gZX9anqPB0kpcB8Cugw_29));
appendString(T80_, colonc1__WzG62vRKCCCuEmzM9bJ2gjA_2);
					checkpoint_4nBz3prx9cKVVOoTZb4rNCQ(T80_);
					nimln_(529, "unittest.nim");
					testStatusIMPL_Q4qcz3YlFyWrLneTJlsS4Q_2 = ((tyEnum_TestStatus_W9bTUg9c9a7UlIYkKYmd5uasQ) 1);
					nimln_(533, "unittest.nim");
					ensureInitialized_8zybqvexf9aYkm9bmgyU3eLg();
					{
						NI volatile i_5;
						NI L_5;
						NI T82_;
						nimln_(3805, "system.nim");
						i_5 = ((NI) 0);
						nimln_(3806, "system.nim");
						T82_ = (formatters_55U7g4zhjHV9bCI6emTgDiA ? formatters_55U7g4zhjHV9bCI6emTgDiA->Sup.len : 0);
						L_5 = T82_;
						{
							nimln_(3807, "system.nim");
							while (1) {
								NI TM_4qp2gZX9anqPB0kpcB8Cugw_31;
								if (!(i_5 < L_5)) goto LA84;
								nimln_(3808, "system.nim");
								if ((NU)(i_5) >= (NU)(formatters_55U7g4zhjHV9bCI6emTgDiA->Sup.len)) raiseIndexError();
								asgnRef((void**) (&formatter_6vZ0eCyziJIpjOJxE6ZZSA_5), formatters_55U7g4zhjHV9bCI6emTgDiA->data[i_5]);
								nimln_(540, "unittest.nim");
								failureOccurred_i9ctYnjK2z9bxX9cq0gYct9cIA(formatter_6vZ0eCyziJIpjOJxE6ZZSA_5, checkpoints_bq5hLRYOyiTcYy29a9akD9c9bQ, NIM_NIL);
								nimln_(3809, "system.nim");
								TM_4qp2gZX9anqPB0kpcB8Cugw_31 = addInt(i_5, ((NI) 1));
								i_5 = (NI)(TM_4qp2gZX9anqPB0kpcB8Cugw_31);
								nimln_(3810, "system.nim");
								{
									NI T87_;
									T87_ = (formatters_55U7g4zhjHV9bCI6emTgDiA ? formatters_55U7g4zhjHV9bCI6emTgDiA->Sup.len : 0);
									if (!!((T87_ == L_5))) goto LA88_;
									failedAssertImpl_aDmpBTs9cPuXp0Mp9cfiNeyA(((NimStringDesc*) &TM_4qp2gZX9anqPB0kpcB8Cugw_6));
								}
								LA88_: ;
							} LA84: ;
						}
					}
					nimln_(543, "unittest.nim");
					{
						if (!abortOnError_Bte3Uiwc4Q19ago2N4C89cUA) goto LA92_;
						exit(nim_program_result);
					}
					LA92_: ;
					nimln_(545, "unittest.nim");
					if (checkpoints_bq5hLRYOyiTcYy29a9akD9c9bQ) { nimGCunrefNoCycle(checkpoints_bq5hLRYOyiTcYy29a9akD9c9bQ); checkpoints_bq5hLRYOyiTcYy29a9akD9c9bQ = NIM_NIL; }
					checkpoints_bq5hLRYOyiTcYy29a9akD9c9bQ = (tySequence_sM4lkSb7zS6F7OVMvW9cffQ*) newSeqRC1((&NTI_sM4lkSb7zS6F7OVMvW9cffQ_), 0);
				}
				LA78_: ;
			}
			popSafePoint();
		}
		else {
			popSafePoint();
			setFrame((TFrame*)&FR_);
			{
				NimStringDesc* T96_;
				NimStringDesc* T97_;
				Exception* T98_;
				TM_4qp2gZX9anqPB0kpcB8Cugw_24.status = 0;
				nimln_(482, "unittest.nim");
				T96_ = (NimStringDesc*)0;
				T97_ = (NimStringDesc*)0;
				T97_ = getCurrentExceptionMsg_fOe1OXzHoGbgrd7IEmbp5Qsystem();
				T96_ = rawNewString(T97_->Sup.len + 21);
appendString(T96_, ((NimStringDesc*) &TM_4qp2gZX9anqPB0kpcB8Cugw_15));
appendString(T96_, T97_);
				checkpoint_4nBz3prx9cKVVOoTZb4rNCQ(T96_);
				nimln_(483, "unittest.nim");
				T98_ = (Exception*)0;
				T98_ = getCurrentException();
				asgnRefNoCycle((void**) (&stackTrace_yo79audNUOaALqoPY6lz8tQ_2), getStackTrace_OenGRUrwbq9c3AFUxAFv9cuA(T98_));
				nimln_(529, "unittest.nim");
				testStatusIMPL_Q4qcz3YlFyWrLneTJlsS4Q_2 = ((tyEnum_TestStatus_W9bTUg9c9a7UlIYkKYmd5uasQ) 1);
				nimln_(533, "unittest.nim");
				ensureInitialized_8zybqvexf9aYkm9bmgyU3eLg();
				{
					NI i_6;
					NI L_6;
					NI T100_;
					nimln_(3805, "system.nim");
					i_6 = ((NI) 0);
					nimln_(3806, "system.nim");
					T100_ = (formatters_55U7g4zhjHV9bCI6emTgDiA ? formatters_55U7g4zhjHV9bCI6emTgDiA->Sup.len : 0);
					L_6 = T100_;
					{
						nimln_(3807, "system.nim");
						while (1) {
							NI TM_4qp2gZX9anqPB0kpcB8Cugw_34;
							if (!(i_6 < L_6)) goto LA102;
							nimln_(3808, "system.nim");
							if ((NU)(i_6) >= (NU)(formatters_55U7g4zhjHV9bCI6emTgDiA->Sup.len)) raiseIndexError();
							asgnRef((void**) (&formatter_6vZ0eCyziJIpjOJxE6ZZSA_6), formatters_55U7g4zhjHV9bCI6emTgDiA->data[i_6]);
							nimln_(538, "unittest.nim");
							failureOccurred_i9ctYnjK2z9bxX9cq0gYct9cIA(formatter_6vZ0eCyziJIpjOJxE6ZZSA_6, checkpoints_bq5hLRYOyiTcYy29a9akD9c9bQ, stackTrace_yo79audNUOaALqoPY6lz8tQ_2);
							nimln_(3809, "system.nim");
							TM_4qp2gZX9anqPB0kpcB8Cugw_34 = addInt(i_6, ((NI) 1));
							i_6 = (NI)(TM_4qp2gZX9anqPB0kpcB8Cugw_34);
							nimln_(3810, "system.nim");
							{
								NI T105_;
								T105_ = (formatters_55U7g4zhjHV9bCI6emTgDiA ? formatters_55U7g4zhjHV9bCI6emTgDiA->Sup.len : 0);
								if (!!((T105_ == L_6))) goto LA106_;
								failedAssertImpl_aDmpBTs9cPuXp0Mp9cfiNeyA(((NimStringDesc*) &TM_4qp2gZX9anqPB0kpcB8Cugw_6));
							}
							LA106_: ;
						} LA102: ;
					}
				}
				nimln_(543, "unittest.nim");
				{
					if (!abortOnError_Bte3Uiwc4Q19ago2N4C89cUA) goto LA110_;
					exit(nim_program_result);
				}
				LA110_: ;
				nimln_(545, "unittest.nim");
				if (checkpoints_bq5hLRYOyiTcYy29a9akD9c9bQ) { nimGCunrefNoCycle(checkpoints_bq5hLRYOyiTcYy29a9akD9c9bQ); checkpoints_bq5hLRYOyiTcYy29a9akD9c9bQ = NIM_NIL; }
				checkpoints_bq5hLRYOyiTcYy29a9akD9c9bQ = (tySequence_sM4lkSb7zS6F7OVMvW9cffQ*) newSeqRC1((&NTI_sM4lkSb7zS6F7OVMvW9cffQ_), 0);
				popCurrentException();
			}
		}
		{
			NimStringDesc* T117_;
			NimStringDesc* T118_;
			nimln_(487, "unittest.nim");
			{
				NI TM_4qp2gZX9anqPB0kpcB8Cugw_35;
				if (!(testStatusIMPL_Q4qcz3YlFyWrLneTJlsS4Q_2 == ((tyEnum_TestStatus_W9bTUg9c9a7UlIYkKYmd5uasQ) 1))) goto LA115_;
				nimln_(488, "unittest.nim");
				TM_4qp2gZX9anqPB0kpcB8Cugw_35 = addInt(nim_program_result, ((NI) 1));
				nim_program_result = (NI)(TM_4qp2gZX9anqPB0kpcB8Cugw_35);
			}
			LA115_: ;
			nimln_(489, "unittest.nim");
			chckNil((void*)(&testResult_zKJcLcg3TmFPRC7R7c9cT9bg_2));
			genericReset((void*)(&testResult_zKJcLcg3TmFPRC7R7c9cT9bg_2), (&NTI_GEvSVSxdPWWgMGM48ywEYQ_));
			T117_ = (NimStringDesc*)0;
			T117_ = testResult_zKJcLcg3TmFPRC7R7c9cT9bg_2.suiteName; testResult_zKJcLcg3TmFPRC7R7c9cT9bg_2.suiteName = copyStringRC1(NIM_NIL);
			if (T117_) nimGCunrefNoCycle(T117_);
			T118_ = (NimStringDesc*)0;
			T118_ = testResult_zKJcLcg3TmFPRC7R7c9cT9bg_2.testName; testResult_zKJcLcg3TmFPRC7R7c9cT9bg_2.testName = copyStringRC1(((NimStringDesc*) &TM_4qp2gZX9anqPB0kpcB8Cugw_21));
			if (T118_) nimGCunrefNoCycle(T118_);
			testResult_zKJcLcg3TmFPRC7R7c9cT9bg_2.status = testStatusIMPL_Q4qcz3YlFyWrLneTJlsS4Q_2;
			nimln_(494, "unittest.nim");
			testEnded_xoIS1BdhYWQ6hhMP22XXiw(testResult_zKJcLcg3TmFPRC7R7c9cT9bg_2);
			nimln_(495, "unittest.nim");
			if (checkpoints_bq5hLRYOyiTcYy29a9akD9c9bQ) { nimGCunrefNoCycle(checkpoints_bq5hLRYOyiTcYy29a9akD9c9bQ); checkpoints_bq5hLRYOyiTcYy29a9akD9c9bQ = NIM_NIL; }
			checkpoints_bq5hLRYOyiTcYy29a9akD9c9bQ = (tySequence_sM4lkSb7zS6F7OVMvW9cffQ*) newSeqRC1((&NTI_sM4lkSb7zS6F7OVMvW9cffQ_), 0);
		}
		if (TM_4qp2gZX9anqPB0kpcB8Cugw_24.status != 0) reraiseException();
	}
	LA63_: ;
	nimln_(465, "unittest.nim");
	ensureInitialized_8zybqvexf9aYkm9bmgyU3eLg();
	nimln_(11, "helloworld_test.nim");
	{
		NIM_BOOL T121_;
		TSafePoint TM_4qp2gZX9anqPB0kpcB8Cugw_40;
		nimln_(467, "unittest.nim");
		T121_ = (NIM_BOOL)0;
		T121_ = shouldRun_LgAPGDTu4rkb7Tq9asAgd9cQ(((NimStringDesc*) &TM_4qp2gZX9anqPB0kpcB8Cugw_2), ((NimStringDesc*) &TM_4qp2gZX9anqPB0kpcB8Cugw_37));
		if (!T121_) goto LA122_;
		nimln_(468, "unittest.nim");
		if (checkpoints_bq5hLRYOyiTcYy29a9akD9c9bQ) { nimGCunrefNoCycle(checkpoints_bq5hLRYOyiTcYy29a9akD9c9bQ); checkpoints_bq5hLRYOyiTcYy29a9akD9c9bQ = NIM_NIL; }
		checkpoints_bq5hLRYOyiTcYy29a9akD9c9bQ = (tySequence_sM4lkSb7zS6F7OVMvW9cffQ*) newSeqRC1((&NTI_sM4lkSb7zS6F7OVMvW9cffQ_), 0);
		nimln_(469, "unittest.nim");
		testStatusIMPL_Q4qcz3YlFyWrLneTJlsS4Q_3 = ((tyEnum_TestStatus_W9bTUg9c9a7UlIYkKYmd5uasQ) 0);
		{
			NI i_7;
			NI L_7;
			NI T125_;
			nimln_(3805, "system.nim");
			i_7 = ((NI) 0);
			nimln_(3806, "system.nim");
			T125_ = (formatters_55U7g4zhjHV9bCI6emTgDiA ? formatters_55U7g4zhjHV9bCI6emTgDiA->Sup.len : 0);
			L_7 = T125_;
			{
				nimln_(3807, "system.nim");
				while (1) {
					NI TM_4qp2gZX9anqPB0kpcB8Cugw_39;
					if (!(i_7 < L_7)) goto LA127;
					nimln_(3808, "system.nim");
					if ((NU)(i_7) >= (NU)(formatters_55U7g4zhjHV9bCI6emTgDiA->Sup.len)) raiseIndexError();
					asgnRef((void**) (&formatter_6vZ0eCyziJIpjOJxE6ZZSA_7), formatters_55U7g4zhjHV9bCI6emTgDiA->data[i_7]);
					nimln_(472, "unittest.nim");
					testStarted_9bXmL9b2zT9aAVv9c8Tm6AvWog(formatter_6vZ0eCyziJIpjOJxE6ZZSA_7, ((NimStringDesc*) &TM_4qp2gZX9anqPB0kpcB8Cugw_37));
					nimln_(3809, "system.nim");
					TM_4qp2gZX9anqPB0kpcB8Cugw_39 = addInt(i_7, ((NI) 1));
					i_7 = (NI)(TM_4qp2gZX9anqPB0kpcB8Cugw_39);
					nimln_(3810, "system.nim");
					{
						NI T130_;
						T130_ = (formatters_55U7g4zhjHV9bCI6emTgDiA ? formatters_55U7g4zhjHV9bCI6emTgDiA->Sup.len : 0);
						if (!!((T130_ == L_7))) goto LA131_;
						failedAssertImpl_aDmpBTs9cPuXp0Mp9cfiNeyA(((NimStringDesc*) &TM_4qp2gZX9anqPB0kpcB8Cugw_6));
					}
					LA131_: ;
				} LA127: ;
			}
		}
		nimln_(474, "unittest.nim");
		pushSafePoint(&TM_4qp2gZX9anqPB0kpcB8Cugw_40);
		TM_4qp2gZX9anqPB0kpcB8Cugw_40.status = _setjmp(TM_4qp2gZX9anqPB0kpcB8Cugw_40.context);
		if (TM_4qp2gZX9anqPB0kpcB8Cugw_40.status == 0) {
			{
				nimln_(583, "unittest.nim");
				asgnRefNoCycle((void**) (&colonc1__WzG62vRKCCCuEmzM9bJ2gjA_3), helloworld_gsKQNDh3DKS9bk2U4dhinhw(((NimStringDesc*) &TM_4qp2gZX9anqPB0kpcB8Cugw_42)));
				nimln_(636, "unittest.nim");
				{
					NimStringDesc* T139_;
					nimln_(633, "unittest.nim");
					nimln_(612, "unittest.nim");
					if (!!(eqStrings(colonc1__WzG62vRKCCCuEmzM9bJ2gjA_3, ((NimStringDesc*) &TM_4qp2gZX9anqPB0kpcB8Cugw_43)))) goto LA137_;
					nimln_(637, "unittest.nim");
					checkpoint_4nBz3prx9cKVVOoTZb4rNCQ(((NimStringDesc*) &TM_4qp2gZX9anqPB0kpcB8Cugw_44));
					nimln_(588, "unittest.nim");
					T139_ = (NimStringDesc*)0;
					nimln_(612, "unittest.nim");
					T139_ = rawNewString(colonc1__WzG62vRKCCCuEmzM9bJ2gjA_3->Sup.len + 22);
appendString(T139_, ((NimStringDesc*) &TM_4qp2gZX9anqPB0kpcB8Cugw_45));
appendString(T139_, colonc1__WzG62vRKCCCuEmzM9bJ2gjA_3);
					checkpoint_4nBz3prx9cKVVOoTZb4rNCQ(T139_);
					nimln_(529, "unittest.nim");
					testStatusIMPL_Q4qcz3YlFyWrLneTJlsS4Q_3 = ((tyEnum_TestStatus_W9bTUg9c9a7UlIYkKYmd5uasQ) 1);
					nimln_(533, "unittest.nim");
					ensureInitialized_8zybqvexf9aYkm9bmgyU3eLg();
					{
						NI volatile i_8;
						NI L_8;
						NI T141_;
						nimln_(3805, "system.nim");
						i_8 = ((NI) 0);
						nimln_(3806, "system.nim");
						T141_ = (formatters_55U7g4zhjHV9bCI6emTgDiA ? formatters_55U7g4zhjHV9bCI6emTgDiA->Sup.len : 0);
						L_8 = T141_;
						{
							nimln_(3807, "system.nim");
							while (1) {
								NI TM_4qp2gZX9anqPB0kpcB8Cugw_47;
								if (!(i_8 < L_8)) goto LA143;
								nimln_(3808, "system.nim");
								if ((NU)(i_8) >= (NU)(formatters_55U7g4zhjHV9bCI6emTgDiA->Sup.len)) raiseIndexError();
								asgnRef((void**) (&formatter_6vZ0eCyziJIpjOJxE6ZZSA_8), formatters_55U7g4zhjHV9bCI6emTgDiA->data[i_8]);
								nimln_(540, "unittest.nim");
								failureOccurred_i9ctYnjK2z9bxX9cq0gYct9cIA(formatter_6vZ0eCyziJIpjOJxE6ZZSA_8, checkpoints_bq5hLRYOyiTcYy29a9akD9c9bQ, NIM_NIL);
								nimln_(3809, "system.nim");
								TM_4qp2gZX9anqPB0kpcB8Cugw_47 = addInt(i_8, ((NI) 1));
								i_8 = (NI)(TM_4qp2gZX9anqPB0kpcB8Cugw_47);
								nimln_(3810, "system.nim");
								{
									NI T146_;
									T146_ = (formatters_55U7g4zhjHV9bCI6emTgDiA ? formatters_55U7g4zhjHV9bCI6emTgDiA->Sup.len : 0);
									if (!!((T146_ == L_8))) goto LA147_;
									failedAssertImpl_aDmpBTs9cPuXp0Mp9cfiNeyA(((NimStringDesc*) &TM_4qp2gZX9anqPB0kpcB8Cugw_6));
								}
								LA147_: ;
							} LA143: ;
						}
					}
					nimln_(543, "unittest.nim");
					{
						if (!abortOnError_Bte3Uiwc4Q19ago2N4C89cUA) goto LA151_;
						exit(nim_program_result);
					}
					LA151_: ;
					nimln_(545, "unittest.nim");
					if (checkpoints_bq5hLRYOyiTcYy29a9akD9c9bQ) { nimGCunrefNoCycle(checkpoints_bq5hLRYOyiTcYy29a9akD9c9bQ); checkpoints_bq5hLRYOyiTcYy29a9akD9c9bQ = NIM_NIL; }
					checkpoints_bq5hLRYOyiTcYy29a9akD9c9bQ = (tySequence_sM4lkSb7zS6F7OVMvW9cffQ*) newSeqRC1((&NTI_sM4lkSb7zS6F7OVMvW9cffQ_), 0);
				}
				LA137_: ;
			}
			popSafePoint();
		}
		else {
			popSafePoint();
			setFrame((TFrame*)&FR_);
			{
				NimStringDesc* T155_;
				NimStringDesc* T156_;
				Exception* T157_;
				TM_4qp2gZX9anqPB0kpcB8Cugw_40.status = 0;
				nimln_(482, "unittest.nim");
				T155_ = (NimStringDesc*)0;
				T156_ = (NimStringDesc*)0;
				T156_ = getCurrentExceptionMsg_fOe1OXzHoGbgrd7IEmbp5Qsystem();
				T155_ = rawNewString(T156_->Sup.len + 21);
appendString(T155_, ((NimStringDesc*) &TM_4qp2gZX9anqPB0kpcB8Cugw_15));
appendString(T155_, T156_);
				checkpoint_4nBz3prx9cKVVOoTZb4rNCQ(T155_);
				nimln_(483, "unittest.nim");
				T157_ = (Exception*)0;
				T157_ = getCurrentException();
				asgnRefNoCycle((void**) (&stackTrace_yo79audNUOaALqoPY6lz8tQ_3), getStackTrace_OenGRUrwbq9c3AFUxAFv9cuA(T157_));
				nimln_(529, "unittest.nim");
				testStatusIMPL_Q4qcz3YlFyWrLneTJlsS4Q_3 = ((tyEnum_TestStatus_W9bTUg9c9a7UlIYkKYmd5uasQ) 1);
				nimln_(533, "unittest.nim");
				ensureInitialized_8zybqvexf9aYkm9bmgyU3eLg();
				{
					NI i_9;
					NI L_9;
					NI T159_;
					nimln_(3805, "system.nim");
					i_9 = ((NI) 0);
					nimln_(3806, "system.nim");
					T159_ = (formatters_55U7g4zhjHV9bCI6emTgDiA ? formatters_55U7g4zhjHV9bCI6emTgDiA->Sup.len : 0);
					L_9 = T159_;
					{
						nimln_(3807, "system.nim");
						while (1) {
							NI TM_4qp2gZX9anqPB0kpcB8Cugw_50;
							if (!(i_9 < L_9)) goto LA161;
							nimln_(3808, "system.nim");
							if ((NU)(i_9) >= (NU)(formatters_55U7g4zhjHV9bCI6emTgDiA->Sup.len)) raiseIndexError();
							asgnRef((void**) (&formatter_6vZ0eCyziJIpjOJxE6ZZSA_9), formatters_55U7g4zhjHV9bCI6emTgDiA->data[i_9]);
							nimln_(538, "unittest.nim");
							failureOccurred_i9ctYnjK2z9bxX9cq0gYct9cIA(formatter_6vZ0eCyziJIpjOJxE6ZZSA_9, checkpoints_bq5hLRYOyiTcYy29a9akD9c9bQ, stackTrace_yo79audNUOaALqoPY6lz8tQ_3);
							nimln_(3809, "system.nim");
							TM_4qp2gZX9anqPB0kpcB8Cugw_50 = addInt(i_9, ((NI) 1));
							i_9 = (NI)(TM_4qp2gZX9anqPB0kpcB8Cugw_50);
							nimln_(3810, "system.nim");
							{
								NI T164_;
								T164_ = (formatters_55U7g4zhjHV9bCI6emTgDiA ? formatters_55U7g4zhjHV9bCI6emTgDiA->Sup.len : 0);
								if (!!((T164_ == L_9))) goto LA165_;
								failedAssertImpl_aDmpBTs9cPuXp0Mp9cfiNeyA(((NimStringDesc*) &TM_4qp2gZX9anqPB0kpcB8Cugw_6));
							}
							LA165_: ;
						} LA161: ;
					}
				}
				nimln_(543, "unittest.nim");
				{
					if (!abortOnError_Bte3Uiwc4Q19ago2N4C89cUA) goto LA169_;
					exit(nim_program_result);
				}
				LA169_: ;
				nimln_(545, "unittest.nim");
				if (checkpoints_bq5hLRYOyiTcYy29a9akD9c9bQ) { nimGCunrefNoCycle(checkpoints_bq5hLRYOyiTcYy29a9akD9c9bQ); checkpoints_bq5hLRYOyiTcYy29a9akD9c9bQ = NIM_NIL; }
				checkpoints_bq5hLRYOyiTcYy29a9akD9c9bQ = (tySequence_sM4lkSb7zS6F7OVMvW9cffQ*) newSeqRC1((&NTI_sM4lkSb7zS6F7OVMvW9cffQ_), 0);
				popCurrentException();
			}
		}
		{
			NimStringDesc* T176_;
			NimStringDesc* T177_;
			nimln_(487, "unittest.nim");
			{
				NI TM_4qp2gZX9anqPB0kpcB8Cugw_51;
				if (!(testStatusIMPL_Q4qcz3YlFyWrLneTJlsS4Q_3 == ((tyEnum_TestStatus_W9bTUg9c9a7UlIYkKYmd5uasQ) 1))) goto LA174_;
				nimln_(488, "unittest.nim");
				TM_4qp2gZX9anqPB0kpcB8Cugw_51 = addInt(nim_program_result, ((NI) 1));
				nim_program_result = (NI)(TM_4qp2gZX9anqPB0kpcB8Cugw_51);
			}
			LA174_: ;
			nimln_(489, "unittest.nim");
			chckNil((void*)(&testResult_zKJcLcg3TmFPRC7R7c9cT9bg_3));
			genericReset((void*)(&testResult_zKJcLcg3TmFPRC7R7c9cT9bg_3), (&NTI_GEvSVSxdPWWgMGM48ywEYQ_));
			T176_ = (NimStringDesc*)0;
			T176_ = testResult_zKJcLcg3TmFPRC7R7c9cT9bg_3.suiteName; testResult_zKJcLcg3TmFPRC7R7c9cT9bg_3.suiteName = copyStringRC1(NIM_NIL);
			if (T176_) nimGCunrefNoCycle(T176_);
			T177_ = (NimStringDesc*)0;
			T177_ = testResult_zKJcLcg3TmFPRC7R7c9cT9bg_3.testName; testResult_zKJcLcg3TmFPRC7R7c9cT9bg_3.testName = copyStringRC1(((NimStringDesc*) &TM_4qp2gZX9anqPB0kpcB8Cugw_37));
			if (T177_) nimGCunrefNoCycle(T177_);
			testResult_zKJcLcg3TmFPRC7R7c9cT9bg_3.status = testStatusIMPL_Q4qcz3YlFyWrLneTJlsS4Q_3;
			nimln_(494, "unittest.nim");
			testEnded_xoIS1BdhYWQ6hhMP22XXiw(testResult_zKJcLcg3TmFPRC7R7c9cT9bg_3);
			nimln_(495, "unittest.nim");
			if (checkpoints_bq5hLRYOyiTcYy29a9akD9c9bQ) { nimGCunrefNoCycle(checkpoints_bq5hLRYOyiTcYy29a9akD9c9bQ); checkpoints_bq5hLRYOyiTcYy29a9akD9c9bQ = NIM_NIL; }
			checkpoints_bq5hLRYOyiTcYy29a9akD9c9bQ = (tySequence_sM4lkSb7zS6F7OVMvW9cffQ*) newSeqRC1((&NTI_sM4lkSb7zS6F7OVMvW9cffQ_), 0);
		}
		if (TM_4qp2gZX9anqPB0kpcB8Cugw_40.status != 0) reraiseException();
	}
	LA122_: ;
	popFrame();
}

NIM_EXTERNC N_NOINLINE(void, helloworld_testDatInit000)(void) {
}

