/* Generated by Nim Compiler v0.18.0 */
/*   (c) 2018 Andreas Rumpf */
/* The generated code is subject to the original license. */
/* Compiled for: MacOSX, amd64, clang */
/* Command for C compiler:
   clang -c  -w  -I/Users/lowks/.asdf/installs/nim/v0.18.0/lib -o /Users/lowks/exercism/nim/bob/nimcache/bob.o /Users/lowks/exercism/nim/bob/nimcache/bob.c */
#define NIM_NEW_MANGLING_RULES
#define NIM_INTBITS 64

#include "nimbase.h"
#include <string.h>
#undef LANGUAGE_C
#undef MIPSEB
#undef MIPSEL
#undef PPC
#undef R3000
#undef R4000
#undef i386
#undef linux
#undef mips
#undef near
#undef powerpc
#undef unix
typedef struct NimStringDesc NimStringDesc;
typedef struct TGenericSeq TGenericSeq;
typedef struct tyObject_HSlice_x7qpDivRIi6zcMSMsudNPA tyObject_HSlice_x7qpDivRIi6zcMSMsudNPA;
struct TGenericSeq {
NI len;
NI reserved;
};
struct NimStringDesc {
  TGenericSeq Sup;
NIM_CHAR data[SEQ_DECL_SIZE];
};
typedef NU8 tySet_tyChar_nmiMWKVIe46vacnhAFrQvw[32];
struct tyObject_HSlice_x7qpDivRIi6zcMSMsudNPA {
NI a;
NI b;
};
N_LIB_PRIVATE N_NIMCALL(NimStringDesc*, hey_UEq6cbqscr3kBFoZ70CHFg)(NimStringDesc* sentence);
N_LIB_PRIVATE N_NIMCALL(NimStringDesc*, nsuStrip)(NimStringDesc* s, NIM_BOOL leading, NIM_BOOL trailing, tySet_tyChar_nmiMWKVIe46vacnhAFrQvw chars);
N_NIMCALL(NimStringDesc*, copyString)(NimStringDesc* src);
N_LIB_PRIVATE N_NIMCALL(NimStringDesc*, nsuToUpperStr)(NimStringDesc* s);
static N_INLINE(NIM_BOOL, eqStrings)(NimStringDesc* a, NimStringDesc* b);
static N_INLINE(NIM_BOOL, equalMem_fmeFeLBvgmAHG9bC8ETS9bYQsystem)(void* a, void* b, NI size);
N_LIB_PRIVATE N_NIMCALL(NIM_BOOL, nsuIsDigitStr)(NimStringDesc* s);
static N_INLINE(NimStringDesc*, X5BX5D__lkBUIkH7j2jb0vaXPf2frAstrutils)(NimStringDesc* s, tyObject_HSlice_x7qpDivRIi6zcMSMsudNPA x);
static N_INLINE(NI, subInt)(NI a, NI b);
N_NOINLINE(void, raiseOverflow)(void);
static N_INLINE(NI, addInt)(NI a, NI b);
N_NIMCALL(NimStringDesc*, mnewString)(NI len);
N_NIMCALL(NimStringDesc*, mnewString)(NI len);
static N_INLINE(NI, chckRange)(NI i, NI a, NI b);
N_NOINLINE(void, raiseRangeError)(NI64 val);
N_NOINLINE(void, raiseIndexError)(void);
static N_INLINE(void, nimFrame)(TFrame* s);
N_LIB_PRIVATE N_NOINLINE(void, stackOverflow_II46IjNZztN9bmbxUD8dt8g)(void);
static N_INLINE(void, popFrame)(void);
static N_INLINE(tyObject_HSlice_x7qpDivRIi6zcMSMsudNPA, dotdot__ctxq0YSon7aLz7isCROwwQstrformat)(NI a, NI b);
N_LIB_PRIVATE N_NIMCALL(NIM_BOOL, nsuIsAlphaStr)(NimStringDesc* s);
N_LIB_PRIVATE N_NIMCALL(NimStringDesc*, nsuReplaceStr)(NimStringDesc* s, NimStringDesc* sub, NimStringDesc* by);
N_LIB_PRIVATE N_NIMCALL(NIM_BOOL, nsuEndsWith)(NimStringDesc* s, NimStringDesc* suffix);
extern TFrame* framePtr_HRfVMH3jYeBJz6Q6X9b6Ptw;
static NIM_CONST tySet_tyChar_nmiMWKVIe46vacnhAFrQvw TM_MmAecqTB2TFy5Y5EyJgJ4A_2 = {
0x00, 0x3E, 0x00, 0x00, 0x01, 0x00, 0x00, 0x00,
0x00, 0x00, 0x00, 0x00, 0x00, 0x00, 0x00, 0x00,
0x00, 0x00, 0x00, 0x00, 0x00, 0x00, 0x00, 0x00,
0x00, 0x00, 0x00, 0x00, 0x00, 0x00, 0x00, 0x00}
;
STRING_LITERAL(TM_MmAecqTB2TFy5Y5EyJgJ4A_3, "Fine. Be that way!", 18);
STRING_LITERAL(TM_MmAecqTB2TFy5Y5EyJgJ4A_9, " ", 1);
STRING_LITERAL(TM_MmAecqTB2TFy5Y5EyJgJ4A_10, "", 0);
STRING_LITERAL(TM_MmAecqTB2TFy5Y5EyJgJ4A_11, "!", 1);
STRING_LITERAL(TM_MmAecqTB2TFy5Y5EyJgJ4A_12, "\?", 1);
STRING_LITERAL(TM_MmAecqTB2TFy5Y5EyJgJ4A_13, "Whatever.", 9);
STRING_LITERAL(TM_MmAecqTB2TFy5Y5EyJgJ4A_14, ":) \?", 4);
STRING_LITERAL(TM_MmAecqTB2TFy5Y5EyJgJ4A_15, "Sure.", 5);
STRING_LITERAL(TM_MmAecqTB2TFy5Y5EyJgJ4A_16, "Whoa, chill out!", 16);

static N_INLINE(NIM_BOOL, equalMem_fmeFeLBvgmAHG9bC8ETS9bYQsystem)(void* a, void* b, NI size) {
	NIM_BOOL result;
	int T1_;
	result = (NIM_BOOL)0;
	T1_ = (int)0;
	T1_ = memcmp(a, b, ((size_t) (size)));
	result = (T1_ == ((NI32) 0));
	return result;
}

static N_INLINE(NIM_BOOL, eqStrings)(NimStringDesc* a, NimStringDesc* b) {
	NIM_BOOL result;
	NIM_BOOL T11_;
{	result = (NIM_BOOL)0;
	{
		if (!(a == b)) goto LA3_;
		result = NIM_TRUE;
		goto BeforeRet_;
	}
	LA3_: ;
	{
		NIM_BOOL T7_;
		T7_ = (NIM_BOOL)0;
		T7_ = (a == NIM_NIL);
		if (T7_) goto LA8_;
		T7_ = (b == NIM_NIL);
		LA8_: ;
		if (!T7_) goto LA9_;
		result = NIM_FALSE;
		goto BeforeRet_;
	}
	LA9_: ;
	T11_ = (NIM_BOOL)0;
	T11_ = ((*a).Sup.len == (*b).Sup.len);
	if (!(T11_)) goto LA12_;
	T11_ = equalMem_fmeFeLBvgmAHG9bC8ETS9bYQsystem(((void*) ((*a).data)), ((void*) ((*b).data)), ((NI) ((*a).Sup.len)));
	LA12_: ;
	result = T11_;
	goto BeforeRet_;
	}BeforeRet_: ;
	return result;
}

static N_INLINE(NI, subInt)(NI a, NI b) {
	NI result;
{	result = (NI)0;
	result = (NI)((NU64)(a) - (NU64)(b));
	{
		NIM_BOOL T3_;
		T3_ = (NIM_BOOL)0;
		T3_ = (((NI) 0) <= (NI)(result ^ a));
		if (T3_) goto LA4_;
		T3_ = (((NI) 0) <= (NI)(result ^ (NI)((NU64) ~(b))));
		LA4_: ;
		if (!T3_) goto LA5_;
		goto BeforeRet_;
	}
	LA5_: ;
	raiseOverflow();
	}BeforeRet_: ;
	return result;
}

static N_INLINE(NI, addInt)(NI a, NI b) {
	NI result;
{	result = (NI)0;
	result = (NI)((NU64)(a) + (NU64)(b));
	{
		NIM_BOOL T3_;
		T3_ = (NIM_BOOL)0;
		T3_ = (((NI) 0) <= (NI)(result ^ a));
		if (T3_) goto LA4_;
		T3_ = (((NI) 0) <= (NI)(result ^ b));
		LA4_: ;
		if (!T3_) goto LA5_;
		goto BeforeRet_;
	}
	LA5_: ;
	raiseOverflow();
	}BeforeRet_: ;
	return result;
}

static N_INLINE(NI, chckRange)(NI i, NI a, NI b) {
	NI result;
{	result = (NI)0;
	{
		NIM_BOOL T3_;
		T3_ = (NIM_BOOL)0;
		T3_ = (a <= i);
		if (!(T3_)) goto LA4_;
		T3_ = (i <= b);
		LA4_: ;
		if (!T3_) goto LA5_;
		result = i;
		goto BeforeRet_;
	}
	goto LA1_;
	LA5_: ;
	{
		raiseRangeError(((NI64) (i)));
	}
	LA1_: ;
	}BeforeRet_: ;
	return result;
}

static N_INLINE(void, nimFrame)(TFrame* s) {
	NI T1_;
	T1_ = (NI)0;
	{
		if (!(framePtr_HRfVMH3jYeBJz6Q6X9b6Ptw == NIM_NIL)) goto LA4_;
		T1_ = ((NI) 0);
	}
	goto LA2_;
	LA4_: ;
	{
		T1_ = ((NI) ((NI16)((*framePtr_HRfVMH3jYeBJz6Q6X9b6Ptw).calldepth + ((NI16) 1))));
	}
	LA2_: ;
	(*s).calldepth = ((NI16) (T1_));
	(*s).prev = framePtr_HRfVMH3jYeBJz6Q6X9b6Ptw;
	framePtr_HRfVMH3jYeBJz6Q6X9b6Ptw = s;
	{
		if (!((*s).calldepth == ((NI16) 2000))) goto LA9_;
		stackOverflow_II46IjNZztN9bmbxUD8dt8g();
	}
	LA9_: ;
}

static N_INLINE(void, popFrame)(void) {
	framePtr_HRfVMH3jYeBJz6Q6X9b6Ptw = (*framePtr_HRfVMH3jYeBJz6Q6X9b6Ptw).prev;
}

static N_INLINE(NimStringDesc*, X5BX5D__lkBUIkH7j2jb0vaXPf2frAstrutils)(NimStringDesc* s, tyObject_HSlice_x7qpDivRIi6zcMSMsudNPA x) {
	NimStringDesc* result;
	NI a;
	NI L;
	NI TM_MmAecqTB2TFy5Y5EyJgJ4A_4;
	NI TM_MmAecqTB2TFy5Y5EyJgJ4A_5;
	NI TM_MmAecqTB2TFy5Y5EyJgJ4A_6;
	nimfr_("[]", "system.nim");
	result = (NimStringDesc*)0;
	nimln_(3556, "system.nim");
	a = x.a;
	nimln_(3557, "system.nim");
	nimln_(3546, "system.nim");
	nimln_(3557, "system.nim");
	TM_MmAecqTB2TFy5Y5EyJgJ4A_4 = subInt((s ? s->Sup.len : 0), x.b);
	TM_MmAecqTB2TFy5Y5EyJgJ4A_5 = subInt((NI)(TM_MmAecqTB2TFy5Y5EyJgJ4A_4), a);
	TM_MmAecqTB2TFy5Y5EyJgJ4A_6 = addInt((NI)(TM_MmAecqTB2TFy5Y5EyJgJ4A_5), ((NI) 1));
	L = (NI)(TM_MmAecqTB2TFy5Y5EyJgJ4A_6);
	nimln_(3558, "system.nim");
	result = mnewString(((NI)chckRange(L, ((NI) 0), ((NI) IL64(9223372036854775807)))));
	{
		NI i;
		NI i_2;
		i = (NI)0;
		nimln_(3519, "system.nim");
		i_2 = ((NI) 0);
		{
			nimln_(3520, "system.nim");
			while (1) {
				NI TM_MmAecqTB2TFy5Y5EyJgJ4A_7;
				NI TM_MmAecqTB2TFy5Y5EyJgJ4A_8;
				if (!(i_2 < L)) goto LA3;
				nimln_(3521, "system.nim");
				i = i_2;
				if ((NU)(i) > (NU)(result->Sup.len)) raiseIndexError();
				nimln_(3559, "system.nim");
				TM_MmAecqTB2TFy5Y5EyJgJ4A_7 = addInt(i, a);
				if ((NU)((NI)(TM_MmAecqTB2TFy5Y5EyJgJ4A_7)) > (NU)(s->Sup.len)) raiseIndexError();
				result->data[i] = s->data[(NI)(TM_MmAecqTB2TFy5Y5EyJgJ4A_7)];
				nimln_(3522, "system.nim");
				TM_MmAecqTB2TFy5Y5EyJgJ4A_8 = addInt(i_2, ((NI) 1));
				i_2 = (NI)(TM_MmAecqTB2TFy5Y5EyJgJ4A_8);
			} LA3: ;
		}
	}
	popFrame();
	return result;
}

static N_INLINE(tyObject_HSlice_x7qpDivRIi6zcMSMsudNPA, dotdot__ctxq0YSon7aLz7isCROwwQstrformat)(NI a, NI b) {
	tyObject_HSlice_x7qpDivRIi6zcMSMsudNPA result;
	nimfr_("..", "system.nim");
	memset((void*)(&result), 0, sizeof(result));
	nimln_(325, "system.nim");
	result.a = a;
	nimln_(326, "system.nim");
	result.b = b;
	popFrame();
	return result;
}

N_LIB_PRIVATE N_NIMCALL(NimStringDesc*, hey_UEq6cbqscr3kBFoZ70CHFg)(NimStringDesc* sentence) {
	NimStringDesc* result;
	NimStringDesc* input_sentence;
	nimfr_("hey", "bob.nim");
{	result = (NimStringDesc*)0;
	nimln_(4, "bob.nim");
	input_sentence = nsuStrip(sentence, NIM_TRUE, NIM_TRUE, TM_MmAecqTB2TFy5Y5EyJgJ4A_2);
	nimln_(5, "bob.nim");
	{
		if (!((input_sentence) && (input_sentence)->Sup.len == 0)) goto LA3_;
		nimln_(6, "bob.nim");
		result = copyString(((NimStringDesc*) &TM_MmAecqTB2TFy5Y5EyJgJ4A_3));
		goto BeforeRet_;
	}
	LA3_: ;
	nimln_(7, "bob.nim");
	{
		NIM_BOOL T7_;
		NimStringDesc* T8_;
		tyObject_HSlice_x7qpDivRIi6zcMSMsudNPA T10_;
		NimStringDesc* T11_;
		NIM_BOOL T12_;
		T7_ = (NIM_BOOL)0;
		T8_ = (NimStringDesc*)0;
		T8_ = nsuToUpperStr(input_sentence);
		T7_ = eqStrings(T8_, sentence);
		if (!(T7_)) goto LA9_;
		T10_ = dotdot__ctxq0YSon7aLz7isCROwwQstrformat(((NI) 0), ((NI) 2));
		T11_ = (NimStringDesc*)0;
		T11_ = X5BX5D__lkBUIkH7j2jb0vaXPf2frAstrutils(input_sentence, T10_);
		T12_ = (NIM_BOOL)0;
		T12_ = nsuIsDigitStr(T11_);
		T7_ = !(T12_);
		LA9_: ;
		if (!T7_) goto LA13_;
		nimln_(8, "bob.nim");
		{
			NIM_BOOL T17_;
			NimStringDesc* T18_;
			NIM_BOOL T19_;
			NIM_BOOL T21_;
			T17_ = (NIM_BOOL)0;
			T18_ = (NimStringDesc*)0;
			T18_ = nsuReplaceStr(input_sentence, ((NimStringDesc*) &TM_MmAecqTB2TFy5Y5EyJgJ4A_9), ((NimStringDesc*) &TM_MmAecqTB2TFy5Y5EyJgJ4A_10));
			T19_ = (NIM_BOOL)0;
			T19_ = nsuIsAlphaStr(T18_);
			T17_ = !(T19_);
			if (!(T17_)) goto LA20_;
			T21_ = (NIM_BOOL)0;
			T21_ = nsuEndsWith(input_sentence, ((NimStringDesc*) &TM_MmAecqTB2TFy5Y5EyJgJ4A_11));
			if (T21_) goto LA22_;
			T21_ = nsuEndsWith(input_sentence, ((NimStringDesc*) &TM_MmAecqTB2TFy5Y5EyJgJ4A_12));
			LA22_: ;
			T17_ = !(T21_);
			LA20_: ;
			if (!T17_) goto LA23_;
			nimln_(9, "bob.nim");
			result = copyString(((NimStringDesc*) &TM_MmAecqTB2TFy5Y5EyJgJ4A_13));
			goto BeforeRet_;
		}
		goto LA15_;
		LA23_: ;
		{
			nimln_(10, "bob.nim");
			if (!eqStrings(input_sentence, ((NimStringDesc*) &TM_MmAecqTB2TFy5Y5EyJgJ4A_14))) goto LA26_;
			nimln_(11, "bob.nim");
			result = copyString(((NimStringDesc*) &TM_MmAecqTB2TFy5Y5EyJgJ4A_15));
			goto BeforeRet_;
		}
		goto LA15_;
		LA26_: ;
		LA15_: ;
		nimln_(12, "bob.nim");
		result = copyString(((NimStringDesc*) &TM_MmAecqTB2TFy5Y5EyJgJ4A_16));
		goto BeforeRet_;
	}
	goto LA5_;
	LA13_: ;
	{
		NIM_BOOL T29_;
		nimln_(13, "bob.nim");
		T29_ = (NIM_BOOL)0;
		T29_ = nsuEndsWith(input_sentence, ((NimStringDesc*) &TM_MmAecqTB2TFy5Y5EyJgJ4A_12));
		if (!T29_) goto LA30_;
		nimln_(14, "bob.nim");
		result = copyString(((NimStringDesc*) &TM_MmAecqTB2TFy5Y5EyJgJ4A_15));
		goto BeforeRet_;
	}
	goto LA5_;
	LA30_: ;
	{
		nimln_(16, "bob.nim");
		result = copyString(((NimStringDesc*) &TM_MmAecqTB2TFy5Y5EyJgJ4A_13));
		goto BeforeRet_;
	}
	LA5_: ;
	}BeforeRet_: ;
	popFrame();
	return result;
}
NIM_EXTERNC N_NOINLINE(void, unknown_bobInit000)(void) {
	nimfr_("bob", "bob.nim");
	popFrame();
}

NIM_EXTERNC N_NOINLINE(void, unknown_bobDatInit000)(void) {
}

